### ISSUE TITLE
Upload doesn't work

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#100]
**Describe the bug**
Upload doesn't upload anything.

**To Reproduce**
1. Click upload and select any files
2. Click on "Send"
3. It goes to 100% and nothing else happens

![demonstration](https://user-images.githubusercontent.com/24497821/218334945-fad8fe33-1876-41b8-96c3-5900747ca30b.gif)

**Expected behavior**
File uploads to the server and gets saved to the folder

**Environment (please complete the following information):**
 - OS: Windows 11 22H2 22621.1194
 - Browser Chrome 109, 110
 - Version 0.31.0

**Additional context**
0.30.0 is the last version uploading worked

**Comment by rejetto** [comment]
this is ugly, sorry.
I will publish a fixed version today.

**Comment by rejetto** [comment]
fixed, thanks for reporting
https://github.com/rejetto/hfs/releases/tag/v0.32.0
