### ISSUE TITLE
Alphabetize Titles Sort

### ISSUE THREAD

**Issue by yurixahri** [rejetto/hfs#105]
Could you add this type of sort into name sort ? it would be convenient for ordering files and folders by number.
![image](https://user-images.githubusercontent.com/111081318/219478850-4cd92898-ed56-4cef-b0e4-d90e2a09bb63.png)

**Comment by rejetto** [comment]
find it in next release
<img width="192" alt="image" src="https://user-images.githubusercontent.com/1367199/219709338-89027fe3-66ee-4400-9633-9a1bdae35835.png">
