### ISSUE TITLE
Login glitch

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#108]
**Describe the bug**
If root folder is granted only logined users a get error (white-page) when login is expired.
Demo: https://share.dvor-net.ptz.ru/dLiV604aui.mp4

![image](https://user-images.githubusercontent.com/7496555/219905647-7c1d2a70-2a88-417a-adb5-43ffe158a78c.png)

**Comment by rejetto** [comment]
it used to work, it's a regression introduced in 0.33.0

**Comment by rejetto** [comment]
fixed https://github.com/rejetto/hfs/releases/tag/v0.35.0
