### ISSUE TITLE
Folders and files with the same name conflict

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#112]
Folders and files with the same name conflict with each other in weird way
![same_name](https://user-images.githubusercontent.com/24497821/220484916-6e8704f2-3489-4f32-b87d-2ae7ee2a9096.gif)

**Environment:**
 - OS: Windows 11 22H2 22621.1194
 - Version 0.35.0

**Comment by rejetto** [comment]
i'm going to prevent creation of folders and also renaming that collide with existing names

**Comment by rejetto** [comment]
https://github.com/rejetto/hfs/releases/tag/v0.36.0
