### ISSUE TITLE
Log-in/out

### ISSUE THREAD

**Issue by yurixahri** [rejetto/hfs#116]
Reload the page will cause the problem, although the account is still login and contents is still accessible, the button return to the login phase.

https://user-images.githubusercontent.com/111081318/221009313-d4d17b8c-1b6c-42f2-aa3c-4c76032a9fc8.mp4

**Comment by rejetto** [comment]
I cannot reproduce the problem.
Did you modify index.html ? Like, you removed this line? ` <script>SESSION = _HFS_SESSION_</script>`

**Comment by yurixahri** [comment]
oh you're right, somehow it did miss that line. I remembered that just adding things, not to remove some lines like that. weird.

**Comment by rejetto** [comment]
I advice you to not modify frontend directly like that, because bad things like this happen.
In facts, you should verify that the bug happens with official frontend before reporting, and you can see why in this example. :)

Another bad thing that can happen is that when i'll publish changes in the frontend it may be hard for you to integrate those changes.
And some changes may be mandatory, like I may modify an api (and I already planned to make one rename).

My advice is that you try to achieve your changes with supported features, like the "custom header".
If you are not happy with what you got, we can discuss what features to add.

**Comment by yurixahri** [comment]
Things i added is not related to the root structure or default script, so i did it as one-time job, keep everything in one place and bring it to anywhere i go. Some features are missing like allow CORS, it's not likes everyone need it so i figured and added myself. I agree that it's not intended to be modded directly likes that, but it's easier for me to keep track the things i added than via work-around ways.

Unless there is a major update, i'll not update the hfs and remain stable. sr for the inconvenient.

**Comment by rejetto** [comment]
the project aims to be customizable (to some extent), but I need to understand people's needs to design new features.
For example I want people to be able to make the customization you made without having to change sources, both for simplicity but also because it makes updates harder and an outdated server software is a risk.

CORS should be fairly quicky to add. I'm not sure if as a plugin.

**Comment by yurixahri** [comment]
Here the list of custom things i made (see if there is any useful things to be noted) :
- Adding elements outside the root (above and below)

> ![image](https://user-images.githubusercontent.com/111081318/221114942-2372b5a2-54aa-415c-9a53-35e83d8bc7d5.png)
> Although custom header is great, it only creates elements inside it. Idk if HFS events (afterEntryname) can make it possible or not

- BrowseFiles.ts line 192

> ![image](https://user-images.githubusercontent.com/111081318/221116463-f761ceed-e0bb-42cc-a5d0-ec42805a30d6.png)
> relativePath -> relativePath.substring(0,relativePath.lastIndexOf("/"))

- src\index.ts (adding CORS)

> ```
> const cors = require('koa-cors')
> .use(cors())
> ```

- Others can be made into a plugin, but since it was made to fit my need, it'll take time to make it globally

**Comment by rejetto** [comment]
thank you very much, your post is useful.

You are customizing <title>.  This could technically be done with a <script> but it would be a bit clumsy, and bad for SEO. I'm going  to add an option in configuration.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/1367199/221227223-4eb98c73-6ef4-4c24-81e0-7876facc56dc.png">

Some of the other stuff you are adding would work inside #root, or can be adjusted to make it work, but I think it's better to give a simpler solution, and the ability to work with a good editor for this extra html stuff.

I could create (initially) empty files top.html and bottom.html, in same folder of config.yaml, and their content would automatically  be inserted when loading index.html . Wouldn't this be quite convenient?

top.html would be inserted just after `<body>`, but all the stuff that you put in `<head>` work inside body too, so I for now would avoid creating a third file if not necessary.

**Comment by rejetto** [comment]
i agree with your removing the final / on folders, i'm doing it for next release.
People/themes wanting it back can add it with a simple style

        li.folder a::after { content: "/" }

**Comment by yurixahri** [comment]
also i added a bunch of libraries to make things work, which is not supported right now

> i'm testing it with custom header, seems like it only works for stylesheet, not js libraries

![image](https://user-images.githubusercontent.com/111081318/221289234-1c5ebfe7-48c9-4e09-967b-99dddc7c1025.png)

**Comment by rejetto** [comment]
i just published "cors" plugin for hfs, in case you are interested

**Comment by yurixahri** [comment]
i've just ported the audio player into a plugin. with the new update and new ways to customize i would say that it is quite ez for now to do such things 
![image](https://user-images.githubusercontent.com/111081318/224763854-13467131-fda2-489d-8602-c02c82ef31be.png)

btw thanks for the cors.

**Comment by rejetto** [comment]
if you find other things missing that you need, let me know!
