### ISSUE TITLE
Uploading with drag and drop Problem

### ISSUE THREAD

**Issue by arkprocession** [rejetto/hfs#130]
Hello, thanks for all the effort in the new updates they really add QOL functions.

Dragging a folder uploads a "file" version of the folder, without its content, for now i am sticking to using the context menus.

Requests:

Integrated Video Player
Integrated Text editor.

ability to create a "share link" to an specific file or folder, and have the option to encrypt them.
For example, the person that receives the link, has only access to that file/folder and if you chose to share it with a password, then it will be requested before accessing the files.

Honestly that would be really extra, hfs as it is now, its perfect

**Comment by rejetto** [comment]
sadly, drag of folders is not supported by browsers, currently.
there's nothing i can do about it.

video player and text editor won't be part of hfs, but can be made by plugins.

some share-link feature is in to-do.
it's not clear what you mean by "encrypt".

to share it with a password, why don't you create an account and assign it to the folder?

**Comment by arkprocession** [comment]
that makes sense!
my idea of sharing with password was based around the fact sometimes you want to share something with someone like a one-time thing, and instead of creating and account and making them login in, you can quick share to them.

i mostly use authenticating though.

**Comment by rejetto** [comment]
yes, an access that expires after a time you decide, but then why the password
so people need to share 2 texts instead of 1? doesn't look safer to me
