### ISSUE TITLE
Crash on clicking "Change"

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#137]
Clicking Change option in Link on any file/folder in the tree of VFS crashes the Admin panel

**Screenshots**
![change_crash](https://user-images.githubusercontent.com/24497821/223005327-18472feb-9cfb-46ac-ba8f-319d878b1c9b.gif)

**Environment:**
 - OS: Windows 11 22H2 22621.1265
 - Browser: Chrome 111
 - Version: 0.38.1

**Additional context**
![image](https://user-images.githubusercontent.com/24497821/223005679-f8633f6e-5022-4a6f-8fb8-c720edaec94e.png)

**Comment by rejetto** [comment]
thanks for reporting.
fix included in next release.

**Comment by rejetto** [comment]
until next release, you should be able to workaround the problem by editing config.yaml and adding a line like this

    base_url: http://youraddress
