### ISSUE TITLE
Possible EventEmitter memory leak warning

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#151]
When looking for online plugins there's a warning in the console.
`(node:39436) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [IncomingMessage]. Use emitter.setMaxListeners() to increase limit
(Use hfs --trace-warnings ... to show where the warning was created)`

**Environment:**
 - OS: Windows 11 22H2 22621.1344
 - Browser: Chrome 112
 - Version: 0.40.0

**Additional context**
I've tried to launch with --trace-warnings parameter but the output is still the same.

**Comment by rejetto** [comment]
thanks for reporting! released 0.40.1
