### ISSUE TITLE
Wrong language selection order?

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#152]
I added a `ru` translation to hfs and since my browser's language is `en-GB` and not `en` it selects `ru`.

**Environment:**
 - OS: Windows 11 22H2 22621.1344
 - Browser: Chrome 112
 - Version: 0.40.0

**Additional context**
My language list in browser is `en-GB`, `en`, and `ru`
Adding another language file with `en-GB` will select it.

**Comment by SanokKule** [comment]
When the main browser language is `en`, and there's `ru` also present, `ru` will be selected instead.

**Comment by rejetto** [comment]
right... english needs a special treatment since there's no file to be loaded

**Comment by rejetto** [comment]
thanks for reporting! released 0.40.1

**Comment by SanokKule** [comment]
Since i forgot to remove the normal `en` from the language list, it worked fine,
but the page will show in `ru` instead of `en` if `en-GB`, `ru` are browser languages.
I suppose you need to check if the language is `en-SOME_COUNTRY` and count `en` part as the language.
Also if i have a language that list looks like this, It will still choose `ru`.
```
Your browser's Accept-Language header:
en-GB,en-AU;
q=0.9,en-CA;
q=0.8,en-IN;
q=0.7,en-IE;
q=0.6,en-NZ;
q=0.5,en-ZA;
q=0.4,en-GB-oxendict;
q=0.3,en-US;
q=0.2,en;
q=0.1,ru;
q=0.1

**Comment by SanokKule** [comment]
Also i forgot to add, but adding or removing normal `en` in browser settings will change hfs' language into english,
but having it in there will not change the `Accept-Language` header in the above case.

**Comment by rejetto** [comment]
> Also if i have a language that list looks like this, It will still choose ru.

are you really sure?
because I didn't expect this behaviour, and also made a quick test here: with only italian lang loaded, this configuration is correctly showing me english.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1367199/226112050-84b96f43-790b-42cc-860a-6237490a9f77.png">

As soon as "it" is just above "en", I will get "it", and that's fine.

Side note: if you REMOVE 'en' and leave 'en-gb', current behavior is to still consider 'en', but not at the same position, at the bottom. I decided this way because if you wanted 'en', you should have set it. So, I thought that having it at the bottom was a softer option. I don't exclude changing my mind about it.

**Comment by SanokKule** [comment]
I added all those languages just as a test, and none of them trigger `en`.
Not sure if this is relevant, but there's `load_lang` 'output' i think: `{"embedded":"en","lang":["en-GB","en-AU","en-CA","en-IN","en-IE","en-NZ","en-ZA","en-GB-oxendict","en-US","ru"]}`

**Comment by SanokKule** [comment]
This is how my language list looked like 
![image](https://user-images.githubusercontent.com/24497821/226112601-d21f3b87-2607-4ecf-aa05-606582433ea2.png)

**Comment by rejetto** [comment]
ok, in your previous post you included "en".
<img width="95" alt="image" src="https://user-images.githubusercontent.com/1367199/226112603-4581da12-c98a-4397-ba2a-b06e50729cf7.png">

NOW it's expected, as I explained above.

**Comment by SanokKule** [comment]
Actually i didn't it's only shown here, and in `load_lang` it's not present

**Comment by rejetto** [comment]
is there a reason why you set so many languages and not just en-gb + en ?

**Comment by SanokKule** [comment]
Just as a test, when only `en-GB` and `ru` are present, the behaviour is the same

**Comment by rejetto** [comment]
yes, that's expected. You should not remove English, if you want it better than russian.

Thank you for your tests, by the way

**Comment by SanokKule** [comment]
So it's intended that it chooses `ru` even if `en-GB` is higher on the list?

**Comment by rejetto** [comment]
yes, because we don't have en-GB, and you removed 'en' yourself.
I suppose this is the best behaviour when you remove 'en'  🤔

**Comment by SanokKule** [comment]
I believe language selection should choose the closest language, all those languages i selected should trigger `en` as it's the language implied by the first part, and the second `-GB` is something like dialect.

**Comment by rejetto** [comment]
it seems like a good alternative way of thinking.
I'm not totally sure it's better.
Maybe I can do like you say but only in case there is NO english in your list.
