### ISSUE TITLE
HFS.onEvent randomly doesn't work?

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#154]
I'm making a plugin and when trying to add elements with ```HFS.onEvent('afterMenuBar', () => `html_code`)``` it randomly doesn't apply.
`beforeHeader` and `afterHeader` exhibit the same behaviour.

**Environment:**
 - OS: Windows 11 22H2 22621.1344
 - Browser: Chrome 112
 - Version: 0.40.0

**Comment by rejetto** [comment]
"doesn't apply" means you don't get html_code in the page?

**Comment by SanokKule** [comment]
Yes

**Comment by rejetto** [comment]
thanks for reporting! released 0.40.1

**Comment by rejetto** [comment]
if you want, we can talk about your plugin.
I'm both curious and want to understand if I can make things better for your goal.
The plugin system is quite young and probably needs improvements.
In case you may open a [new thread](https://github.com/rejetto/hfs/discussions/new/choose)

**Comment by SanokKule** [comment]
Well i never coded before, so it's just your player sample along with video player from [IlyaBOT](https://github.com/IlyaBOT), and i'm trying to make an image viewer.
I mostly have problems with understanding css and js, but it's not hfs' fault.
