### ISSUE TITLE
blocking specific extension

### ISSUE THREAD

**Issue by gogi100** [rejetto/hfs#157]
**Is your feature request related to a problem? Please describe.**
this requirement is not related with problem.

**Describe the solution you'd like**
i would like the option that it's block uploading files with specific extension.

**Describe alternatives you've considered**

**Additional context**

**Comment by rejetto** [comment]
BLOCK specific extension or ALLOW specific extension?

**Comment by gogi100** [comment]
I think, in the hfs default setting is allow all. If you set allow specific, and default block specific extension

**Comment by rejetto** [comment]
i don't understand the last part, "and default block specific extension".
Anyway, I'll consider the "allow extension", because that's actually what the browser can do.

**Comment by gogi100** [comment]
I think, you set option allow specific extension and all others blocked

**Comment by rejetto** [comment]
if you set to allow specific extension for upload on a specific folder, I think upload of a whole folder (the "pick folder" button) must be disabled

**Comment by gogi100** [comment]
I mean allow uploading doc, docx, xlsx, xls, zip, rar, 7z, and prohibit the
rest

**Comment by rejetto** [comment]
yes, and "folder" is also rest

**Comment by gogi100** [comment]
Uplading is possible in folders and subfolders. The permissions stay that
the user can uploade, see,but not download. The user can upload just pdf,
docx, zip...
