### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by yx3016** [rejetto/hfs#161]
I tried to translate it into Chinese, but the front end showed garbled code. How to deal with this?

![image](https://user-images.githubusercontent.com/81002806/225508090-bd135d4c-acd7-4b25-aa2d-79e5e3397017.png)

**Comment by rejetto** [comment]
you probably didn't save the file as UTF8.
Attach the file here so I can give it a look

**Comment by yx3016** [comment]
> you probably didn't save the file as UTF8. Attach the file here so I can give it a look

[hfs-lang-zh.zip](https://github.com/rejetto/hfs/files/10988633/hfs-lang-zh.zip)

**Comment by yx3016** [comment]
> you probably didn't save the file as UTF8. Attach the file here so I can give it a look
Get it done
Thanks！！
![image](https://user-images.githubusercontent.com/81002806/225564276-d05702af-c7e6-4689-a178-2c1ba73e0769.png)

**Comment by rejetto** [comment]
cool!
I will specify this detail in the translation guide.
Do you want to publish your translation for other users?

**Comment by yx3016** [comment]
[hfs-lang-zh.zip](https://github.com/rejetto/hfs/files/10989343/hfs-lang-zh.zip)
> cool! I will specify this detail in the translation guide. Do you want to publish your translation for other users?

After I have translated all, I will send it to you
