### ISSUE TITLE
Search, Zip window title

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#163]
I believe Search and Zip windows should have a title.

Like this:
![image](https://user-images.githubusercontent.com/24497821/225775588-ca5742f4-33fc-4c33-875e-cf5f964475ba.png)
![image](https://user-images.githubusercontent.com/24497821/225776065-3d8658c2-edcc-4167-b451-1a79d1834a45.png)

**Comment by rejetto** [comment]
sure!
