### ISSUE TITLE
New language support

### ISSUE THREAD

**Issue by yx3016** [rejetto/hfs#164]
New language support, Chinese.
[hfs-lang-zh.zip](https://github.com/rejetto/hfs/files/10998210/hfs-lang-zh.zip)

@rejetto

**Comment by rejetto** [comment]
thank you very much!
Is it ok that these are not translated?

        "n_files": "{n,plural,one{# file} other{# files}}",
        "n_folders": "{n,plural,one{# folder} other{# folders}}",
        "filter_count": "{n,plural, one{# filtered} other{# filtered}}",
        "select_count": "{n,plural, one{# selected} other{# selected}}",

**Comment by rejetto** [comment]
what type of chinese is this? 中国人 ?

https://github.com/rejetto/hfs/wiki/Available-languages

**Comment by yx3016** [comment]
> what type of chinese is this? 中国人 ?
> 
> https://github.com/rejetto/hfs/wiki/Available-languages

Simplified Chinese， Yes, I am Chinese

**Comment by yx3016** [comment]
> Is it ok that these are not translated?



> thank you very much! Is it ok that these are not translated?
> 
> ```
>     "n_files": "{n,plural,one{# file} other{# files}}",
>     "n_folders": "{n,plural,one{# folder} other{# folders}}",
>     "filter_count": "{n,plural, one{# filtered} other{# filtered}}",
>     "select_count": "{n,plural, one{# selected} other{# selected}}",
> ```

I don't know how to translate these, so let's explore them further in use before translating them!

**Comment by rejetto** [comment]
ok, i'm sure others will help us

**Comment by yx3016** [comment]
> > what type of chinese is this? 中国人 ?
> > https://github.com/rejetto/hfs/wiki/Available-languages
> 
> Simplified Chinese， Yes, I am Chinese

简体中文
