### ISSUE TITLE
Unable to share root drives

### ISSUE THREAD

**Issue by arkprocession** [rejetto/hfs#174]
Already mapped root drives from previous versions ignoring user, or account limitations (security risk). anyone can access my drives!
I deleted them to add them again but i get greyed out select button when selecting a root drive to share.

**Comment by rejetto** [comment]
i'm a bit confused. Can you add screenshots (or a video) to make it clearer?

**Comment by arkprocession** [comment]
cannot since already deleted the mappings, it goes like this:
I was using one or two versions behind the last update.
I had mapped c: g: and n: drives. Selected accounts were only one, mine.
i updated the fileserver with the newest version you provided, and opened the main page to find out my c:, g: and n: drives where listed without any account logged in.
i entered the configs deleted the old mappings from the old version and added them back, i realized i have to OPEN the c drive to map it as root, it is weird that the select button is greyed out if i select the c: drive as whole from the step before.
once i added them back they disappear when i am not logged in and appear when i log in, normal behaviour again!

i wanted to let you know that many people could have this issue if they updated and already had a config.yaml created.

**Comment by rejetto** [comment]
I will consider the rest of your post tomorrow, but in the meantime, the
first part of your problem is that in 0.39 I changed the way permissions
work.
What you see is now determined by the "see" permission, while in previous
versions the "download" permission was hiding.
I had to change it because it was impossible to make some useful
configurations.
The message in the release was not WARNING enough, I know, my fault.
When I realized that I warned users on telegram.

**Comment by rejetto** [comment]
> i realized i have to OPEN the c drive to map it as root, it is weird that the select button is greyed out if i select the c: drive as whole from the step before

this part is not clear to me. I tried adding C:\ and i had no problem. Maybe you can add screenshots or a video to show your problem.

> normal behaviour again!

This is probably because re-adding the entries you took care of setting the "see" permissions.

**Comment by rejetto** [comment]
no news? should i close this?
