### ISSUE TITLE
File Menu bad positioning

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#177]
File menu spawns way below the visible space when opening it in a folder with many files.

_Video demonstration sent privately._

**Environment:**
 - OS: Windows 11 22H2 22621.1413
 - Browser: Chrome 112
 - Version: 0.42.0

**Comment by SanokKule** [comment]
Fixed in 0.42.1

**Comment by rejetto** [comment]
i'm truly sorry.
I shall take more time before publishing.
