### ISSUE TITLE
select "/" as share files cause frontend become blank

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#183]
**To Reproduce**
1、select "/" as share files in the admin panel;
2、refresh the frontend or after login, that will show a blank webpage.

**Describe the bug**
a blank webpage only
**Expected behavior**
a files/documents tree will show
**Screenshots**
[missing]~

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - HFS Version:0.41.0 or 0.42.2
 - Browser: newest Chrome or Firefox, stable version, x64

**Additional context**

**Comment by rejetto** [comment]
I already tried this and didn't have any problem.
Did you ensure the user running hfs has rights for "/" ?

**Comment by dzw13579** [comment]
I have change the right to 0777 for "hfs"file, and run "hfs" in root enviroument before I got this problem😂maybe the only Problem is the rights of  hfs directory  is 0755? I'm not sure about that, my Ubuntu facing a power issue and I try to fix it tomorrow, after that, I will test again

**Comment by rejetto** [comment]
also copy here the output (console) of the server. It may contain errors.
If you've lost it, you may find debug.log

**Comment by rejetto** [comment]
i was not referring to permissions of "hfs" file.
with "root environment" do you mean the root user or root folder?
if root user, then i guess it's not a permission problem.

**Comment by dzw13579** [comment]
I used "sudo -i" to get the root privilege before running the "hfs"
"hfs"not in root folder, I put it in  "/usr/local/HFS_new"
