### ISSUE TITLE
add html code

### ISSUE THREAD

**Issue by rejetto** [rejetto/hfs#186]
_Originally posted by @xrivo1 in https://github.com/rejetto/hfs/discussions/139#discussioncomment-5492810_

> In HFS 2.4.0, I inserted a string generated by a website, which shows the data of users who lynch. This is the result. With version 0.42.3, however, I failed.
![Login page](https://user-images.githubusercontent.com/106228981/229212591-b8d43b4c-297f-49e1-bf03-b65ec4055eb1.jpg)

**Comment by rejetto** [comment]
per favore, apri una nuova discussion invece di rispondere ad altre, e sentiti libero di scrivere in italiano se preferisci 😉

it was better if you had posted the string you are talking about.
Anyway, you are supposed to insert that in admin-panel / custom html. The "top" section should fit.

**Comment by xrivo1** [comment]
Ti ringrazio molto.
Dicevo che nel file hfs.tpl di HFS 2.4.0, ho inserito la seguente stringa in questa posizione ( vedi allegato 1 ).
![Allegato 1](https://user-images.githubusercontent.com/106228981/229273404-e3ecfc04-fe2c-4771-b1c5-8811a3069008.jpg)

Mettendo la stessa stringa nella pagina custom HTML della versione 0.42.2 il risultato, quando mi connetto al server  è il seguente ( vedi allegato 2 ).

![Allegato 2](https://user-images.githubusercontent.com/106228981/229273405-003bd36d-ca6b-4e48-8498-b665b631fe78.jpg)

Sicuramente si tratta di un errore di compilazione della pagina, ma proprio non riesco a risolvere....

**Comment by rejetto** [comment]
`</html>` non fa parte del codice che devi copiare. Ricopio qui la tua stringa per comodità:
```
<div class="findiptitle">I tuoi dati</div><div id="findipwidget"></div><div class="findiplink" id="findipurl">Powered by <a href="http://www.find-ip.net/" target="_blank">Find-IP.net</a></div><script defer src="https://api.find-ip.net/widget.js?width=190&region=08"></script>
```

il problema che stai avendo a me lo dà solo se metto il codice nella sezione "after list".
Ora studierò il problema, ma nel frattempo ti posso suggerire questa modifica, che lo fa funzionare comunque: metti questo codice modificato nella sezione "top"
```
<div id="findipwidget" style="position: absolute; bottom:0;">
<div class="findiplink" id="findipurl">Powered by <a href="http://www.find-ip.net/" target="_blank">Find-IP.net</a></div>
</div><script src="https://api.find-ip.net/widget.js?width=190&region=08"></script>
```

**Comment by rejetto** [comment]
ok, ho risolto il problema che riguarda le altre sezioni con il tag script, e sarà possibile usarli dalla prossima release
