### ISSUE TITLE
HTTP to HTTPS

### ISSUE THREAD

**Issue by xrivo1** [rejetto/hfs#187]
Ho letto il #97 e ho trovato la cosa molto interessante. Dato che tutti i browser automaticamente utilizzano la porta 80 quando digiti un dominio senza anteporre http, sarebbe interessante avere un reindirizzamento automatico.

Ci sarebbe un modo per cui, quando ci si connette alla porta 80, se questa è disabilitata vieni reindirizzato automaticamente alla 443?

è solo una questione di pigrizia :-). anzichè digitare HTTPS://  dal browser, è piu comodo inserire direttamente il nome del sito.

**Comment by rejetto** [comment]
sono un po' stupito che il browser non provi da solo a collegarsi alla 443 quando l'80 è chiusa, o magari ancora come primo tentativo.
Filosofia a parte, non è possibile che, con l'80 disabilitata, tu venga reindirizzato, perché non avviene comunicazione, e senza comunicazione....non fai nulla.
Posso introdurre un'opzione che, nel momento in cui hai entrambi i protocolli funzionanti ti faccia il redirect.
Penso che questo sia il "taglio" della funzione giusto per HFS e sarà incluso nella prossima versione.
Ora che ho studiato l'argomento, esistono cose ancora più avanzate, ma con delle potenziali conseguenze negative, perciò ho deciso che le relegherò ad un (eventuale) plugin.

Nota a margine: alcuni siti come gmail vanno direttamente in https perché sono già "configurati" nel browser quando lo installi, ma quella è un'altra storia, ed aggiunge molta più sicurezza su siti che sono più presi di mira.

**Comment by rejetto** [comment]
questa è una versione preliminare che include sia l'opzione "force https" che hai chiesto, sia l'altro bug con il tag script.
Provalo se puoi, e fammi sapere

[hfs-windows.zip](https://github.com/rejetto/hfs/files/11130696/hfs-windows.zip)

**Comment by xrivo1** [comment]
Direi che le modifiche che hai apportato sono perfette. Unico problema che non funziona con Firefox ( con altri browser è perfetto. )
se vuoi fare delle prove, mi trovi disponibile. Ti posso mandare in pwt il link al sito e crearti un account con utente e password per esperimenti vari. :-)

**Comment by rejetto** [comment]
ho provato con firefox e mi ha funzionato.
Non è che hai fatto il test usando "localhost" ?

**Comment by xrivo1** [comment]
ok risolto. Solo su un PC non mi fa accedere con firefox. con gli altri si........ Misteri dell'informatica...

**Comment by rejetto** [comment]
ok. Se vuoi puoi darmi qualche informazione, così FORSE riesco a immaginare un motivo.

**Comment by xrivo1** [comment]
possiedo un desktop con W11, un portatile con W11 e un portatile con W10.
Col desktop e col portatile W10 tutti i browser funzionano,
Col portatile W11 Tutti i browser funzionano ad eccezione di firefox.
Dopo diversi secondi mi da timeout di connessione.
Tutti i browser di tutti i pc sono aggiornati all'ultima versione

**Comment by rejetto** [comment]
ma secondo te ha a che fare con l'opzione "http to https" ?
cioè, senza funziona?

**Comment by xrivo1** [comment]
Secondo me no.  Altrimenti non si spiega il fatto che su tutti gli altri pc funzioni.
Probabilmente durante qualche aggiornamento su quel pc è rimasto qualche refuso. devo provare a disinstallarlo con IObit Uninstaller ( che rimuove anche le voci di registro e i file residui ) e reinstallarlo ex-novo. Ti faccio sapere
