### ISSUE TITLE
Icon for file/folder indicating if the authorisation is needed to access it

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#190]

**Comment by rejetto** [comment]
like this?

[hfs-windows.zip](https://github.com/rejetto/hfs/files/11133353/hfs-windows.zip)

**Comment by SanokKule** [comment]
I'm thinking more along the lines of replacing file/folder icon or overlaying it with lock icon

**Comment by rejetto** [comment]
i don't like the idea of replacing and not seeing the difference between types anymore.
Overlaying is a bit dangerous. This is one possible rendering
<img width="159" alt="image" src="https://user-images.githubusercontent.com/1367199/229578884-bf3ab56b-97d0-46b3-9812-e5153d27873d.png">

**Comment by SanokKule** [comment]
Good point, maybe having a small icon in the bottom right of the file icon?

**Comment by rejetto** [comment]
you try, i can't get it to look good
<img width="103" alt="image" src="https://user-images.githubusercontent.com/1367199/229580215-1866d840-82d7-44dc-bd04-c24edafbf9b1.png">
