### ISSUE TITLE
requirement for language

### ISSUE THREAD

**Issue by gogi100** [rejetto/hfs#193]
your guide says:

"translated the hfs  requires:

- json file on language (my language is serbian)
- configuration in chrome: Your browser's Accept-Language header:sr;q=0.9,en-US,en;q=0.8

is it possible in the next version of the hfs to make the language in the application set based on the set json file. users are not adept at setting up chrome

**Comment by rejetto** [comment]
people DON'T need to configure chrome.
if you have a serbian computer, their chrome will automatically be in serbian.

**Comment by gogi100** [comment]
I had chrome, but it was not automatically set to Serbian. the computers are different

**Comment by rejetto** [comment]
you had chrome, but is your operating system in serbian?

**Comment by gogi100** [comment]
it depends on how windows is set. I can't set all windows

**Comment by rejetto** [comment]
this includes a new option in admin/lang
[0.43.0-beta3.zip](https://github.com/rejetto/hfs/files/11157299/hfs-windows.zip)

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1367199/230041942-66903745-dca7-4c17-baec-53e381b0fe1b.png">

**Comment by rejetto** [comment]
please let me know if everything is ok

**Comment by gogi100** [comment]
i send you updated serbian language json file. on my hfs this serbian
language works

**Comment by rejetto** [comment]
i got nothing.
maybe you attached the file to your email? if yes, then github doesn't let attachment pass through.
You can send an email to my personal address a@rejetto.com
