### ISSUE TITLE
Problems encountered in compiling under Windows

### ISSUE THREAD

**Issue by rainbowsource** [rejetto/hfs#198]
When I run "`npm run build-all`" it prompts (NodeJS 18.15.0):
```
'rm' is not recognized as an internal or external command, operable program or a batch file.
```

"rm" I don't think it should appear under Windows.

**Comment by rainbowsource** [comment]
I solved this problem using msys2...lol.

**Comment by rejetto** [comment]
i'm not currently curating the building system to run on different platforms.
i guess it works on mac (where i'm working) and linux.

**Comment by rainbowsource** [comment]
@rejetto Haha, the build process is no problem in MSYS2. EXE can be packaged directly with PKG.
`pkg -t win package.json`
