### ISSUE TITLE
Curiosità

### ISSUE THREAD

**Issue by xrivo1** [rejetto/hfs#200]
Ho notato nel file di log dei comandi ricevuti da IP sconosciuto. ( allego screenshot )
Sapresti dirmi a cosa corrispondono?
Grazie
![screenshot](https://user-images.githubusercontent.com/106228981/230305437-82111738-286f-4436-ad78-4727a390f71c.jpg)

**Comment by rejetto** [comment]
::1 è "localhost" in forma IPv6
equivalente di 127.0.0.1 in forma IPv4.
dico forma per semplificare.
quei comandi sei tu che usi l'admin-panel :)

**Comment by rejetto** [comment]
quasi quasi metto un'opzione per evitare di loggare l'attività localhost

**Comment by xrivo1** [comment]
Ok. no problem. semplicemente non capivo quel ::1 a cosa corrispondesse
