### ISSUE TITLE
Play h265 error

### ISSUE THREAD

**Issue by sinergycena** [rejetto/hfs#206]
Using video play plugin Im trying to play a mkv H265 but is not working, works with mp4, mkv h264, ¿what can i do to for work with h265?

`<HTML><HEAD></HEAD>
<BODY><TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>Vídeo</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>1</TD></TR>
<TR>
<TD><I>Formato :</I></TD>
<TD colSpan=3>HEVC</TD></TR>
<TR>
<TD><I>Formato/Info :</I></TD>
<TD colSpan=3>High Efficiency Video Coding</TD></TR>
<TR>
<TD><I>Formato del perfil :</I></TD>
<TD colSpan=3>Main@L5.1@Main</TD></TR>
<TR>
<TD><I>ID códec :</I></TD>
<TD colSpan=3>V_MPEGH/ISO/HEVC</TD></TR>
<TR>
<TD><I>Duración :</I></TD>
<TD colSpan=3>1 h 48 min</TD></TR>
<TR>
<TD><I>Tasa de bits :</I></TD>
<TD colSpan=3>9 057 kb/s</TD></TR>
<TR>
<TD><I>Ancho :</I></TD>
<TD colSpan=3>3 840 píxeles</TD></TR>
<TR>
<TD><I>Alto :</I></TD>
<TD colSpan=3>2 160 píxeles</TD></TR>
<TR>
<TD><I>Relación de aspecto :</I></TD>
<TD colSpan=3>16:9</TD></TR>
<TR>
<TD><I>Modo velocidad fotogramas :</I></TD>
<TD colSpan=3>Constante</TD></TR>
<TR>
<TD><I>Velocidad de fotogramas :</I></TD>
<TD colSpan=3>50,000 FPS</TD></TR>
<TR>
<TD><I>Espacio de color :</I></TD>
<TD colSpan=3>YUV</TD></TR>
<TR>
<TD><I>Submuestreo croma :</I></TD>
<TD colSpan=3>4:2:0</TD></TR>
<TR>
<TD><I>Profundidad bits :</I></TD>
<TD colSpan=3>8 bits</TD></TR>
<TR>
<TD><I>Bits/(píxel*fotograma) :</I></TD>
<TD colSpan=3>0.022</TD></TR>
<TR>
<TD><I>Tamaño de pista :</I></TD>
<TD colSpan=3>6,88 GiB (99%)</TD></TR>
<TR>
<TD><I>Default :</I></TD>
<TD colSpan=3>Sí</TD></TR>
<TR>
<TD><I>Forced :</I></TD>
<TD colSpan=3>No</TD></TR></TBODY></TABLE></BODY></HTML>`

**Comment by rejetto** [comment]
hi, you should write this to the plugin's page
is it this? https://github.com/IlyaBOT/video-player
the correct link is in your plugins' page, anyway

anyway, i suspect nothing can be done if the browser itself doesn't suppor the file.
In a sense, I suspect you should ask your browser's dev 😉

**Comment by SanokKule** [comment]
@sinergycena ~~if i'm not mistaken, h265 is only supported in Microsoft Edge.~~
Support for HEVC was added to browsers relatively recently.

**Comment by SanokKule** [comment]
More info for someone looking for an answer in this issue
https://github.com/IlyaBOT/video-player/issues/2#issuecomment-1501587870
