### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by xrivo1** [rejetto/hfs#207]
da circa 4 giorni, il programma rileva un proxy che in realtà non c'è.........

p.s. buona Pasqua
![Home](https://user-images.githubusercontent.com/106228981/230759533-eca904ef-0748-48fa-8c49-b2ee73c71f3f.jpg)

**Comment by rejetto** [comment]
una volta che ha ricevuto il "segnale"non si toglie fino a quando o lo fai tu (col bottone) oppure riavvii HFS.
Ti consiglio di iniziare con la seconda per vedere se si ripresenta.

**Comment by rejetto** [comment]
il segnale è un "comando" all'interno di una richiesta, che normalmente viene aggiunto dai proxy, ma nulla impedisce di aggiungerlo "malevolmente" per sfruttare qualche bug.
HFS di default ignora quel comando fino a quando non sei tu a dichiarare che c'è un proxy legittimo.
Non potendo distinguere tra legittimi e attacchi, intanto ti avvisa e poi sei tu a decidere.

**Comment by xrivo1** [comment]
Grazie. riavviato HFS messaggio scomparso. ora vediamo se prossimamente non si ripresenta.

**Comment by rejetto** [comment]
sto considerando di fare in modo che il messaggio scompaia automaticamente in 24h

**Comment by rejetto** [comment]
i just created a page to better explain what's going on, and i will link it in the warning itself
https://github.com/rejetto/hfs/wiki/Proxy-warning
