### ISSUE TITLE
About Translation

### ISSUE THREAD

**Issue by yx3016** [rejetto/hfs#218]
May I ask how to obtain the latest version of the hfs lang en. json file for updating the translated version.
Secondly, where can I upload the updated version file?

https://github.com/rejetto/hfs/wiki/Translation

![image](https://user-images.githubusercontent.com/81002806/232947649-c9da3d7e-ba9e-4bfc-a3eb-df2134a7a1cd.png)

![image](https://user-images.githubusercontent.com/81002806/232946831-d08fa4cd-33cb-47a9-ae7f-155de79e8407.png)

**Comment by SanokKule** [comment]
Try to go here https://github.com/rejetto/hfs/blob/main/src/langs/hfs-lang-en.json
and press the `Download raw file` button in the top right
![image](https://user-images.githubusercontent.com/24497821/232982216-fc906f55-2fb6-4f9c-b163-6bc06f5b633b.png)

**Comment by rejetto** [comment]
please, tell me if this link works for you https://github.com/rejetto/hfs/blob/main/src/langs/hfs-lang-en.json?raw=true

to give me your updated version you can attach your file here. Follow instructions at https://github.com/rejetto/hfs/wiki/Translation

**Comment by yx3016** [comment]
> 



> please, tell me if this link works for you https://github.com/rejetto/hfs/blob/main/src/langs/hfs-lang-en.json?raw=true
> 
> to give me your updated version you can attach your file here. Follow instructions at https://github.com/rejetto/hfs/wiki/Translation

this links  https://github.com/rejetto/hfs/blob/main/src/langs/hfs-lang-en.json?raw=true
cannot access

**Comment by rejetto** [comment]
ok thanks. Does the suggestion of SanokKule work at least?

> Try to go here https://github.com/rejetto/hfs/blob/main/src/langs/hfs-lang-en.json and press the `Download raw file` button in the top right ![image](https://user-images.githubusercontent.com/24497821/232982216-fc906f55-2fb6-4f9c-b163-6bc06f5b633b.png)

**Comment by yx3016** [comment]
> 

OK
