### ISSUE TITLE
impossibile visualizzare logo

### ISSUE THREAD

**Issue by xrivo1** [rejetto/hfs#224]
Ho provato, seguendo le istruzioni in wiki, a inserire un logo nella pagina di login.
La maschera si è ingrandita correttamente per fare spazio al logo, ma questo non appare.
Consigli???
Grazie
P.S. se come percorso metto il tuo URL compare correttamente il tuo logo, ma se metto il mio percorso locale ciò non accade,
Forse sbaglio la descrizione del percorso?
Devo inserire il percorco completo ( es. C:/desktop/ ...... ) oppure se la cartella è in HFS devo inserire solo il nome cartella seguito dal file?

**Comment by rejetto** [comment]
perchè il browser non legge percorsi locali.
Quello che carichi nel browser deve essere sul web, e quindi deve stare in HFS.
L'indirizzo che userai per raggiungere il file è quello che usi anche online, ma non serve scriverlo tutto, parti da DOPO il dominio.
Quello che ti sto dicendo non è una caratteristica di HFS, è così che si fa con HTML/CSS.

**Comment by xrivo1** [comment]
Perfetto. credo di aver scoperto il problema.
La cartella in cui è inserito il logo, è una sottocartella di root.
Anche se i criteri di questa sottocartella cartella sono " visibile a chiunque ", se non inserisco user e password il browser non mi può mostrare il logo in quanto la cartella di root è impostata su " login required " e quando inserisco user e password, la finestra di login ovviamente scompare e il logo non mi serve più.
Analizzando da chrome infatti, il percorso in cui dovrebbe comparire il logo mi indica " error 404 " unautorized
come potrei risolvere?
Grazie

**Comment by xrivo1** [comment]
Fermi tutti. Anche gli orologi !!!
Ho risolto.
Era solo un problema di configurazione della home...
Scusa.
