### ISSUE TITLE
PROBLEMI DI SICUREZZA

### ISSUE THREAD

**Issue by xrivo1** [rejetto/hfs#230]
Ciao. ho notato che, chi conosce il programma, puo' baypassare l'utente admin e accedere ai file di sistema.
Oggi, dal PC del lavoro mi sono collegato al server di casa e, digitando il mio indirizzo di dominio, seguito da /~/plugins/download-counter/main.js, ho visualizzato tale file.
e' normale questo oppure e' un baco?
Grazie

**Comment by SanokKule** [comment]
If i understand your issue correctly, that is a feature.
The plugins have public files that need to be accessible from the user for them to be able to run them.

**Comment by rejetto** [comment]
That's expected indeed, that and other files are public. I fail to see the problem with that. 
Who made the plugin (me 😹) knew the file was publicly accessible, therefore no sensible information is contained in it.
