### ISSUE TITLE
Language contribution to HFS

### ISSUE THREAD

**Issue by Microtel27200** [rejetto/hfs#234]
Hello, 
Here attached, is a small contribution to HFS3 with a language file translated into French.
I  tested it but surely could not inspect all occurrences. 
Please tell me if you find any problem by sending a message to microtel.vernon@wanadoo.fr
I also noticed that a few words are not translated (not exhaustive) :
"Clear"
"Password changed"
Best regards
Jacques - s
[hfs-lang-fr.zip](https://github.com/rejetto/hfs/files/11367548/hfs-lang-fr.zip)
ecretary of "Microtel Club de Vernon"

**Comment by asvt** [comment]
Merci :)
et ce n'est pas une réponse de normand !o)

**Comment by rejetto** [comment]
merci beaucoup :)
Couldn't answer earler as I was travelling.
I'm going to embed your translation in next version.
"Clear" in your file was not translated.
I'm taking the liberty of doing like this, if you have no better suggestion
>        "Clear": "Effacer",

while "Password changed" was actually a bug in HFS, and it will be fixed in next version.

**Comment by asvt** [comment]
There is another bug @rejetto : with the version for Windows, when I try to access a folder that does not exist, the message "Not found" appears, while it is well translated in the file provided by @Microtel27200

**Comment by Microtel27200** [comment]
Hello
Thanks for your answer.
My bad for having missed "Clear". "Effacer" is perfect.
@asvt The translation would be "Non trouv\u00e9" or "Dossier non trouv\u00e9" 
@+ and kind regards Jacques

**Comment by asvt** [comment]
> @asvt The translation would be "Non trouv\u00e9" or "Dossier non trouv\u00e9" 

Salut Jacques, je ne comprends pas pourquoi, mais lorsque je demandais une ressource inexistante, j'avais bien le message Not found alors que tu avais correctement traduit cet élément dans ton fichier. Je penche sur un bug, mais je ne sais pas si cela vient de HFS ou de mon navigateur (Edge la plupart du temps). Le problème est résolu grâce au super plug-in 404 (qui permet de renvoyer le visiteur sur une page personnalisée).
A+
Arnaud (Seino-marin)

**Comment by rejetto** [comment]
> There is another bug @rejetto : with the version for Windows, when I try to access a folder that does not exist, the message "Not found" appears, while it is well translated in the file provided by @Microtel27200

you are right, but it's not just about translation, this is revealing that we miss the whole handling of error pages.
I'll put it in my to-do list.

**Comment by rejetto** [comment]
it may be interesting for you to know that is not necessary to encode characters like é by \u00e9.
You can use the simple character, just be sure that the file is saved as utf-8 (quite standard nowadays).
You can see that with the italian translation I made.

**Comment by Microtel27200** [comment]
@Arnaud    Oui Massimo a dit qu'il allait rectifier cela dans la prochaine version.
@Massimo Thanks for the utf-8 tip, I forgot about that possibility. I will open a new issue to upload the utf-8 file I have already tested.
Best regards 
Jacques
