### ISSUE TITLE
HFS translation into French utf-8 format

### ISSUE THREAD

**Issue by Microtel27200** [rejetto/hfs#243]
Hello
You will find, here attached, the version 1.1 of  the translation file for French.
It now is in utf-8 format
Best regards
Jacques - Secretary of "Microtel Club de Vernon"
[hfs-lang-fr.zip](https://github.com/rejetto/hfs/files/11433476/hfs-lang-fr.zip)
[hfs-lang-fr.zip](https://github.com/rejetto/hfs/files/11433578/hfs-lang-fr.zip)

**Comment by rejetto** [comment]
thanks, included in next release
