### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by xrivo1** [rejetto/hfs#244]
Ciao.
Ho notato che durante il login, il nome utente NON è caps-sensitive.
Non che questo sia un grosso problema, ma credo che possa aumentare la sicurezza.
Già la password conta molto, ma avere un utente tipo " ReJeTtO ", potrebbe rendere i tentativi di accesso praticamente impossibili

**Comment by rejetto** [comment]
ciao, ne sono cosciente, è una mia scelta.
La sicurezza va (praticamente) sempre in direzione contraria all'usabilità.
Tanto per dire, nessuna delle cose che usi tu ha il grado di sicurezza che usano i militari, quindi i compromessi ci sono sempre, c'è solo da "scegliere" quali sono.

**Comment by xrivo1** [comment]
Sono d'accordo con te su tutta la linea. I nostri server non sono sicuramente sotto l'attenzione di gente di Anonymous che al massimo ci possono trovare qualche mia foto al mare in costume ( e ti assicuro che non è un bel vedere :-).
Quindi partendo dal presupposto che non si tratta di server istituzionali, ma casalinghi, inserire qualche piccolo accorgimento che faccia perdere tempo ad haker da 4 soldi sia comunque un piccolo passo in più verso la sicurezza.
Rispetto comunque la tua scelta. Il software è ottimo e questo è quello che conta.

**Comment by rejetto** [comment]
considera che questa mia scelta l'hanno fatta anche google e facebook. Poi decidi tu che valore dare a questo...

**Comment by xrivo1** [comment]
Ripeto. Nessun problema sulla scelta. Sicuramente é una valutazione corretta. Per Google e Facebook la scelta é sicuramente commerciale. fare una ricerca
Senza distinzione tra maiuscole e minuscole aumenta la quantità dei risultati.
Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rejetto** [comment]
mi spiego meglio: non parlavo di ricerche ma del login
