### ISSUE TITLE
Http cookie problem , when Https connexion is OK

### ISSUE THREAD

**Issue by asvt** [rejetto/hfs#245]
Hello,

With the same user account:

- when identifying with the secure url (https, letsencrypt), everything works normally. 
- if I use the insecure protocol (http), I get the error message like Cookie problem : no connexion

HFS version 0.44 & HFS version 0.45.alpha 4 (windows)

**Comment by rejetto** [comment]
the same browser won't allow the same website with http to handle the cookie created when you accessed first with https.
Try with incognito.
Normally there's no reason why a user should do that (go from https to http), but I guess you were testing.
