### ISSUE TITLE
Portuguese Translation.

### ISSUE THREAD

**Issue by OgamiWandermark** [rejetto/hfs#246]
[hfs-lang-pt.zip](https://github.com/rejetto/hfs/files/11471390/hfs-lang-pt.zip)
Here's a portuguese language to help contribute with the project.

**Comment by rejetto** [comment]
thank you very much!
I will include it in next release.
There were a few syntax errors, but I took care of them.
Find the corrected version here: [hfs-lang-pt.json.zip](https://github.com/rejetto/hfs/files/11478918/hfs-lang-pt.json.zip)
