### ISSUE TITLE
Add prev|next methods to Entry object

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#253]
Greetings! I started building an image/video/audio viewer app based on all the ones I've written so far. A very necessary feature is missing in the list of Entry files objects. Namely, the getPrev() and getNext() methods.

A vivid example in the code I write onEvent (after...., ({entry}) => '<button onclick="addImage(entry)">'). Of course, the whole point happens in the handler, but the logic of addressing "next" and "back" in the viewer requires access to the file identifier, you can, of course, climb the list through the selection, but you won't get write access to objects. Currently, this is solved by forming arrays of objects through the processing of each file, which is not good.

**Comment by rejetto** [comment]
"write access" ? you want to modify the entry object? tell me more.

I will see to provide an entry.next() method, or an HFS.getNextEntry(entry)

**Comment by 6elkir** [comment]
No getter only - norm.

Example: Fancybox . on ( 'next', (fancy) => {fancy.open ( currentEntry . getNext () . uri); } )

**Comment by rejetto** [comment]
you'll have it soon.
I already made it.

**Comment by rejetto** [comment]
find a preview in #257
