### ISSUE TITLE
Support external repos in plugin info

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#254]
It would be cool if it were possible to specify the name, repository (link) and author separately from the exports.repo properties autoparser, because for example, my repository is located on its own dedicated server and the autoparser is doing wild things there.

**Comment by rejetto** [comment]
Please provide specific example.
I'm ok with linking github, because I trust the platform, and I'm using their API.
Just linking "another" server sounds both unsafe and useless.

**Comment by 6elkir** [comment]
Example external repo: http://dvor-net.ptz.ru:55555/dvor-net/weblog-parser

imho need:
exports.author = 'Belkir';
exports.name = 'simple-media-viwer';
exports.title = 'Simple media Viewer by belkir';

**Comment by rejetto** [comment]
What do you hope to achieve with this? updates?
HFS uses github-style URIs to 
1) read plugin.js 
2) download the zip
but gitlab has different uris. I see 2 possibilities:
- you set redirections on your server so to make github-style URIs work
- i define at least 2 new URL-properties in plugin.js for the actions cited above, but the number may increase in the future if more interactions with the server are required. Hoping that "urls" are enough.
Opinions?

**Comment by 6elkir** [comment]
Would like the following:
1) The name was added regardless of the link to its repository (it could be specially noted)
2) An example could be specified on a third-party repository outside github.com (for example, I have my own server with gitlab on board)

**Comment by rejetto** [comment]
what I'm asking you is: what does the final user get?
tell me the story for the user point of view.

**Comment by rejetto** [comment]
at the moment the "repo" field gives the user
1. a link to the repo, so he can read more about it
2. check for updates in the GUI
3. updates can be downloaded by just clicking a button

this is the point of view of the user.

**Comment by 6elkir** [comment]
Well the end user receives sl. opportunity:
1) Normal app name like "File Thumbnails" instead of "someone-preview-files-ololol"
2) The ability to specify the author separately from the link to the repository The author can store the turnip in the repository command either someone else's or a worker
3) The ability to pull repositories from other domains in the program if the authors have their own servers

I think it's very convenient. At a minimum, you can parse the authors and app name from the composer.json file directly from the app repository project. If you do this, it will be enough to add only support for external repositories, and parse the rest directly from the project file.

**Comment by rejetto** [comment]
Introducing exports.author is a risk.
Plugins can also be malware, so when you install one from a publisher, you are trusting the publisher.
Translations don't have this problem of course, it's data only.
If you can enter any name as author, you can make people to think you are someone else. 
Same problem applies if you want to extract the name of the publisher by a custom server the way I'm doing with github. You could put any name.
So, this is for 1 and 2.

For 3: to pull/download a repository HFS needs a URL with the ZIP of the plugin repo. 
With github I know how to make the zip url using the "repo" property.
On gitlab the zip is possible but the URL is different.
At the moment this download is possible with the "search" and with "check updates".
Search: it is done on github, currently, and it's easy. How should HFS know other servers? Doesn't seem feasable.
Updates: update could be done if HFS knows the URL to the zip, but to understand if the only version HFS needs to read file "plugin.js" and this too is different URL than github, so you should provide at least a direct link to the zip and a direct link to plugin.js.
Single "repo" string is not enough.  "repo" could point to the webpage, but than you need also repo_zip and repo_main.
And with this you could get check updates + install updates.
No search, no author.
Is this worthy of being added? Would people really use it?

**Comment by 6elkir** [comment]
Maybe then consider such a url in composer.json? As far as I know, it should allow registration of custom fields. Links to zip and the plugin can be specified there, and on the hfs master server, you can send links to this very composer.json, which always lies at the root of the project, wherever it is. The senior server in this case can be connected to HTTP200 via two links and somewhere on its side can be banned.

**Comment by rejetto** [comment]
I don't know this composer.json, and I didn't understand what problem are you trying to solve with it.
Consider the problem is NOT adding new fields inside plugin.js. If they are worthy, I will add them.

**Comment by 6elkir** [comment]
ok, let's skip all the conveniences for the sake of simplicity. Let's just add the ability to host the app with an external repository. For example, my repository is currently here:
http://dvor-net.ptz.ru:55555/dvor-net
and the addition will Possibility of a path _like_ this:
http://dvor-net.ptz.ru:55555/dvor-net/hfs-media-viewer

I would like to somehow be able to find the author for example dvor-net
and application name

**Comment by rejetto** [comment]
what do you mean by "ability to host" ? it's to vague. Do you expect a simple link, or also to get updates within HFS' gui?

What do you mean by "find the author" ? Do you mean to display part of the URL as the author?

**Comment by 6elkir** [comment]
My repository is exactly the same git only hosted not on free discovery from git on its own dedicated server. The same functionality that is now simply necessary can be stored at external repo.

**Comment by rejetto** [comment]
this doesn't answer my questions

**Comment by 6elkir** [comment]
My English is still only a technical level sorry (Well, how can I understand now the program parses only the git url and the author and the plugin name of the position automatically comes from the repository url.
It turns out that parsing should also work on external repositories (the link was given above for an example)

**Comment by rejetto** [comment]
Don't worry, english is not my language either and I know it can be hard. 🙂
But I need 2 answers for my 2 questions at https://github.com/rejetto/hfs/issues/254#issuecomment-1586993174
The sentence "should also work on external repositories" is not answering the 2 questions.

**Comment by 6elkir** [comment]
> what do you mean by "ability to host" ? it's to vague. Do you expect a simple link, or also to get updates within HFS' gui?

I understand that somewhere on the master server you do not place application repositories, but we (clients) check the update on the master server, and it already at least issues a list of links to check for application updates. Accordingly, let's say I made my plugin and want to share it with the community, but my repository is hosted on my personal server with a domain branch from github, how can I be?

> What do you mean by "find the author" ? Do you mean to display part of the URL as the author?

As far as I could judge the title and the author, the client-side hfs parses links to links in plugin.js and it clearly has problems with links outside the github domain

**Comment by rejetto** [comment]
the "master server" you talk about is github.com .
When using "search online", HFS asks github to give a list of plugins. I can do it because github has a search feature. I didn't program the search, it's github's.
When using "check updates", for each installed plugin, HFS reads on github the file "plugin.js".
Does this make things clearer?

To provide "search online" features I need a server. I don't want to run such server myself, because I don't want the project to be affected in case one day I cannot pay the bill. That's why I'm using github, because it's more reliable than me.
Github won't include in search results external sources.
Github will ensure that the "author" is just one, and you cannot copy a name. You cannot publish a plugin as "rejetto", for example. I explained this at https://github.com/rejetto/hfs/issues/254#issuecomment-1585727830 . In the same comment I also suggested what could be done about it, but I didn't get any real feedback.

**Comment by 6elkir** [comment]
I read it again. Understood. ALREADY INSTALLED plugin check updates from link in plugin.js. Example: the user adds simply by downloading it as an archive and placing it in a hfs plugins folder, and the update of this HFS add-on adds the link by checking on a external repository. How is that an option?

**Comment by rejetto** [comment]
"adds the link" is not a problem.
For me "adds the link" means that in the GUI the link on the plugin name points to your server.
The rest is the problem. I was discussing the rest.

**Comment by rejetto** [comment]
from version 0.48
https://github.com/rejetto/hfs/blob/next/dev-plugins.md#things-a-plugin-can-export
<img width="824" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/131577c6-b636-4291-9d8e-22bded000be2">

**Comment by rejetto** [comment]
https://github.com/rejetto/hfs/releases/tag/v0.48.0-alpha1
