### ISSUE TITLE
Change directory event

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#256]
Need support for events in directory change. Example: I'm building a list of Entry to view on the afterEntryName event. When changing the directory, it would be good to reset it after the formation of a new one, but now there are no such events and the list of events is added to the already collected file. We need new afterChangeDirectory events and it must be before the events of files in this directory.

afterChangeDirectory:
- flash list (1)
afterEntryName
- add to list (n)

**Comment by rejetto** [comment]
do you need this list even with the new next/previous of 0.46 ?
if you really do, try HFS.state.list

**Comment by 6elkir** [comment]
It would be nice, as I understand it, this is a matter of a couple of lines of trigger events when updating a sheet

**Comment by rejetto** [comment]
what would be nice? HFS.state.list already exists 
https://github.com/rejetto/hfs/blob/main/dev-plugins.md#front-end-specific

**Comment by 6elkir** [comment]
But how to understand that the list is "updated right now" and you need to start updating the code?

**Comment by rejetto** [comment]
It could technically be done even now, but too tricky.
I could add an event, but there's a better method, much more powerful: I'll give you watchState.
```javascript
HFS.watchState('loading', newValue => {
  if (newValue) console.log('started loading')
  else console.log('finished loading')
})
```
and of course it will work with [all frontend states](https://github.com/rejetto/hfs/blob/main/frontend/src/state.ts) of HFS.

**Comment by 6elkir** [comment]
thanks, im try to use this in code)

**Comment by rejetto** [comment]
it will be available in next alpha/beta of 0.46

**Comment by 6elkir** [comment]
yes, in current HFS.watchState not a function)))

**Comment by rejetto** [comment]
to not keep you waiting, i'm giving this version that includes watchState
[hfs-windows.zip](https://github.com/rejetto/hfs/files/11582748/hfs-windows.zip)

**Comment by rejetto** [comment]
For the moment I consider this done.
If something is wrong you let me know.
