### ISSUE TITLE
Suggestion: Show Actual file size in the monitoring page

### ISSUE THREAD

**Issue by TsunayoshiSawada** [rejetto/hfs#273]
**Is your feature request related to a problem? Please describe.**
It would be a great idea to be able to see what is the size of a file that is being served to a user so we can monitor how big it is and how far it has been uploaded. 

**Describe the solution you'd like**
Add a column to display the file size

![image](https://github.com/rejetto/hfs/assets/34431649/cc9af0e8-c5d3-4c8b-8581-77c26ddee070)

**Comment by rejetto** [comment]
I'm going to use same visualization as for uploads. Green part is in case of resumed download.
<img width="398" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/89312beb-adef-4df8-86e2-200aa386405a">

**Comment by rejetto** [comment]
available in [0.46.0 alpha7](https://github.com/rejetto/hfs/discussions/257)

**Comment by TsunayoshiSawada** [comment]
That looks absolutely gorgeous and compact.
