### ISSUE TITLE
Please add only one Option for add Custom HTML/CSS

### ISSUE THREAD

**Issue by fahad15090** [rejetto/hfs#275]
Straight forward
i like new version of HFS > Great Home/office storage manager with new features
run that for few days , want to implement My-Drive Theme project to HFS 3
my suggestion is simply add only one option as custom html/css that apply on entire site 
for modify according to need
or
Select that file from storage

**Comment by rejetto** [comment]
you already have that
https://github.com/rejetto/hfs/wiki/Customization
