### ISSUE TITLE
HFS not running in Linux (Alpine)

### ISSUE THREAD

**Issue by MadScienzzz** [rejetto/hfs#276]
Spun up a VM in proxmox (Alpine Linux)
Downloaded latest version as zip (wget)
Unzipped
cd to HFS directory
confirmed HFS exe had execute permission
ran ./hfs
result:  -ash: ./hfs: not found

**Comment by BussyBakks** [comment]
if you use .exe file in linux, you should have **wine** package to run .exe file

**Comment by rejetto** [comment]
I don't know/use linux, I just do some testing on ubuntu, where it seems to work.
Maybe the binary is not compatible with Alpine. 
My suggestion is that you don't use the binary at all, with these simple instructions https://github.com/rejetto/hfs#other-systems

**Comment by asd0109** [comment]
is very very nice in 0.47.0-alpha3 , i can use hfs  on my ubuntu server 20.04.6 LTS .

**Comment by rejetto** [comment]
I just tried to run node:18-alpine
entered the shell with `docker run -p 8000:80 -it --rm node:18-alpine sh`
the run `npx -y hfs`
and it runs.
now I can just browse on my computer on address http://localhost:8000
so, apparently there's no problem with Alpine.
I'm closing until more information is provided.
