### ISSUE TITLE
Latest language file for French (0.46 beta)

### ISSUE THREAD

**Issue by Microtel27200** [rejetto/hfs#278]
Hello,
I noticed the language file has evolved since version 0.43 so here is the latest translation for French.
Best regards
Jacques - secretary of Microtel Club Vernon 

[hfs-lang-fr.zip](https://github.com/rejetto/hfs/files/11886257/hfs-lang-fr.zip)

PS : I might be wrong but [Downloads] in the file menu is not translated

**Comment by Microtel27200** [comment]
PS : I might be wrong but [Downloads] in the file menu is not translated

**Comment by rejetto** [comment]
hello and thanks for your contribution :)

<img width="256" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/840ffba3-ecb6-47b5-a6f3-b035bfa97a24">

you are are right, the "downloads" part is not translated. I missed it because it is part of a plugin. I will fix it.
