### ISSUE TITLE
Save button on the Options page need to be clicked twice.

### ISSUE THREAD

**Issue by GeorgeGeorgeGe** [rejetto/hfs#281]
**To Reproduce**

1: go to Options  >> toggle the status of "do not overwrite uploading" switch or any other switch
2. click once on  "Save" button.
 
**Describe the bug**
the new status of  "do not overwrite uploading" switch has not been saved. 
we need to click twice on the "Save" button to get the message "Changes Applied"

Please check.
Thanks.

**Comment by rejetto** [comment]
thanks for reporting.
fixed in 0.46.0
https://github.com/rejetto/hfs/releases/tag/v0.46.0
