### ISSUE TITLE
rename folder error

### ISSUE THREAD

**Issue by asd0109** [rejetto/hfs#286]
version 0.46.0

![2023-07-05 14 06 53](https://github.com/rejetto/hfs/assets/37428027/b09e0b47-1a50-49c6-8b1a-ecd45b0b92ec)

when you rename folder first time , it`s ok .

![2023-07-05 14 07 09](https://github.com/rejetto/hfs/assets/37428027/85995ea2-7091-4ec8-99df-f0ab02ca0fac)

when you rename this folder second time  will error .

![2023-07-05 14 07 43](https://github.com/rejetto/hfs/assets/37428027/0c516f40-7573-42bb-a891-65fae918efe2)

server type this.

thank you very much!

**Comment by rejetto** [comment]
thanks for reporting.
the error we see in your black console is saying nothing about the folder problem.
It's actually another problem, that I fill fix in next release.

When I tried to rename same folder twice, I had no problems.
There must be something else that caused the problem, maybe the name, but if I don't know it I cannot fix it.
Would you be able to record a video while the problem happens? It may be useful

**Comment by asd0109** [comment]
i send mp4 to your a@rejetto.conn  .

today i try make new folder and rename twice ,but is ok ...     maybe  my 360 folder special ?   i dont do any thing for it .

**Comment by rejetto** [comment]
can you still have the problem if you rename the 360 ? (or any other folder)
sadly 0.46.0 won't display the real error, but next version will.
so, if you can still get the error, i can give you another version

**Comment by rejetto** [comment]
thanks for your video, i saw it but could discover anything useful.
can you still have the problem if you rename the 360 ? (or any other folder)
sadly 0.46.0 won't display the real error, but next version will.
so, if you can still get the error, i can give you another version

**Comment by rejetto** [comment]
please update to 0.46.1 and see if you have a better error

**Comment by asd0109** [comment]
Sorry i can't test it today,the 360 on my office computer. i test it tomorrow , i will email you , thank you very much!



---- Replied Message ----
| From | Massimo ***@***.***> |
| Date | 07/09/2023 02:20 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [rejetto/hfs] rename folder error (Issue #286) |

please update to 0.46.1 and see if you have a better error

**Comment by asd0109** [comment]
The error still exists , i send new video to your mail .

**Comment by rejetto** [comment]
Thanks for your video. 
So your observation is that the error doesn't happen if you wait a few seconds between renamings.
Please let me know what error is displayed in the HFS console.

For the moment, the only thing that comes to mind is that you have a software that monitors and scans those folders (or the whole drive). When you rename, it sees the change and scans again, and until it has finished there's a lock on the folder, so HFS fails at renaming. Can you think of such a software and try to stop it? It could be an antivirus for example. 
If I'm correct, maybe you will see now an EPERM error in the console.

**Comment by asd0109** [comment]
> Thanks for your video. So your observation is that the error doesn't happen if you wait a few seconds between renamings. Please let me know what error is displayed in the HFS console.
> 
> For the moment, the only thing that comes to mind is that you have a software that monitors and scans those folders (or the whole drive). When you rename, it sees the change and scans again, and until it has finished there's a lock on the folder, so HFS fails at renaming. Can you think of such a software and try to stop it? It could be an antivirus for example. If I'm correct, maybe you will see now an EPERM error in the console.



i try close virus software,but still.  now i try uninstall virus tools and try again .

**Comment by rejetto** [comment]
i don't advice to uninstall antivirus, just disable it temporarily.
It could be another software then.

**Comment by rejetto** [comment]
I tried to quickly rename a non-empty folder named 360, as you asked, but couldn't reproduce the problem

https://github.com/rejetto/hfs/assets/1367199/e7168fd8-0134-4755-8175-6a1d1393cb4a

**Comment by rejetto** [comment]
please, reproduce the error and then press F12 on your Chrome, you should see a better error in the browser console, like this
<img width="466" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/689199db-f264-4ebc-9e27-cd6a7d803e5f">

to see the blue lines you first have to enable by clicking "default levels" and then "verbose"

**Comment by asd0109** [comment]
i try all on my home computer , i can`t reproduce this error . it`s work very nice !
you are right maybe some another software using the 360 folder ,i try find it but failed .

thank you make this awesome program , and thanks for you patience

**Comment by asd0109** [comment]
i found the program lock folder today !

![2023-07-11 08 37 19](https://github.com/rejetto/hfs/assets/37428027/3ee1f2dd-82bf-434a-8b87-386104219792)

i delete it , it`s ok !

**Comment by rejetto** [comment]
hey, I'm happy that you've found the program in the end 🙂
and thanks for sharing, so other people may find this useful.

Can you tell me what kind of software is it? Is it an antivirus? I tried to search for it but didn't find a real description of the software.

**Comment by asd0109** [comment]
We have a shopping website called Taobao in China.

Wangwang is a tool used by Taobao users to chat.

After installing Wangwang, you will be quietly installed with Alibaba protect

And currently it cannot be simply uninstalled.

I never expected to encounter such a situation.
