### ISSUE TITLE
Error: Cannot find a specific module on macos Ventura 13.4.1

### ISSUE THREAD

**Issue by AlohaWorld** [rejetto/hfs#295]
**To Reproduce**
On macos (apple m2)
1. Download hfs-mac-arm.zip from assets (both [0.47.0-alpha2] or [0.46.1])
2. unzip hfs-mac-arm.zip to ~/bin/hfs/
3. Open a terminal window
4. cd ~/bin/hfs
5. ./hfs  (or sudo ./hfs)

**Describe the bug**
after executing ./hfs (or sudo ./hfs), it shows the following error messages:

`$ sudo ./hfs
Password:
HFS ~ HTTP File Server - Copyright 2021-2023, Massimo Melina <a@rejetto.com>
License https://www.gnu.org/licenses/gpl-3.0.txt
started 2023-7-19 19:15:49
version 0.46.1
build 2023-07-08T18:00:25.802Z
pid 88521
cwd /Users/abc/.hfs
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module '/snapshot/hfs/dist/node_modules/fs-x-attributes/prebuilds/darwin-arm64.node'
Require stack:
- /snapshot/hfs/dist/node_modules/fs-x-attributes/index.js
- /snapshot/hfs/dist/src/util-files.js
- /snapshot/hfs/dist/src/misc.js
- /snapshot/hfs/dist/src/apiMiddleware.js
- /snapshot/hfs/dist/src/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/hfs/dist/node_modules/fs-x-attributes/index.js:5:32)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/hfs/dist/node_modules/fs-x-attributes/index.js',
    '/snapshot/hfs/dist/src/util-files.js',
    '/snapshot/hfs/dist/src/misc.js',
    '/snapshot/hfs/dist/src/apiMiddleware.js',
    '/snapshot/hfs/dist/src/index.js'
  ],
  pkg: true
}`

**Expected behavior**
The hfs starts to run in the terminal window and the admin panel is opened in browser

**Environment (please complete the following information):**
 - OS: macos Ventura 13.4.1
$ uname -mprsv
Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64 arm

- CPU: apple silicon M2 (ARM64)

 - HFS Version [0.47.0-alpha2] or [0.46.1]
 - Browser [safari]

**Additional context**

HFS 0.45.0 works fine in the same environment, while 0.46.1 and 0.47.0-alpha2 both show the error messages.

**Comment by rejetto** [comment]
thanks for reporting!
i will soon publish a fixing version

**Comment by rejetto** [comment]
just published alpha3.
please let me know if it works for you
