### ISSUE TITLE
Documentation to perform Upload from C#

### ISSUE THREAD

**Issue by SnowdenDev** [rejetto/hfs#296]
I have been reviewing the web but I was not successful in finding documentation to make a post request that allows uploading files to my hfs server, if someone present knew how to give me the way? please

**Comment by rejetto** [comment]
hey, just created this page https://github.com/rejetto/hfs/wiki/Upload.
Let me know if something is wrong or missing.

**Comment by SnowdenDev** [comment]
> Oye, acabo de crear esta página https://github.com/rejetto/hfs/wiki/Upload. Avísame si algo está mal o falta.

Thanks it works fine for me, you do a great job **bro**
