### ISSUE TITLE
v0.47.0-alpha3  can not select share in admin interface .

### ISSUE THREAD

**Issue by asd0109** [rejetto/hfs#298]
![2023-07-21 08 10 50](https://github.com/rejetto/hfs/assets/37428027/aa6a62ec-83e3-4387-b9e5-23f342b73ec6)

**Comment by asd0109** [comment]
![2023-07-21 08 19 37](https://github.com/rejetto/hfs/assets/37428027/8a6691c3-140d-4497-ad71-738bc7d29dba)


and linux version

**Comment by asd0109** [comment]
i send a secure problem to you email .

**Comment by rejetto** [comment]
this is quite an ugly bug, so I'm releasing a fix right away.
Click "check for updates" and get alpha4, please.
