### ISSUE TITLE
`localhost` issue of admin interface

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#30]
In 0.14.3, particularly after commit da616fe7ffa65ce6ec17b1f60ecd9fd5482ad87c found with `git bisect`,
in `function ctxAdminAccess` of `adminApis.ts`,
in some conditions `ctx.ip` of localhost addresses is `::ffff:127.0.0.1` rather than expected `127.0.0.1` or `::1`.

An obvious symptom is Firefox can't access the admin interface when starting "cleanly" (i.e. first run) -- it requires auth immediately because it's not being considered localhost (though at this point there's no account, making accounts.yaml manually is needed)
`curl` and `wget` is partially affected too, but it doesn't affect Chromium, in which `ctx.ip` is just `127.0.0.1`

All these is tested on my Linux and Android (Termux). On web search there are some relative cases (of other stuffs) on Windows

So at this time just add `::ffff:127.0.0.1` to `function isLocalHost` nearby 😃

**Comment by rejetto** [comment]
ok. I wonder if I should find a totally different approach for testing localhost, but for the moment this may be ok:
https://github.com/rejetto/hfs/commit/b0847be8e34188d4900338a04634407bf4693a60

**Comment by NaitLee** [comment]
Hey there's 2 colons as prefix: `::ffff:127.0.0.1`
but the fix have just one `:ffff:127.0.0.1`
thus didn't work 😶
I hear 2 colons in ipv6 means to omit the zeros. So it's a totally different meaning
Anyway fix with one character is still a fix 🙃

**Comment by rejetto** [comment]
I'm sorry.
I overwrote the previous fix with a new one
https://github.com/rejetto/hfs/commit/cedd1b67d9b89c78be5c83212156be9b2e150615
