### ISSUE TITLE
Why does Name in folder menu show urlencode name?

### ISSUE THREAD

**Issue by netsesame** [rejetto/hfs#302]
![e9045e45eec382c65b13bf2f466abe9](https://github.com/rejetto/hfs/assets/3131317/d84e87dc-02d0-49ad-9b84-201db7bea83a)

**Comment by rejetto** [comment]
thanks for reporting!
this seems the same as #293 
you'll find it fixed in 0.47

**Comment by deamon2k** [comment]
and in admin - monitoring, logging...

**Comment by netsesame** [comment]
Thanks

**Comment by rejetto** [comment]
> and in admin - monitoring, logging...

this will be solved in next release

**Comment by rejetto** [comment]
> and in admin - monitoring, logging...

fixed in https://github.com/rejetto/hfs/releases/tag/v0.47.0-alpha6
