### ISSUE TITLE
Hide Folders

### ISSUE THREAD

**Issue by lxnunorodrigues** [rejetto/hfs#309]
Hi , i tested this HFS , i like now , but i have a question , how hide a folder ...

example i have a folder /share  if put my web link on port 80 , i would like dont see but if i put /share its see ....

another hfs older have this option to hide folders ...

**Comment by rejetto** [comment]
hey, you must configure your folder like this
<img width="375" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/eb179fa7-aab1-44ad-b8b0-2a1139224d75">
