### ISSUE TITLE
Failed API loginSrp1 when login in webpage

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#31]
Hi,
I would like to have a assistant with code"Failed API loginSrp1", it appear in login with non-admin privilege accounts. Thanks.

**Comment by dzw13579** [comment]
For more detail, I used github the latest release version:0.14.3

**Comment by dzw13579** [comment]
Errorlog:
::ffff:127.0.0.1 - - [29/Mar/2022:10:06:19 +0800] "POST /~/api/set_vfs HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:06:25 +0800] "POST /~/api/loginSrp2 HTTP/1.1" 401 29
::ffff:127.0.0.1 - - [29/Mar/2022:10:07:34 +0800] "POST /~/api/get_status HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:07:34 +0800] "POST /~/api/get_vfs HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:07:34 +0800] "POST /~/api/get_config HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:12:12 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:12:22 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:12:28 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:12:51 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:13:10 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:13:55 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:14:50 +0800] "POST /~/api/get_status HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:15:01 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:17:12 +0800] "POST /~/api/get_status HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:17:16 +0800] "GET / HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:17:21 +0800] "GET / HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:17:33 +0800] "GET / HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:19:11 +0800] "GET /UP/ HTTP/1.1" 401 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:19:33 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:24:42 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:25:00 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:10:50:52 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -
::ffff:127.0.0.1 - - [29/Mar/2022:11:14:17 +0800] "POST /~/api/loginSrp1 HTTP/1.1" 403 -

**Comment by rejetto** [comment]
I tried but cannot reproduce it . I need exact steps to reproduce the problem.

**Comment by dzw13579** [comment]
> I tried but cannot reproduce it . I need exact steps to reproduce the problem.

It's easy to reproduce(maybe consider 100%) in my computer... Here are my steps to make it happen again and again:
The environment:
OS: Windows 10 X64 ProWorkstation, version: 21H2
Browser: Google Chrome(99.0.4844.84)/Firefox(98.0.2)
before doing the following steps, I copied the binary file to a new folder(the path only have EN characters).
Steps:
1.run the binary file, wait the frontend webpage show in browser;
2.make a new account with "Permission to access Admin interface" privilege;
3.make a new account again without the privilege;
4.open a new browser tab, use 127.0.0.1 to login. Boom, it happen....
P.S.:Google Chrome & FireFox have same problem.

**Comment by dzw13579** [comment]
> > I tried but cannot reproduce it . I need exact steps to reproduce the problem.
> 
> It's easy to reproduce(maybe consider 100%) in my computer... Here are my steps to make it happen again and again: The environment: OS: Windows 10 X64 ProWorkstation, version: 21H2 Browser: Google Chrome(99.0.4844.84)/Firefox(98.0.2) before doing the following steps, I copied the binary file to a new folder(the path only have EN characters). Steps: 1.run the binary file, wait the frontend webpage show in browser; 2.make a new account with "Permission to access Admin interface" privilege; 3.make a new account again without the privilege; 4.open a new browser tab, use 127.0.0.1 to login. Boom, it happen.... P.S.:Google Chrome & FireFox have same problem.



Just have a new try, it can omit the step2, just step 1/3/4  to reproduce the failure. But, If I make step2 happen, the privilege account can login normally without any waring.

**Comment by rejetto** [comment]
ok, i reproduced the problem, thanks. I'll let you know.

**Comment by rejetto** [comment]
would you give a try?
https://github.com/rejetto/hfs/releases/tag/v0.14.4

**Comment by dzw13579** [comment]
> would you give a try? https://github.com/rejetto/hfs/releases/tag/v0.14.4

It worked perfectly!But, another failure is happen...
The non-privilege account have right to open admin webpage.
I will open a new issue to discuss later.
