### ISSUE TITLE
Minimize to Tray

### ISSUE THREAD

**Issue by dateno1** [rejetto/hfs#311]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I don't want always show HFS windows

**Describe alternatives you've considered**
Hide windows to tray icon like old delphi version

**Additional context**
Add command to hide windows and Add option (run with Minimized) on config

**Comment by rejetto** [comment]
HFS 3 is a "console" program, so it has no "tray" option.
In the future there will be a separate "window" program, that will actually launch hfs hiding its console, and will have tray option. If anyone wants to take care of this part of the project (as its well separated), please contact me.
So, it's hard to say when.
Your other option for the moment is to try to install HFS as a service. Services don't have a window.

At the moment I don't have [instructions](https://github.com/rejetto/hfs#service) on how to make hfs.exe as service, so I wrote instructions for the non-exe version. It would be cool if someone could improve on this.

**Comment by dateno1** [comment]
I can create service with nssm + exe version

nssm install "HFS exe service" "path\hfs.exe" parameter

OK I will waiting future version
