### ISSUE TITLE
mimetype for one extension to force downloading made all filetypes forced downloads

### ISSUE THREAD

**Issue by De-M-oN** [rejetto/hfs#315]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  - Check if your problem is caused by your proxy, try without it.

No

**To Reproduce**

1. Open Admin Panel
2. Go to Config/options
3. Add mimetype. ( I did add extension .m3u and mime I did application/octet-stream to force it a download instead of open
4. Now try to open a file which should not be affected by this, e.g. a html file, but instead it will now download instead open as well

**Describe the bug**
Seems to me a bug, because when I say .m3u extension should be download, why all of a sudden are all filetypes downloads now?
Even removing that mimetype, doesnt fix it. It stays now broken. So I'm even lost how to fix it now.
I was on version 0.37, tried to upgrade on 46.1, but that one doesnt even work for me. I tried
apt install nodejs
still doesnt run, a 203 exit code:

`sudo systemctl daemon-reload && sudo systemctl enable hfs && sudo systemctl start hfs && sudo systemctl status hfs
Created symlink /etc/systemd/system/multi-user.target.wants/hfs.service → /etc/systemd/system/hfs.service.
● hfs.service - HFS
     Loaded: loaded (/etc/systemd/system/hfs.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2023-08-04 19:17:22 UTC; 7ms a>
    Process: 812223 ExecStart=/usr/bin/npx -y hfs@latest (code=exited, status=203/EXEC)
   Main PID: 812223 (code=exited, status=203/EXEC)
        CPU: 591us
lines 1-6/6 (END)`

I tried then 0.43
That one did start again, but still the same bug.
I tried removing the config.yaml file and it STILL happens. I'm completely lost now. How can this be possible that its still broken after deleting the config?

**Expected behavior**
1. Only that one m3u filetype forced being a download and not all files
2. Removing that mime again makes everything back to default.

**Environment (please complete the following information):**
Ubuntu

**Comment by SanokKule** [comment]
Most browsers seem to remember mime type and just stick with even if it was changed on the server.
Instead of removing all mime types, add all the needed instead.

**Comment by rejetto** [comment]
thanks for reporting!
there are several problems here.
I'll let you know soon

**Comment by rejetto** [comment]
203 exit code is by systemd.
If it can't run as a service, I would try running it normally to see that it runs. npx hfs@latest
If you cannot run 0.46, I need to know what error is displayed. If you cannot see it as a service, run it normally. It's important that you can run the latest, otherwise how will I give you the next update...

The mime editor was malfunctioning. I made a new one for next release (that I will publish soon).

It's not clear how you configured your mime types. Please attach a screenshot, or the equivalent part of config.yaml.

The first mime row that match the files will win, so the "*" rule should be the last.

**Comment by rejetto** [comment]
https://github.com/rejetto/hfs/releases/tag/v0.47.0-beta7

in this release i fixed 2 bugs
- the mime editor was unusable
- changing order of entries was not considered as a change, and you were not asked to save

i also added a warning for the user, to have the "*" (if any) as last rule
<img width="428" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/fbc3c496-5e3c-448d-b4c1-46b5b37118ef">


That said, I tested the problem you said, but I wasn't able to reproduce it. This configuration is working correctly for me
<img width="287" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/afe36fc7-94dd-4aac-a4f4-d095d1c541a3">

This is my result with a jpeg and an m3u file
<img width="595" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/7085fb06-9a3b-4e0c-98de-f4dc1b18fcc1">
I don't know what's going wrong on your machine, but you should first be able to update, so let's work on that.

**Comment by De-M-oN** [comment]
sorry for the super late response

I wasnt aware I could run the new versions still the regular way. It did run with error, so I tried the instruction by you and had that running as service step.

This 0.47.1 version actually does run with a regular start now.

And the best thing is:
This version fixed the problem entirely!

html isnt a download anymore and .m3u is forced now to be a download.

Thank you so much for fixing this issue!

**Comment by rejetto** [comment]
cool!
Are you able to run it as a service now?

**Comment by De-M-oN** [comment]
I didnt try. I'm fine with it being a process
