### ISSUE TITLE
0.47  accounts page black

### ISSUE THREAD

**Issue by asd0109** [rejetto/hfs#316]
![2023-08-10 08 18 49](https://github.com/rejetto/hfs/assets/37428027/7a3e279d-0b6a-45c3-9c6f-4cacffc73097)

![2023-08-10 08 19 12](https://github.com/rejetto/hfs/assets/37428027/7c6d666d-78a2-4b16-9f77-2c6d7115d0ef)

**Comment by asd0109** [comment]
click accounts show black page   chrome and firefox all like this

**Comment by asd0109** [comment]
![2023-08-10 08 27 15](https://github.com/rejetto/hfs/assets/37428027/83ff5d59-0551-4a73-84d6-5f3909cbdaed)

alpha6   is ok

**Comment by FZ500** [comment]
same problem accounts page black

**Comment by rejetto** [comment]
ugh, sorry.
it happens when there is zero accounts.
i'm going to fix it now.
you can still workaround it by adding an account in the config.yaml as [described here](https://github.com/rejetto/hfs/blob/main/config.md#accounts)

thanks for reporting!

**Comment by rejetto** [comment]
fixed
check for updates: 0.47.1
