### ISSUE TITLE
npm no latest version 47?

### ISSUE THREAD

**Issue by jtssi** [rejetto/hfs#319]
**Describe the bug**

Hello, the latest version is not available via npm, is this normal? thank you.

**Comment by rejetto** [comment]
I'm sorry, I forgot. I'll do it as soon as I'm home.
Thanks for reporting

**Comment by rejetto** [comment]
What platform are you running it on?

**Comment by jtssi** [comment]
hello, i'm using windows 10 with the latest version of nodejs

**Comment by jtssi** [comment]
i can confirm 
https://i.ibb.co/GV0NCrB/2023-08-16-11-25-49.jpg

**Comment by rejetto** [comment]
solved
