### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#32]
Well, just a question... is localization support planned in the future?

**Comment by rejetto** [comment]
not planned yet, but not excluded either.
I guess frontend is what would benefit mostly of localization.

**Comment by NaitLee** [comment]
Hi, I just say that I have i18n in my plugin. See some details at [this comment](https://github.com/NaitLee/Tradit-TPL/issues/4#issuecomment-1164014185)

The i18n idea inside is totally applicable to HFS, because that idea is simple & universal. You can even write your own implementation in your own way, and maybe extend it.

btw my piece of that code is in public domain.

**Comment by rejetto** [comment]
cool, and I'm sure you had fun making it, but when I start my part I'd rather use a well known lib for this job, as I think translation is a wild world, there's so much I don't know about other languages. I don't want to mess with it.

**Comment by NaitLee** [comment]
In my mind it's the wild community know their culture best, not dev nor a lib.

I understand your choice, and I hope all these will make it easy for people ☺

**Comment by rejetto** [comment]
multilanguage was added in latest version
