### ISSUE TITLE
ChatGPT translation ENG -> GER

### ISSUE THREAD

**Issue by KLobrillenmann** [rejetto/hfs#326]
translated into German via ChatGPT after the following rules for the AI:

my next input will be taken from a language file of a computer program. I want you to translate it from English to German by the following rules:
1. translate only lines after this line: "translate": {".
2. in every line to be translated only analyse the part after a double dash aka ":".
3. in every line which contains "{" OR "}"  only translate the terms enclosed in "{}" AND starting with "# " AND keep all the other parts of a line unaltered.
4. in a line which NOT contains "{" or "}" only tranlate the part follwing after ": ".
5. keep the translation technical related but keep in mind a users readability and easy understanding.

This was the outcome, which looks very reasonable to me as a native speaker of German:
(the only thing changed afterwards is the authors name)

{
    "author": "Klobrillenmann",
    "version": "1.0",
    "hfs_version": "0.47.0",
    "translate": {
        "Select": "Auswählen",
        "n_files": "{n,plural,one{# Datei} other{# Dateien}}",
        "n_folders": "{n,plural,one{# Ordner} other{# Ordner}}",
        "filter_count": "{n,plural, one{# gefiltert} other{# gefiltert}}",
        "select_count": "{n,plural, one{# ausgewählt} other{# ausgewählt}}",
        "filter_placeholder": "Hier tippen, um die Liste zu filtern",
        "Select some files": "Einige Dateien auswählen",
        "zip_checkboxes": "Verwenden Sie Kontrollkästchen, um Dateien auszuwählen. Danach können Sie erneut zippen.",
        "zip_tooltip_selected": "Ausgewählte Elemente als einzelne ZIP-Datei herunterladen",
        "zip_tooltip_whole": "Die gesamte Liste (ungefiltert) als einzelne ZIP-Datei herunterladen. Wenn Sie einige Elemente auswählen, werden nur diese heruntergeladen.",
        "zip_confirm_search": "Alle Ergebnisse dieser Suche als ZIP-Archiv herunterladen?",
        "zip_confirm_folder": "GESAMTEN Ordner als ZIP-Archiv herunterladen?",
        "select_tooltip": "Die Auswahl gilt für \"Zip\" und \"Löschen\" (falls verfügbar), aber Sie können auch die Liste filtern.",
        "delete_hint": "Um zu löschen, klicken Sie zuerst auf Auswählen",
        "delete_confirm": "{n,plural, one{# Element löschen} other{# Elemente löschen}}?",
        "delete_completed": "Löschung: {n} abgeschlossen",
        "delete_failed": ", {n,plural, one{# fehlgeschlagen} other{# fehlgeschlagen}}",
        "delete_select": "Etwas zum Löschen auswählen",
        "Delete": "Löschen",
        "Options": "Optionen",
        "Search": "Suche",
        "Zip": "Zip",
        "search_msg": "In diesem Ordner und Unterordnern suchen",
        "Searching": "Suchen",
        "Searched": "Gesucht",
        "Clear search": "Suche löschen",
        "Interrupted": "Unterbrochen",
        "stopped_before": "vorzeitig gestoppt",
        "empty_list": "Leere Liste",
        "filter_none": "Kein Filter",

        "Admin-panel": "Admin-Panel",
        "Login": "Anmeldung",
        "Username": "Benutzername",
        "Password": "Passwort",
        "login_untrusted": "Anmeldung abgebrochen: Serveridentität kann nicht vertraut werden",
        "login_bad_credentials": "Ungültige Anmeldedaten",
        "login_bad_cookies": "Cookies funktionieren nicht - Anmeldung fehlgeschlagen",
        "User panel": "Benutzerpanel",
        "Change password": "Passwort ändern",
        "enter_pass": "Neues Passwort eingeben",
        "enter_pass2": "Geben Sie das neue Passwort erneut ein",
        "pass2_mismatch": "Das zweite eingegebene Passwort stimmt nicht mit dem ersten überein. Vorgang abgebrochen.",
        "password_changed": "Passwort geändert",
        "Logout": "Abmelden",
        "connection error": "Verbindungsfehler",
        "Full timestamp:": "Vollständiger Zeitstempel:",
        "Search was interrupted": "Die Suche wurde unterbrochen",
        "Stop list": "Stoppliste",

        "upload_starting": "Ihr Download sollte jetzt starten",
        "wrong_account": "Konto {u} hat keinen Zugriff, versuchen Sie ein anderes",
        "no_upload_here": "Keine Upload-Berechtigung für den aktuellen Ordner",
        "Create folder": "Ordner erstellen",
        "Pick files": "Dateien auswählen",
        "Pick folder": "Ordner auswählen",
        "send_files": "Senden von {n,plural,one{# Datei} other{# Dateien}}, {size}",
        "Clear": "Löschen",
        "failed_upload": "Konnte {name} nicht hochladen",
        "confirm_resume": "Upload fortsetzen?",
        "file too large": "Datei zu groß",
        "Enter folder name": "Ordnername eingeben",
        "Successfully created": "Erfolgreich erstellt",
        "enter_folder": "Ordner eingeben",
        "folder_exists": "Ordner mit gleichem Namen existiert bereits",

        "Sort by:": "Sortieren nach: {by}",
        "name": "Name",
        "extension": "Erweiterung",
        "size": "Größe",
        "time": "Zeit",
        "Invert order": "Reihenfolge umkehren",
        "Folders first": "Ordner zuerst",
        "Numeric names": "Numerische Namen",
        "theme:": "Thema:",
        "auto": "automatisch",
        "light": "hell",
        "dark": "dunkel",
        "parent folder": "Übergeordneter Ordner",
        "home": "Startseite",

        "Continue": "Fortsetzen",
        "Confirm": "Bestätigen",
        "Don't": "Nicht",
        "Warning": "Warnung",
        "Error": "Fehler",
        "Info": "Information",

        "Unauthorized": "Unbefugt",
        "Forbidden": "Verboten",
        "Not found": "Nicht gefunden",
        "Server error": "Serverfehler",

        "Upload": "Hochladen",
        "upload_concluded": "Hochladen abgeschlossen:",
        "upload_finished": "{n} abgeschlossen ({size})",
        "upload_errors": "{n} fehlgeschlagen",
        "upload_file_rejected": "Einige Dateien wurden nicht akzeptiert",

        "File menu": "Dateimenü",
        "Folder menu": "Ordnermenü",
        "Name": "Name",
        "file_open": "Öffnen",
        "Download": "Herunterladen",
        "Missing permission": "Berechtigung fehlt",
        "Reload": "Neu laden",
        "Get list": "Liste abrufen",
        "Skip existing files": "Vorhandene Dateien überspringen",
        "Size": "Größe",
        "Timestamp": "Zeitstempel",
        "Show": "Anzeigen",
        "Loading failed": "Laden fehlgeschlagen",
        "Rename": "Umbenennen",
        "Tiles mode:": "Kachelmodus:",
        "off": "aus",
        "Operation successful": "Vorgang erfolgreich",
        "Uploader": "Uploader",
        "Download counter": "Downloadzähler",
        "Switch zoom mode": "Zoommodus wechseln",
        "Full screen": "Vollbild",

        "File Show help": "Datei Hilfe anzeigen",
        "showHelpMain": "Sie können die Tastatur für einige Aktionen verwenden:",
        "showHelp_←/→": "←/→",
        "showHelp_↑/↓": "↑/↓",
        "showHelp_space": "Leertaste",
        "showHelp_←/→_body": "Zur vorherigen/nächsten Datei gehen",
        "showHelp_↑/↓_body": "Lange Bilder scrollen",
        "showHelp_space_body": "Auswählen",
        "showHelp_D_body": "Herunterladen",
        "showHelp_Z_body": "Zoommodi",
        "showHelp_F_body": "Vollbild"
    }
}

**Comment by rejetto** [comment]
thanks for your contribution!
There's a page where I suggest to use gpt to stub translations, and I'm not mentioning any of those rules because I'm my (one) experience it wasn't needed, and gpt acted correctly by itself.
I'll see to include your translation in next version.

**Comment by rejetto** [comment]
sorry, only after i replied noticed someone else had previously submitted another german translation https://github.com/rejetto/hfs/pull/324
