### ISSUE TITLE
On first download from ZIP CRC is bad and file not readable

### ISSUE THREAD

**Issue by albamef** [rejetto/hfs#338]
**Environment (please complete the following information):**
 - OS: Windows Server 2019
 - HFS Version 0.48.0 a2
 - Browser: any
 - 
![1111](https://github.com/rejetto/hfs/assets/74110396/6bb4a3b4-a87e-40da-a149-35dd6953d12e)

**Comment by SanokKule** [comment]
Can confirm with Windows 11.

**Comment by SanokKule** [comment]
From a brief look with a hex editor i notice some 4 byte chunks getting zeroed. Looks like just bad CRC and data is still good.

**Comment by rejetto** [comment]
thanks for reporting!
i've found the problem, and the fix will be published ASAP.

**Comment by rejetto** [comment]
i'll publish next alpha in a new hours.
in the meantime i published update for stable version.
https://github.com/rejetto/hfs/releases/tag/v0.47.4
