### ISSUE TITLE
non-privilege user can access the admin webpage

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#34]
As the title said, non-privilege user have the botton to access admin webpage in "option" tab.
version:0.14.4
![image](https://user-images.githubusercontent.com/59822418/160862181-4cc804e1-a87c-4e4d-9f8d-8ec7f0d6a7cc.png)
![image](https://user-images.githubusercontent.com/59822418/160861155-fdedee0d-0ac4-4a0f-9471-4ebc57de9e9a.png)
![image](https://user-images.githubusercontent.com/59822418/160861522-bc6ce55a-1ba1-4b6f-b390-91ad4150075d.png)

**Comment by rejetto** [comment]
that is strange, i tested that before, and now, and cannot reproduce your problem.
Can you show "guest" properties?

**Comment by rejetto** [comment]
wait, are you on localhost?

**Comment by dzw13579** [comment]
> wait, are you on localhost?

yeah, using 127.0.0.1 to test
this problem is gone when I access from adapter IP(mean 192.168.xx.xx) which belong to my computer.
For me, my computer is behind a firewall, so I can only access the Internet through NAT, not easy to access my machine from the Internet. In this situtaion, I built a reverse proxy server that using C/S method to get the HFS service from outside. So, when access to HFS, it alway using 127.0.0.1 to get the data.

**Comment by dzw13579** [comment]
> that is strange, i tested that before, and now, and cannot reproduce your problem. Can you show "guest" properties?

I don't really know what to show... hope it's help
![image](https://user-images.githubusercontent.com/59822418/160958945-d82c86b8-2f06-402e-9fd1-898163badb80.png)


P.S.:consider to have a live chat on Telegram? may be a group for all users, more efficiency^_^

**Comment by rejetto** [comment]
ok, that's not a bug, it's just a misunderstanding: **in localhost hfs always lets you in**.
It says so in the homepage when you are not logged in.
The message was not displayed when you were logged in, but next version will keep the message, so there's less confusion.

find me on telegram with this same nickname.
