### ISSUE TITLE
Can't login admin page with 0.48.0 alpha.3

### ISSUE THREAD

**Issue by dateno1** [rejetto/hfs#341]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  - Check if your problem is caused by your proxy, try without it.

**To Reproduce**
1. Exit hfs & Backup 0.48.0 a.2
2. Overwrite 0.48.0 a.3
3. Rerun it
4. Can download&upload files but Can't Login Admin Page

**Describe the bug**

**Expected behavior**
Can't login to admin

**Screenshots**
![0 48 0 a3](https://github.com/rejetto/hfs/assets/12645246/24f78b38-6378-4226-8081-6828b8917dba)
Get_vfs error is added

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - HFS Version : 0.48.0 Alpha.3
 - Browser : Firefox

**Additional context**

Also show txt file (by show-any plugin) is not work (White Blank)

Image files (jpg/png) is OK

It not worked on Alpha.2&3

**Comment by rejetto** [comment]
thanks for reporting!
yes, it is not working correctly in some cases.
it should still work if you use the "enter" key on your keyboad.

**Comment by rejetto** [comment]
i can't remember what i was doing yesterday, but whatever i try now, i succeed in login (except when i write wrong user or password).
can you double check?

**Comment by dateno1** [comment]
> i can't remember what i was doing yesterday, but whatever i try now, i succeed in login (except when i write wrong user or password). can you double check?

ID&Password is saved on browser (Not typed)

**Comment by rejetto** [comment]
that's one of the many modes that i tried, and it works for me.
Try creating a new account and see if it works, see if you find something more, because otherwise I don't know how to fix

https://github.com/rejetto/hfs/assets/1367199/9e773362-42a4-4b1c-a1c5-68a9f0050266

**Comment by rejetto** [comment]
for the show-any plugin, please next time open a separate issue.
I tried to reproduce also this other problem, but without success.
If your problem persists, and you have no idea of what other details you could provide, consider giving me access to your txt on your server so that I can see it myself.

https://github.com/rejetto/hfs/assets/1367199/c249ee0b-1c63-4d17-a130-a1f26347349d

**Comment by dateno1** [comment]
Login with 'Keyboard Enter' key is OK

But login with 'Screen Enter Button' is Not (Require Password)

Test with Alpha.4

Show text file will be create new issue

**Comment by rejetto** [comment]
can you provide a video? maybe I will understand what is different with your case, because here it works, also the button on screen

**Comment by dateno1** [comment]
https://github.com/rejetto/hfs/assets/12645246/6f168b55-49c9-48b5-a102-c49b6e5475bf
Click button on screen is not work

But Keyboard key is OK

**Comment by rejetto** [comment]
ok, i reproduced the problem and i'm working on it
