### ISSUE TITLE
list-uploader not working

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#348]
**Environment:**
 - OS: Windows 11 22H2
 - HFS Version: 0.47.0-alpha6 (didn't test earlier versions) - 0.48.0-alpha4
 - Browser: Edge 117, Firefox 117

**Additional context**
Not sure when exactly it stopped working.

**Comment by rejetto** [comment]
thanks a lot!
it stopped workin in 0.47, yes.
luckily the information was stored, but not read correctly.

**Comment by SanokKule** [comment]
Now in 0.48.0 it's not shown until the page is refreshed.

**Comment by rejetto** [comment]
damn.... this should fix it
[hfs-windows.zip](https://github.com/rejetto/hfs/files/12657259/hfs-windows.zip)

**Comment by SanokKule** [comment]
Indeed, now fixed
