### ISSUE TITLE
About file sorting and hidden file loading

### ISSUE THREAD

**Issue by koogg** [rejetto/hfs#36]
hi，Thanks for your work，
It's a great tool, and version 3 is a good one, but there are some things that would like to keep some of the settings of version 2. For example: the sorting of files can be the same as in version 2, and for hidden files in folders, you can choose whether to load them in.

**Comment by rejetto** [comment]
the "hidden files" fix is ready, but I'm not yet sure about having an option for the alternative sorting.
Let's see if other people is interested.
If other people wants the same should reply here.
Anyway, my problem is only with having it visible in the "options". If you want in the meantime I can make some other "invisible" way to activate it.
