### ISSUE TITLE
only listen 127.0.0.1

### ISSUE THREAD

**Issue by rejetto** [rejetto/hfs#360]
### Discussed in https://github.com/rejetto/hfs/discussions/358

<div type='discussions-op-text'>

<sup>Originally posted by **armgong** September 23, 2023</sup>
because our IT management rules, we need set hfs3 behind nginx (which it allowed), so only listen on 127.0.0.1 is enough for us.  
and  our IT department don't allow hfs3 listen on LAN IP (10.* or 192.*), only 127.0.0.1 allowed.
so the question is could hfs3 only listen 127.0.0.1?
 </div>

**Comment by armgong** [comment]
maybe add a paramter  --host 127.0.0.1 to commandline and config file ,just like --port 80, is a possible way?

**Comment by armgong** [comment]
maybe add a paramter  --host 127.0.0.1 to commandline and config file ,just like --port 80, is a possible way?

**Comment by rejetto** [comment]
please have a look at https://github.com/rejetto/hfs/releases/tag/v0.49.0-alpha1
let me know if it works as expected.

[configuration can be done in many ways](https://github.com/rejetto/hfs#configuration), and command line is one of these.
I decided the name is not "host" but "listen_interface" for the sake of clarity.

**Comment by armgong** [comment]
thanks a lot , it works like a charm
