### ISSUE TITLE
FR : ability to open media files directly in-browser

### ISSUE THREAD

**Issue by ferro4prez** [rejetto/hfs#364]
FR : ability to open media files directly in-browser

Issue : currently a download is triggered when clicking on files, rather than passing the result to the browser in-line.  In the case of sharing a music library (for example) I'd like to simply listen to an mp3 in the browser when I click, rather than explicitly downloading the file to my computer first.

Same with videos - any of the common media formats should attempt to play in the browser rather than downloading.

Thank you!

**Comment by rejetto** [comment]
hey, the thing you say it's already there, so you must be using an old version, or made some configuration that is preventing it.
when you click on an mp3 you have a menu, and it says (among other things): open, download, show.
what version are you using?

**Comment by redtrillix** [comment]
> FR : ability to open media files directly in-browser
> 
> Issue : currently a download is triggered when clicking on files, rather than passing the result to the browser in-line. In the case of sharing a music library (for example) I'd like to simply listen to an mp3 in the browser when I click, rather than explicitly downloading the file to my computer first.
> 
> Same with videos - any of the common media formats should attempt to play in the browser rather than downloading.
> 
> Thank you!

This is usually dependant on the Web Browser you are using and the MIME Types you have set under `admin-panel > options > mime type`.

A plugin such as https://github.com/rejetto/simple-player may also fix this.

These discussions may help too:
https://github.com/rejetto/hfs/issues/349
https://github.com/rejetto/hfs/issues/109
https://github.com/rejetto/hfs/discussions/73

**Comment by rejetto** [comment]
people can easily make mistakes setting mime types manually, and i don't think that's his problem.
i'm closing this as a week has passed and there's no problem confirmed.
