### ISSUE TITLE
Internet tab showing wrong IP

### ISSUE THREAD

**Issue by redtrillix** [rejetto/hfs#371]
### Discussed in https://github.com/rejetto/hfs/discussions/370

<div type='discussions-op-text'>

<sup>Originally posted by **redtrillix** October  4, 2023</sup>
As shown in screenshot 1, I have a public IP starting with `49.192.`, this is my public IP, but I proxy/route through Cloudflare which gives me a proxied IP as shown in screenshot 2 of `172.67.194.248`/`destronia.tk`, this is correct as that is the IP from cloudflare.

Is there a way to fix this and have it use my Cloudflare IP and not my public IP?
I have my proxies set to 2 under settings to fix IP monitoring, but it seems that isn't involved here.

![image](https://github.com/rejetto/hfs/assets/54786587/c17d071b-86b6-4724-9dca-655b6d3c0a27)
---
![image](https://github.com/rejetto/hfs/assets/54786587/9ad5c5c2-2064-4574-86a6-504391a9e1f0)

</div>

Running v0.49.0-alpha1

**Comment by rejetto** [comment]
it's important to understand that this tool is only to help people make their HFS work on the internet, but it's not necessary.
if your server works, you don't *need* this.

Of coure it's not good to have something saying it's *not* working, while *it is*. This should be fixed, if possible.
I never used cloudflare, and i don't exactly know how it works.
It could be useful for me to undertand, in order to think on possible solutions.
I will try to study cloudflare. In the meantime, can you tell me if you configured "proxies" in hfs ?

**Comment by redtrillix** [comment]
> I will try to study cloudflare. In the meantime, can you tell me if you configured "proxies" in hfs ?

Do you mean in regard to https://github.com/rejetto/hfs/wiki/Reverse-proxy?
No, The only Proxy related setting is what I've configured in the options page, But I can do research on how to use it.
![image](https://github.com/rejetto/hfs/assets/54786587/611a8428-4ed4-4f2f-82bf-484cbfa196a0)


With Cloudflare, I am using the DNS records to point my domain name to my public IP. 
Because it is "proxied" it doesn't use my IP of `49.192` as the IP but `172.67.194.248` which is Cloudflare's IP.

![image](https://github.com/rejetto/hfs/assets/54786587/8f488640-0d60-48ed-a8d8-b019dbba4e2c)

**Comment by rejetto** [comment]
the option in hfs is exactly what i meant.
why did you set 2 and not 1?

**Comment by redtrillix** [comment]
Having 1 doesn't show the correct IPs for logging and monitoring, with 2 fixing it, not sure why.

**Comment by rejetto** [comment]
well, if you don't have a rev-proxy in your network, then both (the 2) are cloudflare's, i guess

**Comment by rejetto** [comment]
so, you get this error while trying to generate the certificate, right?

**Comment by rejetto** [comment]
what if I do something like this
<img width="305" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/d3731be5-dd88-47b0-b229-7af909223aea">

with different message

**Comment by redtrillix** [comment]
Yeah that could work.

**Comment by rejetto** [comment]
here a preview: [hfs-windows.zip](https://github.com/rejetto/hfs/files/12823296/hfs-windows.zip)
(just replaced the zip, redownload if you already did it)

**Comment by rejetto** [comment]
are we good, or should we make more adjustements?

**Comment by rejetto** [comment]
i will assume this is done
