### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by ErtilMedia** [rejetto/hfs#372]
**BEFORE**

- Are you using a reverse-proxy, like nginx? - No
  - Check if your problem is caused by your proxy, try without it. - No

**To Reproduce**

**Describe the bug**

Good afternoon.
I can't start HFS. Stops at "loading plugin antibrute"
It does not load plugins. At the same time, it does not give out any error.

**Expected behavior**

He should start the server after downloading the plugins

**Screenshots**

![изображение](https://github.com/rejetto/hfs/assets/36193917/a4bbddae-4e2c-4e66-a963-8faab9766f64)

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - HFS Version 0.40.3
 - Browser firefox

**Additional context**
Please help me fix this problem.
I did everything according to the instructions, but it doesn't start. 
I tried to run the service as root - the result is the same.

Contact for communication alferov-vladimir1993@ya.ru

**Comment by rejetto** [comment]
The only error I see is that port 80 is unavailable.
Can you use another one?

**Comment by ErtilMedia** [comment]
> The only error I see is that port 80 is unavailable. Can you use another one?

Yes, I can - but I don't understand how to change it.
It does not respond to HFS commands.

The config.yaml file is empty.
Can you provide a sample file? Or just add the line manually
For example port 8080?

**Comment by rejetto** [comment]
i see that you are running it as a service.
i'm no expert, but i guess that in this case you cannot input in the console, you just see the output. It's a limit of the system, not HFS.
So, in this case, i'll first report what's in the README file
> if you can never access the console, even with the previous instructions, you can [edit config file add add your admin account](https://github.com/rejetto/hfs/blob/main/config.md#accounts)

so in your case, you can enter another shell of the same machine, access the folder that's displayed (that is `/root/.vfs`), and type this command `echo "port 1080"  >> config.yaml` 

i'm moving this discussion as it's not a bug.

**Comment by ErtilMedia** [comment]
I apologize for my stupidity.
Everything went smoothly. After I added the port to the config.yml file.
After that, everything started without any problems.
I have crooked hands and additionally a beginner in Linux)

I apologize again! Thank you for helping and guiding me in the right direction.

**Comment by rejetto** [comment]
don't worry, i took your case as an opportunity to improve the documentation.
And if you have suggestions about it, don't hesitate...
