### ISSUE TITLE
MIME not work with upper case extension

### ISSUE THREAD

**Issue by dateno1** [rejetto/hfs#375]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  - Check if your problem is caused by your proxy, try without it.

**To Reproduce**

**Describe the bug**
1. File extension is lower case work well
2. If i rename file to upper case&mime is not work (just downloaded)

**Expected behavior**
MIME is not work with Upper case filename

**Screenshots**
![Mime](https://github.com/rejetto/hfs/assets/12645246/4748dbff-c6b7-4d28-8f8d-9a59474d20e4)
It test with IRC Lounge client

1st time i try it with lower case extension
2st time i was rename file to upper case extension&retry

If i copy&paste URL to firefox's address bar lower case show image but upper case is file downloaded

**Environment (please complete the following information):**
 - OS: Windows 10 x64 (server&client)
 - HFS Version 0.48.2 (Lastest Stable)
 - Browser Firefox 118.0.2 (Lastest)

**Additional context**
Current Config
```
version: 0.48.2
accounts:
allowed_referer: "*.example.com"
open_browser_at_start: false
log_gui: true
dont_log_net: 127.0.0.1|::1|192.168.0.0/16|10.0.0.0/8
proxies: 1
force_lang: en
enable_plugins:
  - antibrute
  - antidos
  - max-downloads-ip
  - mini-player
  - video-player
  - show-any
plugins_config:
  max-downloads-ip:
    limit: 10
  show-any:
    extensions:
      - ext: txt
      - ext: pdf
      - ext: flac
      - ext: mp3
      - ext: png
      - ext: jpg
      - ext: jpeg
      - ext: m4a
      - ext: ogg
      - ext: wav
      - ext: mp4
      - ext: mov
      - ext: wmv
      - ext: mkv
      - ext: webp
  antidos:
    max: 2000
admin_net: 127.0.0.1|::1|192.168.0.0/16|10.0.0.0/8
localhost_admin: false
vfs:
                                -----------------Deleted before upload----------------
  source: root
base_url: https://hfs.example.com
favicon: Favicon.ico
mime:
  "*.aac": audio/mp4
  "*.ape": audio/monkey
  "*.flac": audio/FreeLossless
  "*.m4a": audio/mp4
  "*.mid|*.midi": audio/midi
  "*.mp2|*.mp3": audio/mpeg
  "*.ogg|*.oga": audio/ogg
  "*.wav": audio/wav
  "*.weba": audio/webm
  "*.wma": audio/x-ms-wma
  "*.avi": video/x-msvideo
  "*.flv": video/x-flv
  "*.mp4": video/mp4
  "*.mkv": video/x-matroska
  "*.mpg|*.mpeg": video/mpeg
  "*.ogv": video/ogg
  "*.webm": video/webm
  "*.wmv": video/x-ms-wmv
  "*.gif": image/gif
  "*.ico": image/x-icon
  "*.jpg|*.jpeg": image/jpeg
  "*.png": image/png
  "*.svg": image/svg+xml
  "*.tif|*.tiff": image/tiff
  "*.webp": image/webp
  "*.css": text/css
  "*.csv": text/csv
  "*.js": text/javascript
  "*.txt": text/plain
  "*.pdf": application/pdf
  "*": Auto
zip_calculate_size_for_seconds: 100
```
Thanks for fix login button

Now it work well with enter key&screen button

**Comment by rejetto** [comment]
thanks for reporting!
the fix is ready, i will see to publish soon and report here.

but let me tell you: you have the problem because somehow you changed "auto" to "Auto", and the system is not recognizing it that way.
You can solve your problem right now, without any new version, by deleting all of your mime configurations, and leaving only `"*": auto`, with lowercase.

The auto supports, i think, all of the extensions you configured manually. You had to enter them only because it was not working because of the capital "A" in auto.

**Comment by dateno1** [comment]
Thanks for help

change 'Auto' -> 'auto' All work well :D

Also MIME on firefox is fixed (chrome work with 'auto' and 'Auto' + no mime setting)

That is my misstake

but I think change hfs to work with 'auto'&'Auto'&'AUTO' is better (someone can do same misstake)

**Comment by rejetto** [comment]
> but I think change hfs to work with 'auto'&'Auto'&'AUTO' is better (someone can do same misstake)

yes
