### ISSUE TITLE
About Option stream

### ISSUE THREAD

**Issue by lxnunorodrigues** [rejetto/hfs#376]
Hi , If possible click any video to stream it , for example i have mkv and mp4 movies , with srt files , the best example is VLC , so its possible make plugion for that !

Regwards

**Comment by rejetto** [comment]
hey, hfs already plays video files when they are supported by the browser.
Sadly, the file extension is not enough, some mp4 and some mkv will use codec that are not supported (h265/hevc), and there's nothing i can do about it.
