### ISSUE TITLE
Ability to set a custom index page

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#377]
**Is your feature request related to a problem? Please describe.**
when theres a index.html in a folder and i go to that folder it doesnt open that html page instead showing the folder view

**Describe the solution you'd like**
option(s) to allow for this just like there is on hfs 2

**Describe alternatives you've considered**
none

**Additional context**
if i updated my site to hfs 3 it would break pretty much every ui and link i have because it doesnt load the index.html instead of file view

**Comment by rejetto** [comment]
it's an option you have to set on the folder, but the option is displayed only if the index.html is found in that folder.
It's called "Serve index.html".
Let me know if it's ok

**Comment by W-i-n-7** [comment]
> it's an option you have to set on the folder, but the option is displayed only if the index.html is found in that folder. It's called "Serve index.html". Let me know if it's ok

this is not ok for my usecase i have a discord bot that creates a folder with a index.html that redirects to x website its a url shortener and now id have to manually add the folder and check that box

**Comment by rejetto** [comment]
i'm not understanding what prevents you from using the option

**Comment by rejetto** [comment]
is it because it's in a subfolder, and so HFS is not displaying the option on the parent folder?

**Comment by W-i-n-7** [comment]
its because i cant set it on by default

**Comment by rejetto** [comment]
and the reason you can't is..... the one that i wrote in my other message?
> is it because it's in a subfolder, and so HFS is not displaying the option on the parent folder?

**Comment by W-i-n-7** [comment]
> and the reason you can't is..... the one that i wrote in my other message?
> 
> > is it because it's in a subfolder, and so HFS is not displaying the option on the parent folder?

well that could also do it but a option to have this on by default and then toggleable off on certain folders would be ideal

**Comment by rejetto** [comment]
the system can actually do what you say, but it's the UI not offering you the option.
Let's first see if you can get it working, first.
Just add an index.html file to the folder, so HFS will show you the option.
Enable the option, then you can remove the file.
So you will be able to see if it works immediately.

**Comment by W-i-n-7** [comment]
> the system can actually do what you say, but it's the UI not offering you the option. Let's first see if you can get it working, first. Just add an index.html file to the folder, so HFS will show you the option. Enable the option, then you can remove the file. So you will be able to see if it works immediately.

thats a hacky workaround it works but not for subfolders so wouldnt work for my purpose

**Comment by rejetto** [comment]
i'm testing and will let you know

**Comment by rejetto** [comment]
making that setting working also on subfolders required a bit of work, actually, but now I'm able to give you a preview version so you can tell me if it works for you. 
Do you run as exe or npx?
[hfs-windows.zip](https://github.com/rejetto/hfs/files/12912606/hfs-windows.zip)

**Comment by rejetto** [comment]
i forgot to mention that we could have solved in a non-hacky but still not-so-easy way using masks.
With masks you can make changes to dynamic parts of the file system.

**Comment by rejetto** [comment]
https://github.com/rejetto/hfs/releases/tag/v0.49.0-alpha4
