### ISSUE TITLE
Hfs 2 ui with hfs 3 features

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#378]
**Is your feature request related to a problem? Please describe.**
id like to be able to use the hfs 2 ui i like the new features but its not as space efficient

**Describe the solution you'd like**
just a toggle to use hfs 2 ui but have hfs 3 features

**Describe alternatives you've considered**
none

**Additional context**

**Comment by rejetto** [comment]
hfs 3 is web, and its UI works even on a phone.
The UI you say it's not, so it's excluded.

**Comment by W-i-n-7** [comment]
> hfs 3 is web, and its UI works even on a phone. The UI you say it's not, so it's excluded.

i think this is a misunderstanding i wanted the old userinterface on hfs3 as a option

**Comment by W-i-n-7** [comment]
not the admin panel the file view

**Comment by rejetto** [comment]
aaaah ok, but that would be a theme.
People can make themes, as plugins.
<img width="457" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/9ba008cb-b676-43cc-ade6-12bf2b3d87c3">
I know, not many have been done yet.
You mostly need to clone an existing theme and changing the css.
If someone is interested can make a theme plugin to get the old interface, but I'm not spend time on it, so much else to be done.

**Comment by W-i-n-7** [comment]
oh great!
