### ISSUE TITLE
cannot login with username:password@websiteip:port

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#379]
- Are you using a reverse-proxy, like nginx? 
- no
  - Check if your problem is caused by your proxy, try without it.
no

**To Reproduce**
create an account and protect a folder or file with it
log out and then on your url bar use username:password@websiteip:port/folder/file.txt
you can see that it will prompt you to login instead of being logged in like in hfs2

**Describe the bug**
because of the custom login ui instead of browser's own sure makes it work on devices that dont have a built in popup like that or cant display for whatever reason but id like to see this work so i can make direct links to protected files

**Expected behavior**
you would be logged in already and view the file
also option to use browser's login window or custom (perhaps a global and folder based options too)

**Screenshots**
na (not applicable)

**Environment (please complete the following information):**
 - OS: [e.g. Windows] Windows7 but is an issue on any
 - HFS Version [e.g. 0.40.0] 0.48.2
 - Browser [e.g. chrome, safari] firefox 115.3.1esr but is an issue on any

**Additional context**

**Comment by rejetto** [comment]
hfs 3 supports "basic authentication", that is the one used by the url-with-password.
I just tested it, look
<img width="777" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/d4166422-fb1b-441e-a214-7f6de3f3bbe6">

i don't know why it's not working with browsers.
are you sure it's still working in modern browsers? i mean, if you do that with hfs 2.3 now, it works?

**Comment by rejetto** [comment]
ok, i've foud what it was, it should be working now
https://github.com/rejetto/hfs/releases/tag/v0.49.0-alpha4
