### ISSUE TITLE
hfs for android (apk)

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#381]
**Is your feature request related to a problem? Please describe.** no
A clear and concise description of what the new feature is. 
it would be cool if you could host the server on android phone if you want
but maybe this is after release and first prioritize on getting all the old features from hfs v2

**Comment by rejetto** [comment]
so, you have an android device and you want a permanent server that runs on it?

**Comment by W-i-n-7** [comment]
> so, you have an android device and you want a permanent server that runs on it?

my friend wants to do that and if it isnt hard to make its a fun hobby project :)

**Comment by rejetto** [comment]
afaik, it can run on android, just not as apk, but using nodejs.
I remember somebody posted screenshots of it working, possibly 1 year ago.
If somebody wants to play with making an apk, go for it, but i'm not not going to consider it for the moment.
https://github.com/node-on-mobile/node-on-android

**Comment by W-i-n-7** [comment]
> afaik, it can run on android, just not as apk, but using nodejs. I remember somebody posted screenshots of it working, possibly 1 year ago. If somebody wants to play with making an apk, go for it, but i'm not not going to consider it for the moment. https://github.com/node-on-mobile/node-on-android

alright

**Comment by rejetto** [comment]
are you still using win7 ?

**Comment by W-i-n-7** [comment]
> are you still using win7 ?

yes
