### ISSUE TITLE
Uploaded files get prefix

### ISSUE THREAD

**Issue by made1990** [rejetto/hfs#382]
Hi folks,

using hfs 0.48.2 when i upload a file using the webbrowser, the file gets uploaded successfully, but gets a prefix in the file name
**hfs$upload**

So a file called text.txt now has the name: hfs$upload-test.txt

How can I prevent that?

Marcus

**Comment by rejetto** [comment]
that's because your upload is not completed yet.
When it is completed, the name becomes the original one.

**Comment by made1990** [comment]
Got it. My underlying filesystem marks every new file read-only. So i guess the file was set to read-only before hfs could rename the file. 
I now changed the behaviour of my filesystem and now the files are uploaded with the correct filename. 
Thx

**Comment by rejetto** [comment]
ok, so i consider it closed.

hfs renames the files because that's how it knows that it is incomplete, and can suggest upload resume.
also, it's good for the user to know that the file is incomplete.

**Comment by made1990** [comment]
Hi @rejetto , getting back to that old topic again :D 
I actually got some questions regarding this.
Is it possible to deactivate that behavior, meaning upload files without adding the prefix?
Do you know if HFS releases the file handle between upload finished and renaming the file to its original one, even for a couple of seconds?
Thx

**Comment by rejetto** [comment]
there's no option to disable that,
but using server_code (in admin/options) you may use the event uploadStart (documented in dev-plugins.md) to change tempName. This requires some programming skills, tho, but GPT may help.
I didn't design the "tempName" to the same of the final name, tho, and mostyle to just read it, so i can't say if that won't cause any problem.
If you try to set it to be equal to "fullPath", to try to avoid the prefix, you will mess with the features i mentioned in my previous message.
