### ISSUE TITLE
We need an old feature like add URL into the 'Share Files' section.

### ISSUE THREAD

**Issue by Suitear** [rejetto/hfs#389]
**Is your feature request related to a problem? Please describe.**
now it can only add files from local disks.

**Describe the solution you'd like**
we need the old feature back. like in the following screenshot.
![image](https://github.com/rejetto/hfs/assets/9960618/98e077f2-5263-4433-b2e9-6a32b4ba5c7c)

like old times, we can create a shortcut for web URL, something like that.

Thanks for your hardwork.

**Comment by rejetto** [comment]
please give a look at this and tell me if you like it
[hfs-windows.zip](https://github.com/rejetto/hfs/files/13230463/hfs-windows.zip)

**Comment by Suitear** [comment]
> please give a look at this and tell me if you like it [hfs-windows.zip](https://github.com/rejetto/hfs/files/13230463/hfs-windows.zip)

Thanks a lot. but it can't be launched on Win 11. Just crash after a black screen flash on click, no process running.

**Comment by rejetto** [comment]
yeah, i'm sorry, there's a problem that i couldn't see from my system.
this was tested on win11 [hfs-windows.zip](https://github.com/rejetto/hfs/files/13249156/hfs-windows.zip)

**Comment by Suitear** [comment]
Thanks a lot. It seems it can't save any change to URL. 
Whaterver URL I enter, the link seems to be the default Google link.

![ezgif-2-f4911891b3](https://github.com/rejetto/hfs/assets/9960618/b0c48df4-6856-405a-a649-9ea27b8d576f)

**Comment by rejetto** [comment]
i'm sorry, i'm doing this quickly and have not been able to do proper tests.
Hopefully this is the good shot: [hfs-windows.zip](https://github.com/rejetto/hfs/files/13250734/hfs-windows.zip)

**Comment by Suitear** [comment]
> i'm sorry, i'm doing this quickly and have not been able to do proper tests. Hopefully this is the good shot: [hfs-windows.zip](https://github.com/rejetto/hfs/files/13250734/hfs-windows.zip)

Works like a charm. Thanks a lot.

**Comment by Suitear** [comment]
also, can we set some folders with password only, not by letting user log in?
