### ISSUE TITLE
Can users use your API to list and upload files? thanks

### ISSUE THREAD

**Issue by JH6588** [rejetto/hfs#391]
We need to upload some files periodically in a script. Do you support API?  thanks

**Comment by rejetto** [comment]
the API is not documented yet, I will work on it, possibly on swagger
but for the upload part you can refer to https://github.com/rejetto/hfs/wiki/Upload

for the list you can make an http GET to the url
http://localhost/~/api/get_file_list?uri=%2F

the uri is the parameter controlling the folder, and is url-encoded. %2F is actually "/"
Encode using encodeURIComponent(path)

the response is a json object with "list" in it, that's an array of objects. Each entry has at least "n", that is the name.

**Comment by rejetto** [comment]
i started writing proper documentation
https://app.swaggerhub.com/apis-docs/rejetto/HFS/1.0.0

**Comment by rejetto** [comment]
just added this page
https://github.com/rejetto/hfs/wiki/APIs

**Comment by JH6588** [comment]
in my case .The directory is not public .It's only opened for specific  account.   the document didn't  handle account authentication.     It's ok  to send http request with cookies   follow the chrome network panel . .I wonder is there a good way do this .tks
