### ISSUE TITLE
CORS Missing Allow Origin

### ISSUE THREAD

**Issue by AsilMediaUzbek** [rejetto/hfs#395]
Hello there! I wanted to use it to distribute and display videos via HFS, but the browser doesn't display the video via PlayerJS. And when I checked the reason from the browser, I saw this error - "CORS Missing Allow Origin".

I used NGINX before, this problem was also present in NGINX. And fix the problem to the configuration file "add_header Access-Control-Allow-Origin *;" I solved it by adding a tag.

I would like you to add this feature in HFS as well.
![problem](https://github.com/rejetto/hfs/assets/40468520/0ebdec0a-1617-4a32-9f54-a20bbe02225c)

**Comment by SanokKule** [comment]
You can install [CORS](https://github.com/rejetto/cors) plugin for that.

**Comment by rejetto** [comment]
exactly,
admin > plugins > search > cors
let me know if you have any problem with that

**Comment by ahi267aa** [comment]
hi @rejetto ,
I want to install cors plugin, but I can't find plugins at admin-panel now
It just searching without appear any plugins, please help to take a check, thanks

**Comment by rejetto** [comment]
@ahi267aa for some reason your HFS is not reaching github, where plugins are.

you can try to access it with your browser https://github.com/rejetto/cors/tree/main/dist
if it works, then you can do a manual installation.
https://github.com/rejetto/hfs/wiki/Plugins
