### ISSUE TITLE
Reporting crash error logs

### ISSUE THREAD

**Issue by TsunayoshiSawada** [rejetto/hfs#40]
Sometimes HFS just ...stops working. 
[error.zip](https://github.com/rejetto/hfs/files/8637627/error.zip)
[error-2.zip](https://github.com/rejetto/hfs/files/8637629/error-2.zip)

**Comment by rejetto** [comment]
I need the debug.log file, mostly

**Comment by TsunayoshiSawada** [comment]
[Debug logs.zip](https://github.com/rejetto/hfs/files/8642481/Debug.logs.zip)
Added

**Comment by rejetto** [comment]
your debug.zip contains 2 legit debug.log, and 2 error.log
in the former i only see 1 type of error happening every few minutes. Is this the frequency of your problem? otherwise the log doesn't contain any useful info.

**Comment by TsunayoshiSawada** [comment]
The downtime happens rarely. 
But next time it happens I'll note the time and see if we can log it. 
Figured I'll report what I can find anyway

**Comment by rejetto** [comment]
still happening?

**Comment by TsunayoshiSawada** [comment]
Yep, our service just stops serving once a day or once a while.

The service keeps running but monitor reports that it's down, restarting it fixes it.

**Comment by rejetto** [comment]
Can you provide some info? Like ram and CPU usage, after many hours of
usage.
Or last log requests before it stops.

**Comment by rejetto** [comment]
this was caused by the memory leak just fixed
