### ISSUE TITLE
Any way for download protected file via wget utility

### ISSUE THREAD

**Issue by GerFern** [rejetto/hfs#400]
I couldn't find any way to download a protected file without having to log in through a web browser
Is there a possibility adding support for passing the login credentials (username and password) as parameters in the URL when downloading a protected file? For example: 
`wget www.example.com/filepath.zip?user=user1&password=secret`. 
Or maybe there is another alternative way to download protected files?

**Comment by SanokKule** [comment]
I believe this does what you want
`https://username:password@www.example.com/filepath.zip`

**Comment by rejetto** [comment]
that should solve your problem.
let us know if there's more.
