### ISSUE TITLE
right click on local file to 'add to HFS', it shows 'Server is down'.

### ISSUE THREAD

**Issue by Suitear** [rejetto/hfs#405]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  - Check if your problem is caused by your proxy, try without it.
  NO

**To Reproduce**
1. Have enabled the 'Integration' option.
![image](https://github.com/rejetto/hfs/assets/9960618/e66be5c0-4277-49ae-8e4d-e51f4323ceea)

2. Right click on local files, then the black shell window pops out, but also a tip 'Server is down.'
![image](https://github.com/rejetto/hfs/assets/9960618/a94b8ba2-a20d-4f5f-82e5-f3b6becffd29)

**Describe the bug**

**Expected behavior**
successfully add local files or folders to HFS.

**Screenshots**
Try to provide videos or else screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: Win 11
 - HFS Version [0.50.0-alpha3](https://github.com/rejetto/hfs/releases/tag/v0.50.0-alpha3)
 - Browser Chrome

**Additional context**

**Comment by rejetto** [comment]
i couldn't reproduce the problem, it worked fine on my Windows 11.
1. does it always do the same error, or only sometimes?
2. did it ever work?

anyway, this can actually happen if you change your http port AFTER the system integration.
It can also happen if you DON'T have http but only https (this latter case, i should be able to fix it for next release).

**Comment by SanokKule** [comment]
I think it's some url encoding BS.
`T:\file.txt` adds fine
`T:\файл.txt` will error out

**Comment by Suitear** [comment]
> I think it's some url encoding BS. `T:\file.txt` adds fine `T:\файл.txt` will error out

Sanok is correct. My win11 Gui is Chinese. so any file with non-English names can't be added into HFS through right-clicking.

And another suggestion, the file-adding option via local disk. Cant it be done via win 10 systematic choosing option with resumption of last DIR or somthing, rather than using HFS'S own GUI for chooing files?

**Comment by rejetto** [comment]
thank you for your report. The bug should be fixed now:
https://github.com/rejetto/hfs/releases/tag/v0.49.4

**Comment by rejetto** [comment]
> And another suggestion, the file-adding option via local disk. Cant it be done via win 10 systematic choosing option with resumption of last DIR or somthing, rather than using HFS'S own GUI for chooing files?

are you talking about this? 
<img width="169" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/1199d1b2-25af-44a9-98f3-e87bb935fefb">

windows system dialog cannot be used here, because when started in a browser it doesn't reveal the path of the file. It's a limitation of the browser.
I can do something about remembering last folder, anyway.

**Comment by rejetto** [comment]
https://github.com/rejetto/hfs/releases/tag/v0.50.0-beta4

this should remember last folder
