### ISSUE TITLE
对于没有图像界面的Linux系统启动报错

### ISSUE THREAD

**Issue by pxy99** [rejetto/hfs#41]
在本地用着挺不错的，然后到服务器上启动的时候就报错了。
```
network veth8b41470
- http://[fe80::a8f8:77ff:fe1b:ca1f]:8011
Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:8011/~/admin/' ]
}
loading plugin antibrute

**Comment by rejetto** [comment]
i think you were using 0.20.1 (or previous) under linux. Can you confirm?
There was a problem on "xdg-open" file, missing attribute. It should be fixed from 0.21.0 on.

**Comment by pxy99** [comment]
> 
The latest version I use（0.21.0）

**Comment by rejetto** [comment]
is the error present on 0.21.0 ?

**Comment by pxy99** [comment]
> 

yes

**Comment by rejetto** [comment]
what Linux are you using?

I tried on my WSL and it worked fine.

**Comment by pxy99** [comment]
> what Linux are you using?
> 
> I tried on my WSL and it worked fine.


Tencent cloud server  	
CentOS 7.6 64bit

**Comment by rejetto** [comment]
maybe you are missing "xdg-open".
Try installing it.
I'm not Linux expert, sorry.
Let me know.

**Comment by pxy99** [comment]
> maybe you are missing "xdg-open". Try installing it. I'm not Linux expert, sorry. Let me know.
After installing xdg-open, there is no error at startup. But after accessing ip/~/admin locally, the login page pops up, and resource 401<img width="703" alt="image" src="https://user-images.githubusercontent.com/55566632/168101868-9890e30f-3fe0-40bf-a8c8-3a193f57b573.png"![image](https://user-images.githubusercontent.com/55566632/168101963-d36c4c63-4589-4b71-8687-9b7c4cc3953c.png)

**Comment by rejetto** [comment]
i don't see the "resource 401" you are saying in your screenshot

![168101963-d36c4c63-4589-4b71-8687-9b7c4cc3953c](https://user-images.githubusercontent.com/1367199/168102565-71346d6f-a797-4ce8-9f1c-c611ba3ea5a2.png)

**Comment by rejetto** [comment]
I understand you are using a cloud server. Are you able to browse the server with localhost address?

**Comment by pxy99** [comment]
> i don't see the "resource 401" you are saying in your screenshot
> 
><img width="1498" alt="image" src="https://user-images.githubusercontent.com/55566632/168103254-678cdcec-f767-4f87-b377-4b51861d3464.png">

**Comment by rejetto** [comment]
ok, that 401 is normal, don't worry.
The problem is that you are not accessing HFS with localhost.
I guess this is a problem with cloud server, and HFS is not "ready" for this situation. I will find a solution for future versions.

For the moment you must create your account manually.
Create/edit `config.yaml` and enter this text:
```
accounts:
  admin:
    password: your-password
```

**Comment by pxy99** [comment]
> 我了解到您使用的是云服务器。您可以使用 localhost 地址浏览服务器吗？



> 好的，那个401是正常的，不用担心。 问题是您没有使用 localhost 访问 HFS。 我猜这是云服务器的问题，HFS 还没有“准备好”应对这种情况。我会为未来的版本找到解决方案。
> 
> 目前，您必须手动创建帐户。 创建/编辑`config.yaml`并输入此文本：
> 
> ```
> accounts:
>   admin:
>     password: your-password
> ```
If set like this, is userName called admin?and How to add administrative privileges to users

**Comment by rejetto** [comment]
aaaaaaaaah, sorry, i forgot the privileges
```
accounts:
  admin:
    admin: true
    password: your-password
```
the first admin is the username (use another if you want)
the second admin is the privileges

**Comment by pxy99** [comment]
> aaaaaaaaah, sorry, i forgot the privileges
> 
> ```
> accounts:
>   admin:
>     admin: true
>     password: your-password
> ```
> 
> the first admin is the username (use another if you want) the second admin is the privileges

Thank you very much, now it is running successfully

**Comment by rejetto** [comment]
Cool.
For now I will add instructions in the README.
In the future I will make this process easier for cloud servers.
