### ISSUE TITLE
Can't run the server on alpine

### ISSUE THREAD

**Issue by chicco-carone** [rejetto/hfs#438]
**To Reproduce**
1. Install the alpine linux image on docker and open a terminal in the container
2. Install these packages `apk add --no-cache  bash curl unzip wget jq libc6-compat libgcc libstdc++`
3. Download the latest stable relase 
4. Extract it and give permissions with chmod
5. Run and see the error

**Describe the bug**
As soon as i start the executable i run into a Segmentation fault (core dumped) error and it crashes
**Expected behavior**
The Http server with the ui would start

**Screenshots**
![Screenshot_20240109_130822](https://github.com/rejetto/hfs/assets/66080458/2c793cb0-1525-46e0-94fa-42055c07ad28)

**Environment (please complete the following information):**
 - OS: Alpine docker image (latest) on arch linux with docker rootless
 - HFS Version latest

**Comment by rejetto** [comment]
ciao Francesco,
i'm no linux user, and i have no idea of what needs alpine have.
the error message is not really informative.
Can you try installing node, and the launch hfs with "npx hfs" ?
i know that there are some images with alpine+node, but i don't have if that's actually helping.
FYI, ubuntu seems to work

**Comment by chicco-carone** [comment]
> ciao Francesco, i'm no linux user, and i have no idea of what needs alpine have. the error message is not really informative. Can you try installing node, and the launch hfs with "npx hfs" ? i know that there are some images with alpine+node, but i don't have if that's actually helping. FYI, ubuntu seems to work

thanks i managed to install and run it with npx (probably it installs some dependency that wasn't known). I was wanting to make a docker image since there isn't one and this was the only service that i don't run on docker. I would like to make a pr and add the instructions for docker to this repo but i really don't know what to write on readme files, if you would like to add it as one of the installation methods just tell me.
Thanks for the help

**Comment by rejetto** [comment]
maybe it's even better if you write on the wiki
https://github.com/rejetto/hfs/wiki/_new
