### ISSUE TITLE
Http Error: listen EACCES

### ISSUE THREAD

**Issue by KJH-x** [rejetto/hfs#44]
Hi, thanks a lot for your project. I'm really a beginner and I met this when I first start the program as the README said.
![截图_20220521004128](https://user-images.githubusercontent.com/53437291/169574420-d5172172-4720-410b-8116-8f6755a283fa.png)
It didn't open the browser as it should. I've tried with config.yaml and got the same reaction. Could you tell me how to fix it?

In the debug.log, it said:
2022-05-20T16:40:55.671Z: http Error: listen EACCES: permission denied 0.0.0.0:80
Environment: [Win][0.22.0]

**Comment by rejetto** [comment]
your operating system is preventing HFS from opening the port (80 by default).
You have 2 options
- telling your operating system to allow it, maybe it's the firewall or something else
- try another port like suggested, hoping a different number will help

**Comment by KJH-x** [comment]
Thanks, I started it in pwsh with para --port 8080 and fix the problem.
btw, I didn't find conflicting rules in firewall settings (it's not in the list before I successfully run it).

**Comment by rejetto** [comment]
ok, but ideally you should be able to run it on port 80.
it's not powershell the problem, as it is not blocking me.
I'm interested in knowing the real solution. I've found someone who solved his problem like this
https://stackoverflow.com/posts/70189351/revisions

**Comment by rejetto** [comment]
Also, if you think a different message would have you served better, feel free to suggest

**Comment by KJH-x** [comment]
Copy that. However, since I'm using a VPN and seeding on this machine, I would test these methods on the next restart to avoid potential problems.
