### ISSUE TITLE
HFS3建议及问题反馈

### ISSUE THREAD

**Issue by 491977678** [rejetto/hfs#443]
1.增加预览功能，例如：进入图片的文件夹后，右上角或标题栏 可以增加一个按钮   点击后 可以整体预览当前页面的所有“图片、视频、文档、压缩包等常见类型的文件”(可以在滚动的时候自动加载 而不影响使用速度)，目前的操作是  点击单个文件的时候会有预览功能，但 如果有很多文件的话   就很不方便。(有时候记不住文件名，但依稀记得文件内容)

2.经常性的 页面 无法返回，，只有点击  向上按钮才是正常的，，点击上一个路径名称时，页面变成空白，需要刷新才能恢复。

**Comment by 491977678** [comment]
3.  https        一旦开启，不知在哪里关闭

**Comment by rejetto** [comment]
Please don't collect many things in one message, open "new issue" for each one.

1.  if you want preview of pictures install the "thumbnails" plugin.
2. i'm not sure i understand, the translation is not clear. Try with a video, or screenshots.
3. admin-panel > options > https port > off

**Comment by rejetto** [comment]
closed because stale
