### ISSUE TITLE
Issue with zip functionality and large folders

### ISSUE THREAD

**Issue by orcutt989** [rejetto/hfs#45]
**Describe the bug**
When downloading a large folder (14GB) using  the `Download Zip` button, the download seems to complete sucessfully, but right when it looks like its about to finish it restarts the download. This happens from multiple PCs in multiple locales.  The download would continue to do this forever if you do not cancel it.

**To Reproduce**
1. Share folder with 14GB of files in it
2. Browse to file share page and click `Download zip` to get
3. Watch download restart before it finishes

**Expected behavior**
I would expect the download to complete and not restart.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.22.0

**Comment by rejetto** [comment]
I managed to reproduce the problem. The download fails, and Chrome decides to restart it (firefox fails without restarting).
I will let you know.

**Comment by orcutt989** [comment]
Awesome! I'm glad you were able to reproduce it. The software is awesome thanks so much.

**Comment by rejetto** [comment]
https://github.com/rejetto/hfs/releases/tag/v0.22.1

this release will hopefully fix your problem. LMK

**Comment by orcutt989** [comment]
Awesome thanks!

**Comment by rejetto** [comment]
can you confirm it is actually fixed?

**Comment by orcutt989** [comment]
Yep works perfectly!
