### ISSUE TITLE
Names of uploaded files have unwanted hfs$upload- prefix

### ISSUE THREAD

**Issue by accnetdev** [rejetto/hfs#457]
- OS: Win11 Microsoft Windows [version 10.0.22631.3007]
 - HFS Version 0.50.6
 - Browser Firefox 121.0.1

Hi, I have uploaded some Excel files this morning and noticed that my files have all a hfs$upload- prefix in their names.

hfs$upload-202310_helios.xlsx 5 743 23/01/2024 10:32 -a--
hfs$upload-202310_selene.xlsx 5 470 23/01/2024 10:32 -a--
hfs$upload2-202310_helios.xlsx 5 743 23/01/2024 10:38 -a--

**Comment by rejetto** [comment]
uploading files get that temporary name until the upload is finished.
As soon as it is finished HFS _tries_ to rename it to the correct name.
The rename can fail, and in your case it did.
I know your upload was finished because of the arrow-up icon.
I don't know the reason, but it is very possible that some other software, probably an antivirus, saw the new file and decided to read it, probably for checking, and that prevented the final rename to happen.
I don't think HFS can prevent things like this from happening.
What I can think of, is that hfs could maybe retry for a short time, maybe 1 minute, hoping the other program will finish its activity and release the file.
So, not technically a bug, since I believe it's caused by something else, but I can see if I can make it more resiliant.

**Comment by accnetdev** [comment]
OK, in my context the antivirus of servers and workstations is ESET Endpoint Antivirus et ESET Server Security. It may help...

**Comment by accnetdev** [comment]
HFS ~ HTTP File Server - Copyright 2021-2023, Massimo Melina <a@rejetto.com>
License https://www.gnu.org/licenses/gpl-3.0.txt
started 2024-1-23 10:30:41
version 0.50.6
build 2024-01-02T10:56:57.046Z
cwd C:\_\hfs-windows
node v18.5.0
platform win32
pid 13156
config config.yaml
HINT: type "help" for help
http serving on 172.50.1.12 : 80
serving on http://172.50.1.12
https serving on 172.50.1.12 : 443
serving on https://172.50.1.12
loading plugin antibrute
loading plugin list-uploader
loading plugin download-counter
Error: EPERM: operation not permitted, rename 'logs/access.log' -> 'logs/access.log-2024-01-17'
Error: EPERM: operation not permitted, rename 'logs/access-error.log' -> 'logs/access-error.log-2024-01-17'
couldn't rename temp to C:\_\_hfs_root_\export\202310_helios.xlsx Error: EPERM: operation not permitted, rename 'C:\_\_hfs_root_\export\hfs$upload-202310_helios.xlsx' -> 'C:\_\_hfs_root_\export\202310_helios.xlsx'
couldn't rename temp to C:\_\_hfs_root_\export\202310_selene.xlsx Error: EPERM: operation not permitted, rename 'C:\_\_hfs_root_\export\hfs$upload-202310_selene.xlsx' -> 'C:\_\_hfs_root_\export\202310_selene.xlsx'
couldn't rename temp to C:\_\_hfs_root_\export\20240123_david_Lig_sep_ss_lib_comment.xlsx Error: EPERM: operation not permitted, rename 'C:\_\_hfs_root_\export\hfs$upload-20240123_david_Lig_sep_ss_lib_comment.xlsx' -> 'C:\_\_hfs_root_\export\20240123_david_Lig_sep_ss_lib_comment.xlsx'
couldn't rename temp to C:\_\_hfs_root_\export\IMG40FF.gif Error: EPERM: operation not permitted, rename 'C:\_\_hfs_root_\export\hfs$upload-IMG40FF.gif' -> 'C:\_\_hfs_root_\export\IMG40FF.gif'
couldn't rename temp to C:\_\_hfs_root_\export\Lig_sep_ss_lib_comment.xml Error: EPERM: operation not permitted, rename 'C:\_\_hfs_root_\export\hfs$upload-Lig_sep_ss_lib_comment.xml' -> 'C:\_\_hfs_root_\export\Lig_sep_ss_lib_comment.xml'
couldn't rename temp to C:\_\_hfs_root_\export\202310_helios.xlsx Error: EPERM: operation not permitted, rename 'C:\_\_hfs_root_\export\hfs$upload2-202310_helios.xlsx' -> 'C:\_\_hfs_root_\export\202310_helios.xlsx'
couldn't rename temp to C:\_\_hfs_root_\export\20240123_david_Lig_sep_ss_lib_comment.xlsx Error: EPERM: operation not permitted, rename 'C:\_\_hfs_root_\export\hfs$upload-20240123_david_Lig_sep_ss_lib_comment.xlsx' -> 'C:\_\_hfs_root_\export\20240123_david_Lig_sep_ss_lib_comment.xlsx'

It could help you to understand?

**Comment by rejetto** [comment]
it may, thanks.
Do you have this problem at each upload?
It seems you got the same error also when hfs tried to rename the logs, for rotation.

**Comment by accnetdev** [comment]
Yes I have the problem with each upload.

Le mar. 23 janv. 2024, 12:53, Massimo Melina ***@***.***> a
écrit :

**Comment by rejetto** [comment]
well, in a way, that's better.
Can you try disabling temporarily the antivirus?
so we know if it's that

**Comment by accnetdev** [comment]
ESET antivirus disabled for 30 minutes at both sides (server and client): no change, still the prefix.

**Comment by rejetto** [comment]
will you send me your config to a@rejetto.com ?
admin-panel > options > edit config > copy

**Comment by accnetdev** [comment]
version: 0.50.6
force_lang: fr
accounts:
  admin:
    ignore_limits: true
    admin: true
vfs:
  children:
    - source: C:\_\_hfs_root_
      can_see:
        - admin
      can_read:
        - admin
      can_list:
        - admin
      can_upload:
        - admin
      can_delete:
        - admin
      can_archive:
        - admin
enable_plugins:
  - antibrute
  - download-counter
  - list-uploader
log_gui: true
title: HFS Mes fichiers 
base_url: https://xxx.xxx.x.xx
listen_interface: xxx.xxx.x.xx
force_base_url: true
cert: self.cert
private_key: self.key
https_port: 443

**Comment by rejetto** [comment]
thanks. Can you rename the uploaded files (not using HFS), or do you get an error?

**Comment by accnetdev** [comment]
Sorry for the time you spent on this!
I'm confused, it was a simple ntfs security issue.
Only my local sam user had modification rights on the folder _hfs_root_ and I was connected with an AD account which had no right of modification on the folder...

**Comment by rejetto** [comment]
ok, thanks for having shared your findings
