### ISSUE TITLE
(dev feature req) plugin & private/external files?

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#46]
I want that:

- In plugin config it's able to select an external file/directory, and return its path or content.
- Plugin can store "private" files somewhere, that are meant to be assets, cache, etc., **and** have a good way to manipulate them.

I think some security should be concerned, too. For 3rd-party plugins, it is possible to ruin an environment by allowing something like real file/dir path.

**Comment by rejetto** [comment]
- I will add a type 'real-path', as I plan to add also 'virtual-path' to select a point in the vfs some day. It should be fairly easy now that I have the FileField component.
- plugin has its own folder where it's supposed to to whatever it wants. All its files are private exception made for "public" folder. Your api for files is nodejs, but I guess you'll have to `api.require('fs')` to access it.

Security is a problem: at the moment limits of a plugin are the same of HFS itself. Your only option to limit a plugin now is to limit HFS. That's the reason I introduced a warning at download time.

**Comment by NaitLee** [comment]
I see it. I've made it to manipulate files.

But it comes up more request:

- "Notify" the plugin, in case config is updated by user?
- Consider to provide `setConfig`? (use case eg. "reflective" config)
- Should plugin access config of HFS? (port etc.)

**Comment by rejetto** [comment]
- sure, subscribeConfig is already in to-do
- let's discuss it. Tell me a story. :) [use case]
- yeah, i guess i should introduce an api for that

**Comment by NaitLee** [comment]
For example, in config there are a lot of switches.
But also a few "preset" buttons are provided, clicking on any toggles some of them.
Edit: I see no buttons yet. Maybe select, or whatever
To be flexible, a `setConfig` is good :)

Also, I remember HFS 2 template macro can `set ini`. Here I think I should make it optional, though.
(I know it's yaml, not ini anymore 🙂)

**Comment by rejetto** [comment]
new real_path type for plugins is documented
https://github.com/rejetto/hfs/commit/22dd09bb70c490d26e524846debe28a96b6e9e30#diff-6d5869829cb849efa8f315e496f4338f7ad68ad8306400bde770a4c09262e1e4

please, next time open different issues, one for each thing you want to ask/discuss. It's easier and less confusing.

**Comment by NaitLee** [comment]
Oh, I got it :)

I think there can be a bit more, like a file mask option for filtering files, and locate to plugin folder if default is empty.
And I see the file picker have problem when it's given a non-existent path.

**Comment by rejetto** [comment]
[defaultPath and fileMask, ready](https://github.com/rejetto/hfs/commit/f2044af8ab9d9ac2632beb23211d2369e9a94881#diff-6d5869829cb849efa8f315e496f4338f7ad68ad8306400bde770a4c09262e1e4)

**Comment by rejetto** [comment]
> For example, in config there are a lot of switches. But also a few "preset" buttons are provided, clicking on any toggles some of them. Edit: I see no buttons yet. Maybe select, or whatever To be flexible, a `setConfig` is good :)

Sorry, I'm not sure I get it. Could you be clearer?
For a start: are you talking about setting HFS' or plugin's config?

**Comment by NaitLee** [comment]
I mean plugin config :)

For a brief example:

![Screenshot_20220606_180556](https://user-images.githubusercontent.com/47078558/172140898-b007859c-e830-4607-a213-39203d6781b2.png)

By changing that preset, options below are also affected, via like `setConfig`
(but user can have custom choices after that)

**Comment by rejetto** [comment]
Ok, now I get it. Anyway, the setConfig I will offer you won't affect the form in real-time.
Do you think you already need something like the picture? Because in that case I think I can instead create a special type of field component.

Plugins' capabilities will expand in time. I want for example them to be able to new pages that will populate the main menu.

**Comment by rejetto** [comment]
i just pushed setConfig and getHfsConfig.
Now to close this multi-issue I just need the subscribeConfig 😀

**Comment by rejetto** [comment]
just pushed api.subscribeConfig

**Comment by rejetto** [comment]
should we close this issue now?

**Comment by NaitLee** [comment]
Yes :)

I have thought that in my case I should provide dedicated admin-like page for advanced configs,
while keep basic settings in HFS admin, make it simple.

I will of course try to follow HFS admin view "policy" etc., with auth api.

I have another case to use `setConfig`: scan for a `tpl` in plugin folder and use it, in case first run

Thanks!

**Comment by rejetto** [comment]
so, first run you scan for a tpl, and when you find it you automatically set it as current-tpl ?

**Comment by NaitLee** [comment]
Yes :)
See everything around [here](https://github.com/NaitLee/Tradit-TPL/blob/7c2224c581a14b7fe64473f705f4ef86ea50005e/tradit-handler.ts#L45)
