### ISSUE TITLE
Can SMB protocol shared folders be mapped to virtual directories?

### ISSUE THREAD

**Issue by harmydzh** [rejetto/hfs#460]
Is it possible to map an SMB protocol shared folder to a virtual directory? 
I hope to add this function so that files in another NAS device can be downloaded through HFS. 
It is indeed very convenient to use a browser to download files.

**Comment by rejetto** [comment]
hey, i'm not on Windows. Did you try?

**Comment by rockrider69** [comment]
Hey, if it can help, I believe I am doing that, although not strictly from a NAS.
In my case I have files on several HDDs plugged on a linux server, these HDDs are accessed via SMB on my Windows server, and from there served by HFS V3 via https. No problem at all.

**Comment by rejetto** [comment]
i don't think NAS is necessarily special, and probably what's on the "other side" of the network is not the important thing, here.
The variable I can think of is how the operating talks with HFS to give access to the SMB folders.
Since you say it is working for you on Windows, then i guess HFS on Windows can manage SMB.
THis may change with other OSs.
I can say it is working on Mac, because I tried.

**Comment by harmydzh** [comment]
Thank you, this is indeed feasible on Windows. I first tried to add a virtual directory using the web management page, and then I found that the network shared file could not be found. Now I added it directly in the config file, and it is indeed feasible.

**Comment by rejetto** [comment]
I'm glad you solved!
You could even not edit the config directly, but enter your path here
<img width="184" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/ab147e0e-587e-4088-b807-8aa4b69c9a3e">


I also noticed that if you type or paste an initial SMB address like this, then you can also browse for more
<img width="328" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/de390c41-c7ca-479a-a55b-da1abd7df52d">

but i see, the file/folder picker when you go at the root offers only drives and not SMB resources. I'll take a note and see if I can do something about it. THanks for letting me know.
