### ISSUE TITLE
Upload progressbar

### ISSUE THREAD

**Issue by hampta** [rejetto/hfs#471]
Using an HTML progress bar for greater visibility and customization of the theme.

**Comment by rejetto** [comment]
you mean here? (not the monitoring)

<img width="383" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/56061a80-63cb-4208-897b-80cfd6cc9b2b">

**Comment by hampta** [comment]
Yes, here

**Comment by rejetto** [comment]
ok.
And is css enough for the customization you are talking about?

**Comment by hampta** [comment]
The only thing missing is a progressbar, I would like to be able to do something like this
![Screenshot_20240202-104500.png](https://github.com/rejetto/hfs/assets/56561445/1e03a431-e214-4907-bea8-19ec22233b35)

**Comment by rejetto** [comment]
<img width="488" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/8acac0cc-3457-4219-a701-c3876468cb8e">

i'm not sure how far you can customize the standard < progress >.
If you need more you'll let me know.

**Comment by hampta** [comment]
Thank you very much, what I threw off is a regular progressbar tag

**Comment by hampta** [comment]
Thank you very much, what I threw off is a regular progressbar tag

**Comment by rejetto** [comment]
np, you'll have that in next release

**Comment by rejetto** [comment]
in case you'd care for a preview, you just right click on the "check for update", and then paste this link
https://github.com/rejetto/hfs/files/14152601/hfs-windows.zip

**Comment by hampta** [comment]
![image](https://github.com/rejetto/hfs/assets/56561445/74a3350c-c36b-431d-916f-98da7adf364e)
yea, it`s working. thanks!
