### ISSUE TITLE
pressing back while on a web page wont leave the website unless you refresh

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#472]
see attatchment

https://github.com/rejetto/hfs/assets/90262580/f346ed2b-e2f3-445b-a039-3d4c07b75d3e

**Comment by W-i-n-7** [comment]
i should have re recorder that

**Comment by rejetto** [comment]
[beta4.2](https://github.com/rejetto/hfs/files/14259038/hfs-windows.zip)

this should fix that

**Comment by W-i-n-7** [comment]
> [beta4.2](https://github.com/rejetto/hfs/files/14259038/hfs-windows.zip)
> 
> this should fix that

thank you! it works
