### ISSUE TITLE
Is it possible to adapt to more versions of Chromium?

### ISSUE THREAD

**Issue by de7ang** [rejetto/hfs#473]
Older versions of Chromium are unable to display the page, and some buttons cannot be clicked. Is it possible to adapt to more versions of Chromium?

**Comment by rejetto** [comment]
you should at least specify what version are you talking about

**Comment by de7ang** [comment]
Chromium  43.0.2357.65 and 63.0.3239.132：unable to display the page
Chromium 86.0.4240.198：some buttons cannot be clicked
By the way, can you restrict download speeds for different IP ranges?

**Comment by rejetto** [comment]
i need BigInt for login encryption, that was introduced in version 67.
Specifically, I'm using this lib https://github.com/midonet/tssrp6a
I didn't find a better one for SRP.

What buttons don't work with 86 ?

**Comment by de7ang** [comment]
> i need BigInt for login encryption, that was introduced in version 67. Specifically, I'm using this lib https://github.com/midonet/tssrp6a I didn't find a better one for SRP.
> 
> What buttons don't work with 86 ?

![2024-02-02_220112](https://github.com/rejetto/hfs/assets/108105714/8e4ef3a3-e8b4-46a5-9a60-55960fa7b287)

**Comment by rejetto** [comment]
i got chrome 69 for testing, and now things should be better.
this is a preview version [hfs-windows.zip](https://github.com/rejetto/hfs/files/14146252/hfs-windows.zip)
a feedback would be appreciated

**Comment by de7ang** [comment]
> i got chrome 69 for testing, and now things should be better. this is a preview version [hfs-windows.zip](https://github.com/rejetto/hfs/files/14146252/hfs-windows.zip) a feedback would be appreciated

The button can be clicked normally now, thank you. Thumbs up for your work, don't push yourself too hard, and take care of yourself.

**Comment by rejetto** [comment]
brilliant!
