### ISSUE TITLE
登陆ID或密码错误

### ISSUE THREAD

**Issue by fishwding** [rejetto/hfs#476]
**BEFORE**
版本：0.52.0
**Describe the bug**
1、登陆ID或密码错误，提示“证书错误”。登录窗口自动关闭
**Expected behavior**
2、错误提示信息“用户名或密码错误”
      登录窗口不自动关闭

**Screenshots**
Try to provide videos or else screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - HFS Version [e.g. 0.40.0]

**Additional context**

**Comment by rejetto** [comment]
i cannot reproduce the problem you say.
please provide a video or a screenshot.

**Comment by rejetto** [comment]
please reopen with more info
