### ISSUE TITLE
uploading slow with tons of files

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#485]
the uploading starts to get really slow when you are uploading files in the thousands
im uploading games to my site and they have alot of files and noticed the upload waits on 100% for more and more time the more files there are

**Comment by W-i-n-7** [comment]
its very slow with over 5000 files
and it affects on LAN too

**Comment by W-i-n-7** [comment]
opening multiple tabs slows down the other uploads

**Comment by rejetto** [comment]
i tried to reproduce this problem, but maybe my computer is too fast (m1 pro).
I even tried artificially slowing down with Chrome
<img width="168" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/69a7f720-979a-471f-abd0-05f5512c3e73">

still i could get over 200MB/s on a single large file, even with over 5k files in queue.
Can you still replicate the problem?
The easiest way to try is to "pick folder" and select a big one. You can do it multiple times, doesn't matter the files are duplicate.

I suspect the problem is not with the list in itself, but with its update on the screen. So, my idea is to not show all the items, but cut at 500.

**Comment by W-i-n-7** [comment]
my pc is very fast aswell could be even faster than yours am not sure (i5-13400f)
the issue is with uploading multiple small files it takes an age to get to the next file that completes instantly due to it being so small
so 90% of the time uploading is spent waiting for the next file to start uploading while theres multiple in queue

**Comment by W-i-n-7** [comment]
> i tried to reproduce this problem, but maybe my computer is too fast (m1 pro). I even tried artificially slowing down with Chrome <img alt="image" width="168" src="https://private-user-images.githubusercontent.com/1367199/316977233-69a7f720-979a-471f-abd0-05f5512c3e73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODUyNzYsIm5iZiI6MTcxMTQ4NDk3NiwicGF0aCI6Ii8xMzY3MTk5LzMxNjk3NzIzMy02OWE3ZjcyMC05NzlhLTQ3MWYtYWJkMC0wNWY1NTEyYzNlNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMjAyOTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzM2MzcyZmY2MjkzMWUxYWQxMGI3ZDUwZTM5YmNkZDNiNjg0MWZlMTZjMWEwYWZjNzc1ODJiYjY3Y2Q3OTNlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.niqh13LsvBN5BY-29f8RbcbGf5MLu8uUCJQgbdl3geM">
> 
> still i could get over 200MB/s on a single large file, even with over 5k files in queue. Can you still replicate the problem? The easiest way to try is to "pick folder" and select a big one. You can do it multiple times, doesn't matter the files are duplicate.
> 
> I suspect the problem is not with the list in itself, but with its update on the screen. So, my idea is to not show all the items, but cut at 500.

https://hdun.org/random/hfs_upload_issues.mp4

**Comment by rejetto** [comment]
ah yes, you got files that are exceptionally small, 10 bytes each.
There's no decent way at the moment to get good performances.
Of course you may zip them before uploading.
I think I can add an "unzip" command without much effort. It could be available if you have upload permission.
Anyway, I also devised an optimization that should improve things already.
Let's see how faster you can get
[0.52-beta6.2](https://github.com/rejetto/hfs/files/14765565/hfs-windows.zip)

**Comment by rejetto** [comment]
ok, i made a test myself.
we are passing from a performance index of 7 to 44 with the version above, but then i've managed to improve my technique and reach 75.
To my surprise, the main slowing factor was repainting of the list.

**Comment by W-i-n-7** [comment]
it repaints the whole list when 1 file dissapears?

**Comment by rejetto** [comment]
something like that

**Comment by W-i-n-7** [comment]
could there be expand/hide button if more than  500 files
if hiddenwould show progress bar for all files in 1

**Comment by rejetto** [comment]
that's roughly what i did
