### ISSUE TITLE
Blank site when open File Server in iOS 12.5.5

### ISSUE THREAD

**Issue by bily267** [rejetto/hfs#49]
Like title when Start HFS 0.22.1 File Server at 192.168.88.101 but when open it on my iPhone it still show blank site.

 - Device: iPhone 6
 - OS: iOS 12.5.5
 - Browser: Safari version 12, Chrome version 92

![IMG_2441](https://user-images.githubusercontent.com/24521744/171030941-ba11429a-b56a-4aea-900c-a38e335c951d.PNG)

**Comment by rejetto** [comment]
apparently support on chrome android arrived with version 102, so it may be that same version will work on ios
https://caniuse.com/bigint
