### ISSUE TITLE
frozen connections

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#491]
[https://hdun.org/random/hfsbug.mp4](https://hdun.org/random/hfsbug.mp4)
theres tons of these frozen connections that have been here for days

**Comment by W-i-n-7** [comment]
apoligies for the link the filesize was too big

**Comment by rejetto** [comment]
1. if you click "disconnect", do they go away?
2. how often does it happen? roughly
3. if you refresh the browser, do they go away?

**Comment by W-i-n-7** [comment]
yes they go away if i click it
i dont know how often it happens and why but they just appear

**Comment by rejetto** [comment]
so *maybe* they are real connections, not just leftovers after they disconnected.
i'm introducing a timeout for those that don't make a proper request within 30 seconds.
[52-beta4.4](https://github.com/rejetto/hfs/files/14392838/hfs-windows.zip)

**Comment by W-i-n-7** [comment]
@rejetto now im unable to access it at all

**Comment by W-i-n-7** [comment]
not even localhost responds
umm i restored hfs-old and even that doesnt work now

**Comment by rejetto** [comment]
that's weird, i jut tried this exact version, also over the internet (mobile network) and it works fine for me.
maybe your antivirus blocked it?

**Comment by W-i-n-7** [comment]
download-counter plugin causes it

**Comment by W-i-n-7** [comment]
> so _maybe_ they are real connections, not just leftovers after they disconnected. i'm introducing a timeout for those that don't make a proper request within 30 seconds. [52-beta4.4](https://github.com/rejetto/hfs/files/14392838/hfs-windows.zip)

the "real connections" include downloads frozen in time for days (not progressing at all) even the speed stays exactly the same

**Comment by rejetto** [comment]
ok but most of them were connections without data exchanged, weren't they.
and i don't see a speed for them.
the ones with some speed were you, using the admin-panel

**Comment by W-i-n-7** [comment]
yes they were but they were on for days without changing at all

**Comment by rejetto** [comment]
you are right, i will also disconnect any connection that doesn't exchange data for a minute
[52-beta4.5](https://github.com/rejetto/hfs/files/14393343/hfs-windows.zip)

**Comment by W-i-n-7** [comment]
thank you

**Comment by rejetto** [comment]
reopen this issue if you find the same situation again
