### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#495]
![image](https://github.com/rejetto/hfs/assets/90262580/64a26afa-6467-4110-9d41-2fedd4e2dc4a)

console says:
miss i18n: Close

**Comment by rejetto** [comment]
i can't reproduce it.
any direction?

**Comment by W-i-n-7** [comment]
i got password wrong multiple times and antobruteforce plugin started to
slow it down alot then i left the circle loading for a while

**Comment by rejetto** [comment]
did this happen just once or....?

**Comment by W-i-n-7** [comment]
1

la 24. helmik. 2024 klo 1.32 Massimo Melina ***@***.***>
kirjoitti:

**Comment by rejetto** [comment]
still i cannot reproduce it, can you?

**Comment by rejetto** [comment]
reopen if you get more info
