### ISSUE TITLE
spinning circle when saving

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#496]
i noticed when making custom html that theres no real feedback when pressing the save button and it makes me feel like my changes didnt save and then i end up clicking it 5 times to make sure it saved
the only indication that anything happent is a really fast flash of the button

**Comment by rejetto** [comment]
the indication that i'm using is a circle around the button when there are changes that need to be saved.
no circle = no need.
it's similar to the "save" button (blue, with text) elsewhere.
would it be better if i disabled it instead?

**Comment by W-i-n-7** [comment]
yes that would be good!

**Comment by rejetto** [comment]
ok, you'll see this in next release
