### ISSUE TITLE
uninteractable item in adminpanel

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#498]
![unnamed](https://github.com/rejetto/hfs/assets/90262580/5ec236cd-7ef4-4027-8c27-7ba5fc328f56)
i added C: to my admin folder in hfs and now i cant rename delete or modify it in anyway

**Comment by W-i-n-7** [comment]
you can manually fix this by editing the config in the options tab manually

**Comment by rejetto** [comment]
yeah, i introduced this problem lately while trying to fix something

**Comment by rejetto** [comment]
0.51.3 fixes this problem
next 0.52 will too
