### ISSUE TITLE
Plugin & License

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#50]
See around [here](https://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins) of GNU GPL FaQ.

From the view of license, a plugin **must** be (also) released under GPL 3, otherwise it's a violate.

My thought is, it's necessary to check the license of a plugin, from search result of GitHub.
(Maybe when installing, to avoid low performance of course)
(And maybe analyze from file `COPYING`)

Another matter is "exception" system of GPL 3, could be used to deal with necessary circumstances.
For example to allow plugins with non-copyleft license -- *but whatever, they should be free-as-in-freedom!*

**Comment by rejetto** [comment]
I'm honestly confused on how one could require another piece of software, published separately, to use a specific license, even if it's meant to be "plugged in", but I'm no lawyer.
Anyway, surely HFS is not obliged at restricting the plugins you can install.
We can consider helping people who cares about free software to stay free.
At the moment you can open the link to the page and read the name of the license.
Showing the name of the license on the table takes a bit of space. Idea: a column, hidden by default, that you can enable.

**Comment by NaitLee** [comment]
It's the concept of [Copyleft](https://www.gnu.org/licenses/licenses.html#WhatIsCopyleft).
And in this case HFS & plugins work together, so should be seen as a whole. (["establish intimate communication"](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins))
You can ask FSF via [Email](https://www.gnu.org/licenses/license-list.html#LicensingEmailAddress) about what to do 😉
My own opinion is (you) to make an "exception" with few words, in file `COPYING` etc that's suitable.

**Comment by rejetto** [comment]
I don't think this will become an actual problem. In case, I'll address it.
I don't mean to prevent anyone from doing plugins under any kind of license, as I personally see them as separate softwares.
