### ISSUE TITLE
text file editor

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#500]
a basic text file editor in browser prefferably could open any file such as .bat .cmd .log .conf .ini .cfg .py .html and others
this could also be a plugin

**Comment by rejetto** [comment]
i guess we'll have something like that, at least as a plugin.
in the meanwhile, did you consider the "reupload" plugin? it does the job.
you can edit basically anything.

**Comment by W-i-n-7** [comment]
i use firefox you said the plugin is chrome only

**Comment by damienzonly** [comment]
@W-i-n-7 i released a simple text editor plugin, give it a try, you can download it in the plugin page of the admin panel
https://github.com/damienzonly/hfs-simple-editor

**Comment by W-i-n-7** [comment]
@damienzonly 

this is really cool thanks :D
could you add a create text document button somewhere though?

**Comment by damienzonly** [comment]
sure it's a good idea, i'll keep you updated

**Comment by damienzonly** [comment]
@W-i-n-7 i released a new version (1.1), you can update it in the plugins > check updates page.
i added some screenshots to the [documentation](https://github.com/damienzonly/hfs-simple-editor) to show you how to create a new file in the current folder

NOTE: the button may not appear if the browser caches the old plugin UI. in that case it's enough to ctrl+shift+R (or cmd+shift+R on mac)

**Comment by W-i-n-7** [comment]
@damienzonly tysm

**Comment by W-i-n-7** [comment]
oh i just noticed its exactly issue 500
