### ISSUE TITLE
The favicon is not displaying

### ISSUE THREAD

**Issue by elllectrum** [rejetto/hfs#505]
The favicon is not displaying, how to fix this issue?
![image](https://github.com/rejetto/hfs/assets/64004342/3de43b79-1469-4288-8d5c-052fdcc0056a)

**Comment by rejetto** [comment]
i just made a test and it's working here.
Show me how you configured your favicon.

**Comment by elllectrum** [comment]
I made my favicon 16x16 and placed it in the folder with HFS.
![image](https://github.com/rejetto/hfs/assets/64004342/4d1c4f29-26fc-41d0-8b2b-65018925f8f9)

**Comment by rejetto** [comment]
your browser may not be loading it because of the cache.
try with incognito.

**Comment by elllectrum** [comment]
[favicon.zip](https://github.com/rejetto/hfs/files/14472416/favicon.zip)

**Comment by elllectrum** [comment]
Incognito mode didn't help either, just checked now.

**Comment by rejetto** [comment]
<img width="341" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/cd1f5294-a5ea-4397-8293-f620160e61f8">

it works here
<img width="121" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/5a3487ed-7b9d-40c9-9768-0913ee6a9d86">

i don't know what's different with you.
i can tell you that the browser doesn't retry loading the favicon unless i force it holding shift

**Comment by elllectrum** [comment]
Massimo, thank you so much, holding shift helped! I didn't even know that holding shift makes the browser refresh the favicon))

**Comment by rejetto** [comment]
but people are not supposed to learn tricks to make things work,
so i took this chance to make a mechanism that should solve your problem automatically.

shift is about the whole cache, not just favicon.
