### ISSUE TITLE
newer version needs yarn to be built

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#51]
Not a big deal for me, just update the docs, for other people :)

**Comment by rejetto** [comment]
what makes you say so?
i'm using npm only here

**Comment by NaitLee** [comment]
Oh man that made me nervous :(
But see [here](https://github.com/rejetto/hfs/blob/22dd09bb70c490d26e524846debe28a96b6e9e30/shared/package.json#L7)

**Comment by rejetto** [comment]
stupid of me, copying from the web without thinking.
I'll try to remove that senseless dependency.
Thanks for reporting!
This apparently does:
```
    "build": "tsc && sass src/:lib/"
```
