### ISSUE TITLE
0.52.0-beta5 Performance issues

### ISSUE THREAD

**Issue by de7ang** [rejetto/hfs#523]
After I discovered and resolved the issue with the buttons not being clickable (in 0.52.0-beta5 and the first preview version you provided me), there has been a significant decrease in performance. Compared to version 0.51.3, when accessing the web page for the first time, it takes a long time to load, sometimes even more than a minute with the spinning circle.

**Comment by de7ang** [comment]
Version 0.52.0-beta5 remains in this state for several tens of seconds, whereas version 0.51.3 takes less than a second.
![image](https://github.com/rejetto/hfs/assets/108105714/2f3351a5-51fa-4fc7-8ccc-3e9953095e8c)



The version you first provided me with to fix the button issue also experiences the same slow loading problem when opening the page.
![image](https://github.com/rejetto/hfs/assets/108105714/00eadf6c-ded1-4e06-a17b-55641d732146)
![image](https://github.com/rejetto/hfs/assets/108105714/20a67fee-e95f-4929-b0b1-61deedfa13c0)

**Comment by rejetto** [comment]
ok i think i've solved it
[0.52-beta5.8](https://github.com/rejetto/hfs/files/14635447/hfs-windows.zip)

**Comment by de7ang** [comment]
![image](https://github.com/rejetto/hfs/assets/108105714/b1b8b298-57de-461a-ba6a-0a79f0181c20)
The first time opening the page is still very slow. This is a Hyper-V virtual machine, but the speed in the official version is very fast.

**Comment by rejetto** [comment]
what if you refresh after it has loaded?

**Comment by de7ang** [comment]
After successful loading, refreshing would require reloading the same amount of time.

**Comment by rejetto** [comment]
can you give me a link to your HFS?
even privately if it's not public
a@rejetto.com

is it working for you on Windows 7 ? I thought it was not possible

**Comment by de7ang** [comment]
The server is set up on an internal network without internet access, so you can't access it. I temporarily set up servers for versions 0.52-beta5.8 and 0.51.3 on the host machine and tested them using a Win7 virtual machine. You can watch the recorded video, and there is a significant speed difference. However, when using a Win10 virtual machine, the speed is normal. Therefore, the issue should be due to Win7.
![image](https://github.com/rejetto/hfs/assets/108105714/ea373e9f-6db1-43c1-99ec-f3cb7aea3b20)

https://github.com/rejetto/hfs/assets/108105714/730ed19c-0aee-4695-b577-7d21b05471e9

**Comment by rejetto** [comment]
i don't feel like dismissing this problem, and i don't think win7 is the problem.
let's investigate a bit on it.
i see in your video that you are not using the same config, as there's a config.yaml file in 0.52 and none in 0.51.
please try the following
1. run with same configuration (you can copy the config, or remove the config from 0.52, whatever you prefer)
2. see if beta4 has the problem https://github.com/rejetto/hfs/releases/tag/v0.52.0-beta4

**Comment by de7ang** [comment]
This time, I've placed the server within a simpler network Win10 virtual machine. The loading speed in the beta version has improved significantly, with Win7 loading in under 5 seconds. While Win10 displays a spinning action, it lasts less than 1 second. After refreshing, the loading speed remains the same. This scenario persists in both beta4 and beta5. In the official version, the spinning action never occurs under any circumstances.

**Comment by rejetto** [comment]
it's strange, these are my timings when accessing my HFS over local wifi, with cache disabled
<img width="790" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/4c65a753-63b6-444b-9e77-1a9407dc3752">

**Comment by de7ang** [comment]
Local access does indeed not exhibit this issue. In a new test scenario, when the server connects to the external network using a home router, the problem of slow loading in the beta version can be replicated when the gateway is not filled in on a Win7 client. When the server uses an enterprise switch solely for internal network usage, regardless of whether the gateway is set or not, accessing the beta version from Win7 encounters issues. All tests on Win10 have no issues.

**Comment by de7ang** [comment]
I think I've identified the problem. Only clients with internet access privileges can load from the beta server quickly. Clients without internet access experience slow loading issues, even though the server is not connected to the external network at this time.

**Comment by de7ang** [comment]
I suspect that the beta server instructs the clients to fetch some information from the external network first.

**Comment by rejetto** [comment]
> I think I've identified the problem. Only clients with internet access privileges can load from the beta server quickly. Clients without internet access experience slow loading issues, even though the server is not connected to the external network at this time.

ok, this is enlightning! i now know why.
it is trying to load an internet file, indeed.
i will work on it.

**Comment by rejetto** [comment]
[0.52-beta5.96](https://github.com/rejetto/hfs/files/14732065/hfs-windows.zip)
this version is supposed to fix the problem.
would you please give it a try?

**Comment by rejetto** [comment]
in the meantime i decided to release beta 6, which include this fix of course

**Comment by de7ang** [comment]
0.52-beta5.96 fixed this issue. nice work!
