### ISSUE TITLE
Support to generate linke QR code

### ISSUE THREAD

**Issue by Kelephant** [rejetto/hfs#53]
I want to download the files on HFS on my mobile phone, but I have to manually enter the URL every time, which is very troublesome. If I can generate a QR code on HFS, I can directly access my resources by scanning the code on my mobile phone.

**Comment by rejetto** [comment]
I don't exclude this coming in the future (as plugin), but it can be easily provided by the browser itself with a plugin.
Firefox: https://addons.mozilla.org/it/firefox/search/?q=qrcode&type=extension
Chrome: https://chrome.google.com/webstore/search/qrcode?utm_source=chrome-ntp-icon

Actually, both firefox and chrome have a "send to device" function right clicking on any link, to send it to your mobile, so you don't need QRcode at all with these browsers, and don't need installing a plugin either.
It doesn't look worth the effort to build another variant of the same feature.

**Comment by Kelephant** [comment]
thanks

**Comment by arminus** [comment]
Firefox with https://github.com/igorlogius/show-qrcode - this isn't really useful:

![grafik](https://github.com/rejetto/hfs/assets/683680/fd1baf99-c4ad-4cae-acab-db62941bb62c)

The link field is read-only and is therefor not picked up from show-qrcode even if selected, nor does show-qrcode's right-click menu pick up the URL.

Too bad, an additional button "Show QR code" would really be nice...

**Comment by rejetto** [comment]
i don't think the read-only is the problem, since you can still select the text.
maybe it is that is not a real link, but just text that seems like a link.
i will see if i can make it a link, or offer another button on the right, that will work as a link.

**Comment by arminus** [comment]
Or just integrate something like https://github.com/soldair/node-qrcode ?

**Comment by arminus** [comment]
Would you accept a pull request:

![QRCode](https://github.com/rejetto/hfs/assets/683680/9daf9d89-f008-4b92-bff2-ecab12c21620)

**Comment by rejetto** [comment]
that looks nice, and I'm happy to see someone is playing with the stuff.
I guess you are using the lib you said, but it looked a bit bloated with some yargs lib that I don't need, so I've found one that's should be much lighter (qr-creator, like 12KB once added).
I'm not even sure using a library is the best option. There's this service on google.
https://chart.googleapis.com/chart?cht=qr&chl=http%3A%2F%2Frejetto.com&chs=400
I guess some users would prefer not relying on google, if possible.
I'd be happy to look at your commit, and if everything is ok I'd be happy to accept the PR.

**Comment by rejetto** [comment]
i expect that many times you'll want to link to stuff that's not visible in the VFS.
then you'd need something that works also in the frontend (i should find a clearer name for this, maybe file-browser?).
Anyway, it would be of great help if I knew exactly how you mean to use the qrcode. Like... is it for you or other people? Does it matter if it's directly to the exact file you need, or is it ok even if you just reach the home of the server? describe your use-case, please.

Is it just me or Chome now has a QR code generation? You can right click on a page, and there's a "Create QR code" option.

**Comment by arminus** [comment]
My usecase is this: I have something (either a single file or a folder) on my PC which I quickly and easily want to share with either my own mobile device or someone else's who's in the same network (e.g. family, visiting friends) - without any special client app or other network access. With that button, I can easily do that but I only discovered your app today, I'm not familiar with it yet as to where else such a button might make sense.

The qr-creator works just as well - and personally, I only use chrome for software testing if I have to ;-)

**Comment by rejetto** [comment]
in the Virtual File System you design what you expose.
In the VFS you can put a folder that's linked to a folder on your disk.
You don't see the content of this folder from the VFS, not as it is now. To see the content you use the user frontend, that is the different frontend you get with the link in the field labeled "Link".
Not seeing the content, you cannot generate links to it, just to the general folder that you set in the VFS.

**Comment by rejetto** [comment]
so, while the qrcode that you programmed can be nice, relying on the firefox plugin will give you more convenience.
I'm under the impression that we'd better work to make the link a real link, so that you can right-click.

**Comment by arminus** [comment]
> relying on the firefox plugin will give you more convenience

not for me it doesn't as I had pointed out above

But you're the owner, feel free to do what you think is best... Regardless: I didn't find any docs on how you build the exe for windows? Can you point me to something?

**Comment by rejetto** [comment]
My first impression is that your PR is good.
You'll be still able to have the extra convenience that I was talking about nonetheless, as in the frontend you have real links, and you can already right-click whenever necessary.

You are right, the build instructions don't mention binaries generation. I will add it.
While I've started the project under Windows, I then moved to a Mac, and I'm currently generating all the builds here.  I do it by launching `npm run dist`, that is just build-all + dist-bin . I can't say if it will work correctly on Windows with all the changes it has been through, but surely I'm curious to know.

**Comment by rejetto** [comment]
i managed to have the Link field as a real link too.
I'm now fixing a bug, but hopefully I'll publish a new beta that will include it all within a couple of days.

**Comment by rejetto** [comment]
i published in a hurry, hopefuly all is well (automatic tests are passed, of course)
https://github.com/rejetto/hfs/releases/tag/v0.51.0-beta7

**Comment by rejetto** [comment]
somebody:
> I think the qr code should have black background, my scanner refuses to see it unless i open the image with darker background

i will adjust colors for next release

**Comment by arminus** [comment]
That was on oversight on my end, I didn't change the color after having replaced the first qr lib... That blue isnt't even aligned with the palette's blue :-/

**Comment by arminus** [comment]
> You are right, the build instructions don't mention binaries generation. I will add it. While I've started the project under Windows, I then moved to a Mac, and I'm currently generating all the builds here. I do it by launching `npm run dist`, that is just build-all + dist-bin . I can't say if it will work correctly on Windows with all the changes it has been through, but surely I'm curious to know.

FYI: npm run dist sort of works on windows if started form a bash (w/o bash it appears to windows "find" and breaks). Towards the end I get this

```
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules\open\xdg-open
  %2: path-to-executable/xdg-open
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules\open\xdg-open
  %2: path-to-executable/xdg-open
node:internal/child_process:414
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at spawn (node:child_process:761:9)
    at fabricate (C:\Data\Development\hfs\node_modules\pkg\lib-es5\fabricator.js:55:51)
    at fabricateTwice (C:\Data\Development\hfs\node_modules\pkg\lib-es5\fabricator.js:120:5)
    at MultiStream._queue (C:\Data\Development\hfs\node_modules\pkg\lib-es5\producer.js:271:68)
    at MultiStream._next (C:\Data\Development\hfs\node_modules\multistream\index.js:86:12)
    at Meter.onEnd (C:\Data\Development\hfs\node_modules\multistream\index.js:129:12)
    at Object.onceWrapper (node:events:631:28)
    at Meter.emit (node:events:517:28)
    at endReadableNT (node:internal/streams/readable:1368:12) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Node.js v18.18.2
```

But at least the windows exe is built - which is enough for me ;-)

**Comment by rejetto** [comment]
i'm really glad it works!
the warnings are issued by pkg processing module "open".
if there is any change to make the experience smoother I will consider it.

**Comment by rejetto** [comment]
> That was on oversight on my end, I didn't change the color after having replaced the first qr lib... That blue isnt't even aligned with the palette's blue :-/

don't worry, i just wanted to inform you. The comment wasn't even about "your" colors, as in my build I already adapted to the app's palette, and in next build I will have a darker background.
