### ISSUE TITLE
[BUG] Custom HTML doesn't get updated when changing pages

### ISSUE THREAD

**Issue by Timtam** [rejetto/hfs#531]
Hello there,

I've got a setup like we discussed in #481. It works fine as far as I can see. The markdown is currently converted into HTML and shown on the main page (currently officially available on https://hoard.reaperaccessibility.com). Its displayed above the file list and that is fine. However, if I click on a file or directory and switch pages to the new subfolder page, the markdown still gets displayed and doesn't update as well. Is that intended or how could I handle this? I don't know if that is a general issue or if its just my custom HTML that is broken so I thought a new issue would be better than reopening the old one.

Thanks!

**Comment by rejetto** [comment]
i looked at your hfs and i can't see the problem you are referring to.
I also look at the code I gave you, and i see the part responsible for the reset, at every change.
