### ISSUE TITLE
[Feature request] Add ability to open a URL shortcut instead of downloading it

### ISSUE THREAD

**Issue by Timtam** [rejetto/hfs#540]
Hello,

we do have Windows URL shortcuts on our HFS which allow Windows users just to press enter on them to open the linked URL from Explorer, which is really useful in combination with WebDAV. HFS obviously considers those regular files and thus only allows t download them. Would it be possible to allow to open them properly instead and just link to the linked website?
An example file would be here: https://hoard.reaperaccessibility.com/Links/Toni%20Barth's%20Reaper%20accessibility%20tutorials%20on%20YouTube.url

Thanks!

**Comment by rejetto** [comment]
i don't know these URL files.
i guess it's Windows prioprietary format.
so you'd like that when trying to open these files you actually get redirected? is that it?

**Comment by Timtam** [comment]
Yep exactly. Yeah I know, these are pretty exotic, but they work quite nicely to link to websites straight from Windows Explorer, so thats why we're using them.

**Comment by TEA-Time1** [comment]
> i don't know these URL files. i guess it's Windows prioprietary format.

Yup. In Windows, a shortcut to a website is a file with a .url extension. Windows just hides the extension by default. For example; I just created a shortcut to https://rejetto.com and called it Rejetto.  The file is actually called Rejetto.url and the contents are as follows (not sure what the 1st 2 lines are about):

[{000214A0-0000-0000-C000-000000000046}]
Prop3=19,11
[InternetShortcut]
IDList=
URL=https://rejetto.com/

**Comment by rejetto** [comment]
maybe this is better to be a plugin

**Comment by rejetto** [comment]
try new plugin
<img width="628" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/19d62e30-791b-4c60-b84f-0a1eef18ac8b">

**Comment by Timtam** [comment]
Awesome, works just fine here! Thanks!

**Comment by rejetto** [comment]
glad to hear it
