### ISSUE TITLE
HTML/CSS/JS Edit from Admin panel

### ISSUE THREAD

**Issue by djmakers** [rejetto/hfs#542]
It would be good to add the possibility to edit HTML and CSS, for users who do not know ts and js.

An option from cpanel would be welcome, because I would change many things related to the design, but I can't change them without knowing ts/js, or having access to HTML/CSS

Thank you very much for all the effort you make!

**Comment by rejetto** [comment]
you already have some html/css possibilities.
in the admin-panel menu you have "custom html".
please read here https://github.com/rejetto/hfs/wiki/Customization

if there's stuff that you think it's not possible, you can specify that and we'll discuss it.
