### ISSUE TITLE
bug ab ZIP perm & button

### ISSUE THREAD

**Issue by BussyBakks** [rejetto/hfs#544]
![image](https://github.com/rejetto/hfs/assets/108082159/ca92f891-6c50-4836-abfc-f646e8bd1243)
*my friend server*
yeah i just mark ZIP perm to "no one" and this popup show when i click to the disabled ZIP button, but if try to ZIP then 403 forbiden appears:)
i think it just a bug 🤷 (sorry for bad english)
version: 0.52.0-beta7
@rejetto

**Comment by rejetto** [comment]
the "forbidden" is correct, since you don't have permission.
so, i understand the problem is that you got the popup clicking.

sorry, i cannot reproduce your problem.
my zip is disabled too, and if i click on the button nothing happens.
maybe i didn't understand something, try with a video.
