### ISSUE TITLE
any plans for docker and docker compose support?

### ISSUE THREAD

**Issue by aniel300** [rejetto/hfs#547]
any plans to support docker and docker compose support?

**Comment by rejetto** [comment]
i'm not sure what is needed for docker as i'm no docker user myself, but i tried to write a few instructions here https://github.com/rejetto/hfs/wiki/Docker/
feel free to edit the page if you have any contribution.
i know @damienzonly is working on something.

**Comment by aniel300** [comment]
perfect can't wait to test it out
