### ISSUE TITLE
HU translation update

### ISSUE THREAD

**Issue by killersolyom** [rejetto/hfs#550]
Hi! I found a few language errors in the Hungarian translation and I would like to publish a corrected version.

[hfs-lang-hu.json](https://github.com/rejetto/hfs/files/14875840/hfs-lang-hu.json)

![image](https://github.com/rejetto/hfs/assets/44471935/5c2f282d-0a02-4de8-9dd7-cc4964e7017a)

**Comment by rejetto** [comment]
thank you, i'm including your changes in next release.

This file is limited to version 0.49, while new lines have been added in time.
In your file "Comment" is the last line, but you can see new ones at this address https://github.com/rejetto/hfs/blob/52/src/langs/hfs-lang-en.json
I'm saying in case you'd like to do also the new lines.
