### ISSUE TITLE
HFS log don’t know what files were deleted specifically.

### ISSUE THREAD

**Issue by ilanni2460** [rejetto/hfs#558]
You can see the action of deleting files in the hfs log, but you don’t know what files were deleted specifically.

![1](https://github.com/rejetto/hfs/assets/5058391/cbe952ef-9926-49d5-bd04-dee2251cde41)

**Comment by rejetto** [comment]
that's bad, thanks for reporting.
keep you posted

**Comment by rejetto** [comment]
fixed by version 0.52.1
