### ISSUE TITLE
a few feature requests

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#560]
1. dark mode switch on home page of admin panel (by defualt respect browser)
2. open in new tab for links
3. create link button on front end for accounts with upload permission
4. change default link for new links to example.com from google.com (more appropriate)

**Comment by rejetto** [comment]
please keep every "issue" here to one thing, as this is harder to manage

1. would you use it?
2. done
3. so you want to create web-links from the frontend?
4. done

**Comment by W-i-n-7** [comment]
i didnt catch that
please keep every "issue" here to one thing, as this is harder to manage
what did you mean by this?

1. yeah
3 yes would be nice and then you dont need to give someone admin-panel access to create them too though i suppose they could just upload windows url files if the plugin is enabled but thats not quite the same

**Comment by rejetto** [comment]
3. web-links are part of the VFS while uploads are written on disk. The folder where you are browsing may not have a nodo in  the VFS, as it can be a subfolder, so this cannot work.

**Comment by W-i-n-7** [comment]
oh i couldnt think of that myself
yes that would be the case sadly

**Comment by rejetto** [comment]
1. done
