### ISSUE TITLE
error middleware plugin thumbnails: Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#569]
![unnamed](https://github.com/rejetto/hfs/assets/90262580/e31ce9b7-ac6e-4425-9bce-626f4201dcd0)
my console is full of this

**Comment by W-i-n-7** [comment]
21.4.2024
22.33.08
error
Error: bad content-type header, no multipart boundary
21.4.2024
22.33.07
error
Error: bad content-type header, no multipart boundary

22.4.2024
22.32.51
log
error middleware plugin thumbnails: pngload_buffer: libspng read error


21.4.2024
23.23.53
log
error middleware plugin thumbnails: Premature close

**Comment by W-i-n-7** [comment]
other errors i found in the log

**Comment by rejetto** [comment]
next time report the bug on the plugin's page please, to not be "counted" as bug of hfs.
it's likely to be a file that's not working for some reason, but i need the file to work on it.

**Comment by W-i-n-7** [comment]
> next time report the bug on the plugin's page please, to not be "counted" as bug of hfs. it's likely to be a file that's not working for some reason, but i need the file to work on it.

oh okay
as for the file, i now noticed that there was 2 wallpapers with no thumbnail and found out this was because a bmp file was renamed to be a png instead
maybe the plugin could look for the file format inside the file and not with the extension? though this may be a big ask
for example in Hex 42 4D is for a .bmp file

**Comment by rejetto** [comment]
i don't think i will work for such a feature in the plugin, but if someone wants to work on it, feel free.
can you send me one file causing the problem? i may still devise a better behavior.

**Comment by W-i-n-7** [comment]
> i don't think i will work for such a feature in the plugin, but if someone wants to work on it, feel free. can you send me one file causing the problem? i may still devise a better behavior.

thats fine i wasnt expecting it

![Windows7](https://github.com/rejetto/hfs/assets/90262580/e9b6c9b1-2d69-4c9d-b21c-68dcf31dcae5)
this file is one (bmp renamed to png)

**Comment by W-i-n-7** [comment]
oh, it embedded
here downloadable
[Windows7.zip](https://github.com/rejetto/hfs/files/15080473/Windows7.zip)

**Comment by W-i-n-7** [comment]
@rejetto maybe atleast have it so that the plugin doesnt cause these errors in the console?

**Comment by rejetto** [comment]
that's what i meant

**Comment by rejetto** [comment]
ok, now you can update the plugin.
thanks for reporting
