### ISSUE TITLE
Download zipped folder from link

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#57]
It would be nice to be able to download the zipped directory via a direct link: this makes it possible to download files with multi-threaded managers like Download Manager

**Comment by rejetto** [comment]
it should already be possible.
The download-zip button is actually a link you can copy.
This is true without login, I'm not sure how things go when login is required.

**Comment by 6elkir** [comment]
infinite login window in download manager, but login|pass correct.

**Comment by rejetto** [comment]
do you login correctly using a browser?

**Comment by 6elkir** [comment]
yes)

**Comment by rejetto** [comment]
so, i guess it's a problem with the browser of the download manager.
You didn't specify which one, by the way.
HFS is currently requiring a recent browser for login, [like 2019 or newer](https://caniuse.com/bigint)
It's possible the browser inside the download manager is not supporting it. This may as well be a problem of this other software.
I can give a look when I get time, if you tell me the name of the software.
If you can make a video of the problem, it could be useful.

**Comment by 6elkir** [comment]
Download Manager 6.19.7.1655

**Comment by rejetto** [comment]
i cannot find a software with that name.
can you link its website?

**Comment by rejetto** [comment]
is it this? https://www.internetdownloadmanager.com/

**Comment by 6elkir** [comment]
https://westbyte.com/
but site from Russia - 403. May be war reason =\

**Comment by rejetto** [comment]
on that website there is a software named "internet download accelerator", not "download manager".
Its latest version is 6.24, while you have 6.19. You may want to try to update to see if it solves the problem.

**Comment by 6elkir** [comment]
I write demo video here:
https://share.dvor-net.ptz.ru/cq3cXXXgJF.mp4

**Comment by rejetto** [comment]
ok, your video makes me think they try to use "basic" http authentication.
I may try to support that for downloads.
It makes sense.

**Comment by rejetto** [comment]
so, the name of the software now is "download master" ? 😁 
[is this it?](https://en.vessoft.com/software/windows/download/downloadmaster)

**Comment by dzw13579** [comment]
> ok, your video makes me think they try to use "basic" http authentication. I may try to support that for downloads. It makes sense.

I guess it's the same problem to me when I use "IDM" to login😂

**Comment by 6elkir** [comment]
> so, the name of the software now is "download master" ? 😁 [is this it?](https://en.vessoft.com/software/windows/download/downloadmaster)

yes)

**Comment by rejetto** [comment]
next release should solve your problem.
I tested it with FDM and curl.
