### ISSUE TITLE
New HFS server 0.52.3 browse option not list files

### ISSUE THREAD

**Issue by ciscohack** [rejetto/hfs#573]
HFS version 0.52.3 version under the options button not list files if trying to browse... The old version does not have such an issue. if you go into the options tab then choose https and browse the certificate file from the local system it will not list any directory file.

Here is an example to see empty dialogue  

<img width="1122" alt="image" src="https://github.com/rejetto/hfs/assets/11479557/8089a7cd-91d5-44fe-bca7-d9a10a4bc62b">

Side query :-- Any plan to add HTTP2/http3 in future.

**Comment by rejetto** [comment]
thanks for reporting!
it will be fixed in next release, asap.

there's no update on the http2 thing, see #446

**Comment by rejetto** [comment]
published 0.52.4
