### ISSUE TITLE
Accounts imported in bulk via CSV are encountering certificate parameter issues during login

### ISSUE THREAD

**Issue by de7ang** [rejetto/hfs#575]
Accounts imported in bulk via CSV are encountering certificate parameter issues during login, though the passwords are entered correctly.
![微信截图_20240429162949](https://github.com/rejetto/hfs/assets/108105714/2792c2b7-bc31-4132-8ca0-7d82252515f0)

**Comment by rejetto** [comment]
i would need the english error to dig more, but i see that it's about the certificate.
I don't think this is a bug in hfs, but some problem with your certificate.
I'm quite sure it has nothing to do with csv and accounts.
Try creating an account manally, and you'll see the same error.
