### ISSUE TITLE
Can't create admin account from config file

### ISSUE THREAD

**Issue by vyachkoslav** [rejetto/hfs#579]
When I try creating admin profile with running hfs by appending `create-admin: password` to config.yaml, server logs that admin account is created, clears the create-admin line, but the account doesn't appear in config and I can't login to admin:password.

**Environment (please complete the following information):**
 - OS: node:alpine3.19 docker
 - HFS Version 0.52.4

**Comment by rejetto** [comment]
i tried to reproduce the problem, but couldn't.
i'm not good with docker and alpine.
what's the content of your config after those steps?

**Comment by rejetto** [comment]
ok, maybe i've found, keep you posted

**Comment by rejetto** [comment]
ok, i've fixed the bug and it will be included in next release.
thanks for reporting.
are you using npx?

**Comment by vyachkoslav** [comment]
yes, but I also install hfs with `npm i` on non-root user while building container

**Comment by rejetto** [comment]
can you workaround by editing the config file, until i publish the fix?

**Comment by vyachkoslav** [comment]
yep, no problem

**Comment by rejetto** [comment]
fixed in 0.52.5
