### ISSUE TITLE
Account -> Redirect subtly breaks if you do not start with a slash

### ISSUE THREAD

**Issue by soleofthesea** [rejetto/hfs#585]
Let's say I have a HFS server that can be accessed via `https://example.com/files`.

If I open the Admin panel -> Accounts, there is the option 'Redirect' to automtically bring the user to a certain folder.

If I input `foo`, logging in will take me to `https://example.com/foo`, with the `files` part deleted. Browsing files works, but attempting to open anything returns a 404.

If I input `/foo`, then everything works properly.

**Comment by rejetto** [comment]
you mean that you have a reverse-proxy that maps /files to your HFS root?
https://github.com/rejetto/hfs/wiki/Reverse-proxy

**Comment by soleofthesea** [comment]
Yes, that is correct.

**Comment by rejetto** [comment]
ok, the solution to your problem is in the link that i posted above.

You should already see a link saying "Read our guide on proxies" inside the home page of the Admin-panel. Can you confirm?

**Comment by soleofthesea** [comment]
My NGINX config params are identical to the example provided and I have indeed setup the correct URL in section 'Internet'.

To note, the proxy itself works, and so is the option I am filing this bug report for - as long as you have put a leading / at the start. But the settings allow you to omit it.

![image](https://github.com/rejetto/hfs/assets/35699509/1f030e91-26ba-4a9f-a86c-aa1acf163dee)

**Comment by rejetto** [comment]
you say the setting "allow" you to omit the leading /, but that sounds right, as i expect some cases you want to have relative links, instead of absolute links.
In the end you can enter anything, right?
<img width="206" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/d359d562-bcc0-4df7-b3d7-e6c88e6dfa7a">

can you enter the leading / correctly in the field?

anyway, i had a closer look to the "redirect" function, and if i'm not mistaken, you are supposed to just enter "/" there, and your prefix of the reverse proxy should be prepended automatically. Can you give me a feedback about this?

**Comment by rejetto** [comment]
ok, maybe now i'm seeing what's happening here.
the logic i'm applying for redirection is to automatically prefix with the reverse-proxy-prefix ONLY if the address you enter starts with /
This was supposed to allow relative links, but from what you are saying it seems this is not working correctly. I'm going to test it.

**Comment by soleofthesea** [comment]
> the logic i'm applying for redirection is to automatically prefix with the reverse-proxy-prefix ONLY if the address you enter starts with /

Yes, that's the part I'm hung up on. Is it intentional?

**Comment by rejetto** [comment]
it was intentional, but i still have to understand if that's the right thing to do

**Comment by rejetto** [comment]
please let me know about this

> anyway, i had a closer look to the "redirect" function, and if i'm not mistaken, you are supposed to just enter "/" there, and your prefix of the reverse proxy should be prepended automatically. Can you give me a feedback about this?

**Comment by soleofthesea** [comment]
> anyway, i had a closer look to the "redirect" function, and if i'm not mistaken, you are supposed to just enter "/" there, and your prefix of the reverse proxy should be prepended automatically. Can you give me a feedback about this?

Yup, no issues.

(Also I apologize: I used 'files' both for the NGINX location and the HFS subfolder. So the URL is `https://example.com/files/Files`. That must be confusing.)

I must admit, I'm not understanding what is the relative link feature intended for? As in, if I only type in `foo`, then where is it _supposed_ to take me?

**Comment by rejetto** [comment]
the relative is for when you login while NOT in the root.

if you have "files" already in nginx configuration, you probably want hfs to not have the "files" folder, but just all things in the home.

**Comment by rejetto** [comment]
while testing, i've found that the account-redirect feature is broken since 0.52.1 😅

**Comment by rejetto** [comment]
i just updated the [wiki page](https://github.com/rejetto/hfs/wiki/Reverse-proxy) to include x-forwarded-host in the configuration.
some features (like roots, that you may not use) will not work with it.

and i've just found a bug about roots+proxy. All fixed in next release.

**Comment by rejetto** [comment]
ok, all fixed in 0.52.6
thanks
