### ISSUE TITLE
A problem with uploading a 300MB file using HFS

### ISSUE THREAD

**Issue by FSparkling** [rejetto/hfs#588]
Dear community members,

I am encountering an issue with the HFS file transfer system and would greatly appreciate your help and guidance. Here is a detailed description of the problem:

Problem description:
I am attempting to upload a file of approximately 300MB in size by dragging and dropping it into the file list. However, I am receiving the following error message:
```
You can drag and drop files into the file list to upload
1 skipped - 1 failed to upload
=========================================
```
Interestingly, I have noticed that uploading smaller files works fine.

I have tried several troubleshooting steps, such as rebooting the system and checking the network connection, but the issue persists. I am curious about the possible causes of this problem and how it can be resolved.

Additional information:
- The operating system I am using is Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-167-generic x86_64).
- The version of HFS I am using is 0.52.5.

Thank you very much for your assistance!

---------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------

尊敬的社区成员们，

我在使用HFS文件传输系统时遇到了一个问题，希望能够得到您的帮助和指导。具体问题描述如下：

问题描述：
我正在尝试将一个大小约为300MB的文件通过拖放到文件列表中进行上传，但是遇到了以下报错信息：
```
您可以将文件拖放到文件列表中进行上传
1 skipped – 上传失败1 失败
=========================================
```
然而，我注意到当我尝试传输其他较小的文件时，上传是正常的。

我已经尝试了一些解决方法，例如重新启动系统、检查网络连接等，但仍然无法解决问题。我想知道这个问题的可能原因以及如何解决。

附加信息：
- 我正在使用的操作系统是 Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-167-generic x86_64)。
- 我使用的HFS版本是 0.52.5。

非常感谢您的帮助！

**Comment by rejetto** [comment]
are you accessing HFS directly or there's another server/proxy in between?

**Comment by FSparkling** [comment]
Hello, thank you for your answer. I set it up in a public network environment and used caddy to do the reverse generation processing



---Original---
From: "Massimo ***@***.***&gt;
Date: Sun, May 12, 2024 04:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rejetto/hfs] A problem with uploading a 300MB file using HFS(Issue #588)




 
are you accessing HFS directly or there's another server/proxy in between?

**Comment by rejetto** [comment]
i don't know what you mean with caddy and reverse generation processing, but I suspect you meant reverse-proxy, like nginx.
i'm quite sure your problem has nothing to do with HFS, but with a reverse-proxy in between. You should configure that for max upload size.
You can verify that by accessing your HFS directly at its IP and upload from there.

Refer to this page https://github.com/rejetto/hfs/wiki/Reverse-proxy
where you can also see a line that's necessary on nginx to disable the limit on upload.

**Comment by FSparkling** [comment]
Okay٩()ᵒᵏᵎᵎᵎᵎ! I will take your advice! Thanks again for your help! Thank you very much!



---Original---
From: "Massimo ***@***.***&gt;
Date: Sun, May 12, 2024 16:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rejetto/hfs] A problem with uploading a 300MB file using HFS(Issue #588)




 
i don't know what you mean with caddy and reverse generation processing, but I suspect you meant reverse-proxy, like nginx.
 i'm quite sure your problem has nothing to do with HFS, but with a reverse-proxy in between. You should configure that for the max upload size.
 You can verify that by accessing your HFS directly at its IP.
 
Refer to this page https://github.com/rejetto/hfs/wiki/Reverse-proxy
 where you can also see a line that's necessary on nginx to disable the limit on upload.
