### ISSUE TITLE
(dev) Bugs on HFS/plugin config

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#59]
I've encountered *several* tough bugs while making some other plugin config.

Let me say one here... (and the rest after me successfully debug them, in separate issues.)

At [here](https://github.com/rejetto/hfs/blob/208df4891044728fa4de94e05492fe996227135e/server/src/plugins.ts#L40), HFS checks if the config being set is the same as default, if yes then don't set -- so, the config remains unchanged :(
(i.e. you can't have default value anymore, once you set it to something else)

P.S. it's 2 hours debugging on *this*. Hope I have better luck

**Comment by NaitLee** [comment]
Wait, I still think this isn't always true. This is reproduced when I modify some code to remove another bug.

I'd re-open after I'm sure what to do

**Comment by rejetto** [comment]
what happens there is that config is always rewritten as a whole.
The object is not just a "diff", so when you pass a default value, and it is excluded by the `pickBy`, the previous value is virtually deleted, so it IS changed.
Any following attempt to read that (deleted) value will result in the default value.

**Comment by rejetto** [comment]
the only problem i can imagine is if you use that api to set/get values that were not declared.
I suppose such attempt will work while you are NOT using the configuration form: that will overwrite any "undeclared" key.
I think it may be interesting to preserve such values, to provide easy storage for plugins for values you don't want to expose to user.

**Comment by NaitLee** [comment]
See #60. \*Sigh\*
