### ISSUE TITLE
add total uptime to Monitoring tab

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#598]
nothing to add to title

**Comment by rejetto** [comment]
what do you meant by "total" ?
you want the value to not reset at each restart?

**Comment by W-i-n-7** [comment]
yes a separate value that doesnt reset

**Comment by W-i-n-7** [comment]
now that i think about it it seems kinda useless unless u dont run it 24/7

**Comment by rejetto** [comment]
and you use it 24/7, so you don't really want this 🫠

**Comment by rejetto** [comment]
wait, i'm lost in your double negation.
Do you think it's useful for 24/7 cases?

**Comment by W-i-n-7** [comment]
> wait, i'm lost in your double negation. Do you think it's useful for 24/7 cases?

okay i cant find anyway it would be useful just there
apologies
