### ISSUE TITLE
(dev) `api.setConfig` resets other config to default (i.e. removed them)

### ISSUE THREAD

**Issue by NaitLee** [rejetto/hfs#60]
FINALLY found it. I don't even know how to tell it until now.

Look [here](https://github.com/rejetto/hfs/blob/208df4891044728fa4de94e05492fe996227135e/server/src/plugins.ts#L41),
Changing to this can solve:
```typescript
    pluginsConfig.set(v => ({ ...v, [id]: _.isEmpty(config) ? undefined : Object.assign(v[id], config) }))
```

And a test plugin to test it: [test.zip](https://github.com/rejetto/hfs/files/8948595/test.zip)

1. Manage to install & enable it.
2. Note the two configs inside, they have default value `foo: "apple"` and `bar: "orange"`
3. Browse root url, the middleware routine inside will `setConfig` `bar` to `banana`, then show the two fruit name on screen
4. Go to Admin plugin config, change `apple` to `potato`, save it. In terminal you can see the change being applied
5. Refresh page, it's still `apple`. In terminal you can see `foo` is changed back to `apple`, reflected by `subscribeConfig`

**Comment by rejetto** [comment]
ok, i see the problem: the *rest* api was conceived to receive a full object, while the same code is being used for a single key.
It's ok for me to assume a partial object can be passed, but then your change wouldn't account for cases where we are unsetting a key, to make it same as defaultValue.
Also, I'm not sure it's ok to modify v[id] object.
Will this work for you ?

```javascript
export function setPluginConfig(id: string, config: Dict) {
    pluginsConfig.set(v => {
        const fields = getPluginConfigFields(id)
        config = _.pickBy({
            ...v[id],
            ...objSameKeys(config, (v, k) =>
                v === null || same(v, fields?.[k]?.defaultValue) ? undefined : v)
        }, x => x !== undefined)
        return { ...v, [id]: _.isEmpty(config) ? undefined : config }
    })
}
```

**Comment by rejetto** [comment]
this is nicer and should work as well
```javascript
export function setPluginConfig(id: string, changes: Dict) {
    pluginsConfig.set(allConfigs => {
        const fields = getPluginConfigFields(id)
        const oldConfig = allConfigs[id]
        const newConfig = _.pickBy({ ...oldConfig, ...changes },
            (v, k) => v != null && !same(v, fields?.[k]?.defaultValue))
        return { ...allConfigs, [id]: _.isEmpty(newConfig) ? undefined : newConfig }
    })
}
```

**Comment by NaitLee** [comment]
It worked :)

Thanks!
