### ISSUE TITLE
Can I directly call the local program when opening a file?

### ISSUE THREAD

**Issue by SKYINSTALL** [rejetto/hfs#606]
For example, the dwg format of the drawing can be directly opened using local AutoCAD instead of downloading it。solidworks,pdf,excel,word......

**Comment by rejetto** [comment]
normally, a browser won't open autocad (or other) files.
if the browser itself doesn't support this, there's nothing i can do to interact with autocad (or other programs) from within a web page, it's beyond this software's powers.

if your purpose was not merely to save a couple of clicks, but to be able to edit the file in autocad saving the changes on the server, you may consider the "reupload" plugin.
