### ISSUE TITLE
Debian 12 x64 start problem

### ISSUE THREAD

**Issue by BreakHear7** [rejetto/hfs#609]
I try start hfs on Debian 12.5.0 x64, but I get error Illegal instruction and exit code 132.
run by /usr/bin/npx -y hfs@lates
npm@9.2.0
node v18.19.0
Python 3.12.1
uname -a:
Linux debian 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

It worked good on x86 version of Debian

How i can fix it?

**Comment by rejetto** [comment]
linking answer here for convenience
https://github.com/rejetto/hfs/discussions/610#discussioncomment-9702726

can we close this?
