### ISSUE TITLE
Listen only on all ipv4/ipv6

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#611]
My router does not correctly work with ipv6 ports so i only tend to host stuff on ipv4 and seeing ipv6 addresses i can't use is an eyesore.

![Screenshot 2024-06-06 201702](https://github.com/rejetto/hfs/assets/24497821/08bac66b-f46c-4e0b-8015-9aae62a68759)

An option "All ipv4 addresses" in the "Listen interface" would be great.

**Comment by rejetto** [comment]
how many ipv4 do you have?

**Comment by SanokKule** [comment]
Lan ip from router and public ip

**Comment by rejetto** [comment]
but your hfs sees only one, right?

**Comment by SanokKule** [comment]
In console both, in "Listen interface" dropdown there's 127.0.0.1 and my local ip.

**Comment by rejetto** [comment]
then you should select your local ip in the listen interface.
that should do

**Comment by SanokKule** [comment]
I'm not able to connect in that case from the same pc the server is on.

**Comment by rejetto** [comment]
right, because localhost is not part of it

**Comment by rejetto** [comment]
coming with 0.54
