### ISSUE TITLE
Black screen Log window

### ISSUE THREAD

**Issue by rejetto** [rejetto/hfs#615]
### Discussed in https://github.com/rejetto/hfs/discussions/614

<div type='discussions-op-text'>

<sup>Originally posted by **PH5HP** June  9, 2024</sup>
Hi,

Very strange. I got a black screen in the admin area when I try to go to the log section. 

I tried:
- restart HFS
- Tried another browser, but in both I got the same
- Tried other section, but it happens only when I trie to go to the log section

Next thing I will try is to boot my computer.

UPDATE:
Booting the computer did not help. Still a black browser window if I go to the log section in the admin area. Yesterday when shut down th computer all was OK.

Kind regards,
Henk - ph5hp.nl - fileserver.ph5hp.nl

![image](https://github.com/rejetto/hfs/assets/140949730/c63ffea3-d689-48bb-9cd9-e4dd9f4c0067)
</div>

**Comment by PH5HP** [comment]
Hi,

The log screen just came back. I changed nothing. Just clicking refresh. It seems to be a layout issue which causes the screen to go black. If I scroll down it goed black again. So I can't see what line is causing it.

Could what caused this blak screen been written in the logfile of this date?

Kind regards,
Henk - ph5hp.nl - https://fileserver.ph5hp.nl

**Comment by PH5HP** [comment]
Hi Rejetto,

This is what I have done:

- I opened the logfile of today's date
- In the admin section->Log I scrolled carefully line by line till the screen went black to determine after which line this happens
- I looked up the last line before the screen went black in the logfile I opened
- I think the next line is the line which causes the problem

This is the line:

209.170.125.226 - - [09/Jun/2024:12:01:20 +0200] "GET / HTTP/1.1" 200 12103 "{\"country\":\"US\",\"ua\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36\"}"

I hope this helps.

Kind regards,
Henk - ph5hp.nl - https://fileserver.ph5hp.nl

**Comment by rejetto** [comment]
hey, i don't think that's the line causing the problem.
i think the right line has some % sign in the address.
anyway, don't worry, i should be able to fix it with information i have.
keep you posted

**Comment by PH5HP** [comment]
Hi,

I found this ones in the log after each other:

146.70.200.117 - - [09/Jun/2024:11:17:16 +0200] "GET /?n=%0A&cmd=ipconfig+/all&search=%25xxx%25url%25:%password%}{.exec|{.?cmd.}|timeout=15|out=abc.}{.?n.}{.?n.}RESUTLT:{.?n.}{.^abc.}===={.?n.} HTTP/1.1" 200 12103 "{\"country\":\"AU\",\"ua\":\"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\"}"
146.70.200.117 - - [09/Jun/2024:11:34:56 +0200] "GET /?n=%0A&cmd=ipconfig+/all&search=%25xxx%25url%25:%password%}{.exec|{.?cmd.}|timeout=15|out=abc.}{.?n.}{.?n.}RESUTLT:{.?n.}{.^abc.}===={.?n.} HTTP/1.1" 200 12103 "{\"country\":\"AU\",\"ua\":\"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\"}"
146.70.200.117 - - [09/Jun/2024:11:35:44 +0200] "GET /?n=%0A&cmd=ipconfig+/all&search=%25xxx%25url%25:%password%}{.exec|{.?cmd.}|timeout=15|out=abc.}{.?n.}{.?n.}RESUTLT:{.?n.}{.^abc.}===={.?n.} HTTP/1.1" 200 12103 "{\"country\":\"AU\",\"ua\":\"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\"}"
209.170.125.226 - - [09/Jun/2024:12:01:20 +0200] "GET / HTTP/1.1" 200 12103 "{\"country\":\"US\",\"ua\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36\"}"

Kind regards,
Henk - ph5hp.nl - https://fileserver.ph5hp.nl/

**Comment by rejetto** [comment]
these requests are probing to find faulty old hfs 2.3
i'm adding these to the "spam" marker.

here is a preview of next release, fixing several bugs, if you like
[hfs-windows.zip](https://github.com/user-attachments/files/15754467/hfs-windows.zip)

**Comment by rejetto** [comment]
had you the chance to try this?

**Comment by rejetto** [comment]
fixed in https://github.com/rejetto/hfs/releases/tag/v0.53.0-rc13
