### ISSUE TITLE
cant download more than 1GB outside my network. 

### ISSUE THREAD

**Issue by SilverChocobo95** [rejetto/hfs#616]
Hello Rejetto.

I discovered your work recently and I love it, HFS seems like an incredible application to me, that's why I decided to install it in my homelab so I can download files from outside my network.

I have configured the application correctly and configured a reverse proxy, being able to access my data from any network, but I noticed that after downloading 1GB, I receive a "network error" and the download stops. I can confirm that when I download something within my network, this error does not occur. 

I have verified from the monitoring tab that the "SENT" value never exceeds 1Gb, even with files larger than 1gb.

Is this a bug, or am I doing something wrong?

Thank you so much for your work!
![Captura de pantalla 2024-06-08 181653](https://github.com/rejetto/hfs/assets/172202372/d4028373-396f-4ca2-b4b4-76fbb6974475)

**Comment by rejetto** [comment]
hey, thanks for you the kind words!
nothing in what you say about the problem points to HFS, as the problem disappears as soon you don't use the reverse proxy.
several people are using hfs with a reverse proxy, and no one reported a problem like that, so it must not be a common thing.
in my experience, even outside hfs, this kind of problems have always been related to upload, never download, so i'm a bit surprised.
sadly i'm not the right person to help you configure the proxy.
but are you sure you need to use the reverse proxy, after all?

**Comment by SilverChocobo95** [comment]
Hey! Thank you very much for your quick response!

It's a curious problem, because if I resume the download, it continues from where it left off before giving the error. I can download files but I have to reset the download, so not a big deal.

I use a reverse proxy because it is more convenient for me to remember a URL than to remember my public IP, since it changes every so often and I don't want to have too many open ports on my router.

I'll take a look at my proxy.

Again, thank you very much and excellent work!
