### ISSUE TITLE
different address

### ISSUE THREAD

**Issue by maandoz** [rejetto/hfs#617]
hi rejetto,

I use win10 pro 64 -
I haven't been able to access hfs for some time
I'm sure I made a mistake
Is it possible to restore?
![pic](https://github.com/rejetto/hfs/assets/171188942/d3f8b34e-72d4-43d7-948b-823cb00c8c77)

Thank you

**Comment by rejetto** [comment]
hey, HFS is unable to launch your browser. 
can you confirm that the browser is not open at start?
anyway, that's not very important, you can do it manually, of course, or not do it at all, HFS will still work in the background.
sadly, i have no idea on how to solve the problem. I make the request to the system, but it's not granted to work.
I just made a test on my win11 machine, and the browser is open regularly with 0.53.0-beta10
let me know if you find any detail or a solution
