### ISSUE TITLE
How to customize logo in hfs

### ISSUE THREAD

**Issue by ilanni2460** [rejetto/hfs#619]
How to customize logo in hfs

**Comment by rejetto** [comment]
exactly what logo are you talking about?

**Comment by ilanni2460** [comment]
@rejetto  hfs management background
![1](https://github.com/rejetto/hfs/assets/5058391/044c330f-ebd1-4ac6-8549-a2e52e5184ee)

**Comment by rejetto** [comment]
there's no such option at the moment

**Comment by ilanni2460** [comment]
Okay, I hope it can be customized

**Comment by rejetto** [comment]
would you care to tell me the reasons you want to remove HFS name from administration panel?

**Comment by ilanni2460** [comment]
@rejetto Sorry, this was requested by my boss。Let me close it first。

**Comment by rejetto** [comment]
i was asking just to understand people's needs.
i'm not excluding this possibility in the future.
would it be good if i moved name and version inside the the "home" page ?
<img width="254" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/97314b7e-9e1e-429c-abb5-042cfc73ede8">
