### ISSUE TITLE
The browser's header icon in the hfs log cannot be displayed

### ISSUE THREAD

**Issue by ilanni2460** [rejetto/hfs#620]
The browser's header icon in the hfs log cannot be displayed

My hfs server runs on the intranet and cannot connect to the Internet due to security requirements.

Suggestion: The icon of this browser is directly included in the hfs application

![1](https://github.com/rejetto/hfs/assets/5058391/1c0c1a20-fdef-4a94-8df8-70785979283c)

**Comment by rejetto** [comment]
this is a tricky thing, as i don't want to have legal issues by embedding logos of other companies in my software.
i need a safe solution

**Comment by rejetto** [comment]
for the time being, my solution is to fallback to simple text when internet is not available, like this

<img width="376" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/6c0d1f8d-34b9-4fcb-8567-3a784a11d4ed">

you can still hover your mouse on the name to the the full user-agent text

**Comment by ilanni2460** [comment]
> for the time being, my solution is to fallback to simple text when internet is not available, like this
> <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/1367199/338476853-6c0d1f8d-34b9-4fcb-8567-3a784a11d4ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTE3ODMsIm5iZiI6MTcxODA5MTQ4MywicGF0aCI6Ii8xMzY3MTk5LzMzODQ3Njg1My02YzBkMWY4ZC0zNGI5LTRmY2ItODU2Ny0zYTc4NGExMWQ0ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDczODAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U1ZDYwMzliMzhkM2VlNjAzYjc2MDBmNzJjNGE3MDI2NjMzOTliNjhkYTZhZDA3YjdhZThlMzlmODJiZDcyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.POUoSZfL8Nv5qfz2Uzm4D35ULt7JOS1pgiHT89hF5sQ">
> 
> you can still hover your mouse on the name to the the full user-agent text

Oh, this solution is great 👍

**Comment by ilanni2460** [comment]
@rejetto If you have the latest package, I can test it first

**Comment by rejetto** [comment]
sure!
this is a preview version including the fix
[hfs-linux.zip](https://github.com/user-attachments/files/15784188/hfs-linux.zip)
[hfs-windows.zip](https://github.com/user-attachments/files/15784191/hfs-windows.zip)

**Comment by ilanni2460** [comment]
@rejetto I tested it using the latest linux package and it was ok. Thank you very much 🙏

![1](https://github.com/rejetto/hfs/assets/5058391/3f6ec43e-c7cf-4641-b41f-24e80ecbfbc2)

**Comment by rejetto** [comment]
very well!
