### ISSUE TITLE
How to customize the .hfs directory in the Linux version of hfs

### ISSUE THREAD

**Issue by ilanni2460** [rejetto/hfs#621]
How to customize the .hfs directory in the Linux version of hfs

I am using the Linux version of hfs, and added hfs to systemd for management, as follows:
`
cat /etc/systemd/system/hfs.service 
[Unit]
Description=HFS
After=network.target

[Service]
Type=simple
Restart=always
ExecStart=/usr/local/hfs/hfs --config /usr/local/hfs/config.yaml

[Install]
WantedBy=multi-user.target

`

The hfs service is running normally, but I found that there is a hidden directory .hfs in the root user's home directory. How can I customize this hidden directory?

![1](https://github.com/rejetto/hfs/assets/5058391/b3e4915c-4ea4-440f-8d33-b322ee6cb42b)

**Comment by rejetto** [comment]
don't use --config, use --cwd PATH_TO_DIRECTORY

the config file will be stored inside

**Comment by rejetto** [comment]
i took the chance to improve the documentation about this point

**Comment by ilanni2460** [comment]
@rejetto Thank you very much. This is my modified configuration.

`
cat > /etc/systemd/system/hfs.service << "EOF"
[Unit]
Description=HFS
After=network.target
[Service]
Type=simple
Restart=always
ExecStart=/usr/local/hfs/hfs --cwd /usr/local/hfs/
[Install]
WantedBy=multi-user.target
EOF
`
