### ISSUE TITLE
Fix please this feature

### ISSUE THREAD

**Issue by djmakers** [rejetto/hfs#629]
After Add to HFS link is wrong !

![image](https://github.com/rejetto/hfs/assets/47154419/8ae334cf-f183-41ae-a483-8cbed21c3b8a)

![image](https://github.com/rejetto/hfs/assets/47154419/527348ad-aac2-4d01-b844-ed1005e9d92d)

![image](https://github.com/rejetto/hfs/assets/47154419/d1f8f13d-a3a2-44b3-9964-0736b985f3c4)

Repair copied link please! Thx!

**Comment by rejetto** [comment]
what version?

**Comment by rejetto** [comment]
while you wait for the fix, maybe solve on your own:
go to admin/shared, click remove-integration, click system-integration
and this time when you specify the folder, be sure that you add a "/" at the beginning.
let me know

**Comment by rejetto** [comment]
the fix will be included in next release.
thanks for reporting!

**Comment by djmakers** [comment]
Last version ...
![image](https://github.com/rejetto/hfs/assets/47154419/f649b5e7-90a3-4400-8ec8-5cf7f52944e4)

**Comment by rejetto** [comment]
fixed in https://github.com/rejetto/hfs/releases/tag/v0.53.0-rc13
