### ISSUE TITLE
request "Zip" file can be resume download after network interrupted

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#63]
currently I'm facing network failure in busy hour, it is easily disconnecting from HFS server. and "zip" file has no resume download feature after connection lost , it's a torture when lost connection on downloading huge size files and can not continue from where the files was downloaded😭.
thank you!

**Comment by dzw13579** [comment]
just have a second thought, could you add a new feature that make the huge file to separate? maybe add a option that if "zip" file size is reach a limit (maybe 2G or something), then HFS will sepatated the file into several files automatically?

**Comment by rejetto** [comment]
i probably never tested resume on zip.
I want to make it possible, for sure.
I will let you know.

**Comment by rejetto** [comment]
ok, I added support for resume. 
I made my tests and it seems ok.
Can I give you a preview version so you can tell me if it is ok for you?
If yes, tell me if you use windows/exe or other versions.
