### ISSUE TITLE
Bypass Browser version restriction

### ISSUE THREAD

**Issue by elpoolet** [rejetto/hfs#630]
Hello
First of all, many thanks for your GREAT HFS !!!!
I use it to serve files located on a rented server, and to to download it directly at home.
The fact is that I use the DownThemAll plugin in Firefox.
But I have to use an old version supporting "multi threading".

In version 2.4rc4, it worked like a charm, but this version is vulnerable.
I switched to new version 0.52.9
It's installed on Windows 2016 server

My Firefox version is 52.3.0 (portable ESR version)
Is there a way to bypass the error message "Please use a newer browser" ? like an hidden option in the config file ?

Thanks again !

**Comment by rejetto** [comment]
hey, this is happening because hfs failed to early-detect that your browser won't full interface, otherwise you would have switched to basic interface, that you can manually trigger by appending `?get=basic` to the URL. You may not like what you will see 😬.
i see that i had included firefox up to 39, but i actually have to include up to 59.
this is because of a feature called "module", introduced in v60.
i will give a second look if i can do something to not require this.

so, you use firefox 52 as a choice for your browsing on the internet?
it's not just servers that can be violated when outdated.
https://www.mozilla.org/en-US/security/advisories/

**Comment by rejetto** [comment]
i've worked a bit, and next version will provide a better message to old browsers, that includes a link to the basic interface

**Comment by elpoolet** [comment]
Hi Massimo

Wonderful answer !
Be assured I don't use a such old browser for my browsing.
I use Brave or Chrome for my all-day browsing.
But I use this old version of Firefox only to download my files on my
server, since this is one of the last version supporting the DownThemAll
add-on able to download one file with multiple parts.

Again, many thanks, I'll try to get the basic interface.

Have a nice day.



Le sam. 15 juin 2024, 05:55, Massimo Melina ***@***.***> a
écrit :

**Comment by rejetto** [comment]
cool!
in the meantime, i'm making progress on extending support to firefox 52 without recurring to the "basic"

**Comment by elpoolet** [comment]
Hi.

Just a sec.
I added ?get=basic" at the end of the URL and nothing changed.

My full URL is : <masked>
But I always get the message :  "Please use a newer browser".
Do you have any advice ?

In order to test with Firefox 52, you can use this portable version :
https://portableapps.com/apps/internet/firefox-portable-legacy-52

Have a nice day

--------------
Laurent VOUDON


Le sam. 15 juin 2024 à 07:16, Massimo Melina ***@***.***> a
écrit :

**Comment by rejetto** [comment]
I'm not home, but I guess that feature may require version 0.53

**Comment by elpoolet** [comment]
Hello Massimo

I tried with version 0.59.0-rc12, and it shows me the landing page.
But as soon as I try to login an error is thrown :

AbortController is not defined

The "access-error.log" only shows a 404 error for "/favicon.ico" file.
The "acces.log" shows the landing page log : "GET
/~/api/get_file_list?uri=%2F HTTP/1.1" 200 127 "{}"

Thanks for your help

--------------
Laurent VOUDON


Le sam. 15 juin 2024 à 10:05, Massimo Melina ***@***.***> a
écrit :

**Comment by rejetto** [comment]
you mean with firefox 52?
it's right, i said i'm working on it, so latest version doesn't include "that" yet.

well, firefox up to 39 would present you with the basic interface, automatically.
later versions will show you the fancy interface but won't work, up to some number. (unless you try ?get=basic)
i'm working to give you the fancy interface, working. i should be close.
i also fixed some malfunctioning with the ?get=basic .

i don't know what OS are you on, but this is a preview, if you care about it
[hfs-windows.zip](https://github.com/user-attachments/files/15893483/hfs-windows.zip)

**Comment by elpoolet** [comment]
Yes Massimo.
Its perfect.
I'll wait till then.

Many thanks again

Le mar. 18 juin 2024, 18:46, Massimo Melina ***@***.***> a
écrit :

**Comment by rejetto** [comment]
update published
https://github.com/rejetto/hfs/releases/tag/v0.53.0-rc13

any feedback appreciated

**Comment by elpoolet** [comment]
Hi Massimo

I got a good news and a bad one.
The good news is : it works !
The bad news is : it works only if you don't have to login.
It seems login isn't supported.
But my password includes some "special characters" (french accents letters).
I tried with one not containing such characters and it works.
Any Idea, I can also open a new issue...

Again : Thanks for all your help

--------------
Laurent VOUDON


Le mer. 19 juin 2024 à 11:04, Massimo Melina ***@***.***> a
écrit :

**Comment by rejetto** [comment]
thanks for reporting!
problem fixed in next release.

**Comment by elpoolet** [comment]
My pleasure !
Wonderful !

--------------
Laurent VOUDON


Le jeu. 20 juin 2024 à 12:35, Massimo Melina ***@***.***> a
écrit :

**Comment by rejetto** [comment]
you can now update to 0.53.0-rc14

**Comment by elpoolet** [comment]
Great job Massimo !!!
Works like a charm !
