### ISSUE TITLE
Folder upload is not working properly

### ISSUE THREAD

**Issue by killersolyom** [rejetto/hfs#631]
I can't upload folders on the latest version. The upload process skips folders and only uploads files.

Steps to reproduce:
1. Select Pick folder
![image](https://github.com/rejetto/hfs/assets/44471935/9cb27969-8fb3-4124-abc7-9f4175ffb39e)

2. Choose a folder on your computer. In my case the selected folder has 2 subfolders, and each of them contains an image.
![image](https://github.com/rejetto/hfs/assets/44471935/344022d4-00d8-432a-b5c5-5c3cb58182d8)

3. Upload.

Result: All files are uploaded, but folders are skipped.

![image](https://github.com/rejetto/hfs/assets/44471935/9300c7ad-e346-4ae8-abef-acb2bb4e2f41)

![image](https://github.com/rejetto/hfs/assets/44471935/378c5d93-3f5a-4262-91ea-fa713754bfbd)

**Comment by killersolyom** [comment]
Thank you @rejetto

**Comment by rejetto** [comment]
fixed in https://github.com/rejetto/hfs/releases/tag/v0.53.0-rc13
