### ISSUE TITLE
Download speed slow behind nginx

### ISSUE THREAD

**Issue by yurixahri** [rejetto/hfs#634]
I was testing my internet speed after doing some RAID setup. The local transfer speed is 2.5Gbps, Lan speed is 1Gbps, but downloading  files behind nginx only get around ~ 22MB/s. I tried to down via local ip and the speed got back to ~ 100MB/s. I'm not familiar with reverse proxy that much, can you help me solve this problem? 
![image](https://github.com/rejetto/hfs/assets/111081318/6f474386-135b-41e8-a002-101b63f35c63)

**Comment by rejetto** [comment]
i doubt nginx is the problem, as it's known to be fast.
something else must be affecting you "after it".
but this is not an hfs issue, so i'm moving you to "discussions".
