### ISSUE TITLE
Zipped folder with nonstandard encoding

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#64]
**Describe the bug**
I have a bug for files with names in a non-standard encoding if such a directory is downloaded through an archive. In this case, in the example, the OS encoding is Russian, after unpacking the archive it turns into a mess.

**Screenshots**
https://share.dvor-net.ptz.ru/Z4ZEnuNj2J.png

**Environment (please complete the following information):**
 - OS: windows 10 21H2 Pro
 - Browser: last Maxthon 6 (Chromium)
 - Archiver: WinRar 6.02 x64

**Comment by rejetto** [comment]
thanks for reporting, I've fixed the problem. Stay tuned for next release!
