### ISSUE TITLE
Preserve folder structure/hierarchy on "Pick folder" uploads.

### ISSUE THREAD

**Issue by bouncytorch** [rejetto/hfs#645]
**Problem:**
Currently on "Pick folder" uploads the uploader doesn't preserve folder structure, it just dumps files into the folder you're uploading into. For example, here are the files I'm uploading:
![654  chrome  (21 Friday 21 39 11)](https://github.com/rejetto/hfs/assets/98487235/1dc8d017-c2a0-41a5-acde-96ceb3517569)
And this is how they end up in the folder:
![656  chrome  (21 Friday 21 42 51)](https://github.com/rejetto/hfs/assets/98487235/79954063-9e32-4664-b557-625437469239)

**Solution:**
For front-end, add a toggle, f.e. "Preserve folder structure", so then the uploader will create all the necessary folders and put all files in the right spot.

**Comment by bouncytorch** [comment]
I don't know whether I downloaded the wrong zip or didn't overwrite the previous HFS version, but I updated from admin panel to 0.53.0-rc14 (even though I'm pretty sure I downloaded the right zip). Anywho, this is a duplicate of #631, my bad (although it wasn't ever proposed to make such a feature a toggle).

**Comment by rejetto** [comment]
yes, it was a bug that was just fixed
