### ISSUE TITLE
Adding files or browsing issue

### ISSUE THREAD

**Issue by POPIT-SOLUTIONS** [rejetto/hfs#648]
From the admin panel when we add folders from disk or we browse files for some plugins it gets stuck most of the time , some times show network error inside the add window , sometimes take too long . also the user panels also get freeze if we refresh of switch subfolders while we working with add files or browsing files form admin panel.

**Comment by rejetto** [comment]
are you accessing admin panel on "localhost" ?

**Comment by POPIT-SOLUTIONS** [comment]
In both cases that is via localhost and via lan. i had the same issue

**Comment by rejetto** [comment]
i have no clue on what is causing your problem.
you are the first one to report it, so it is something specific to your configuration.
i can give a look at it if you click on admin-panel > options > edit config > copy excluding password
and paste here

**Comment by POPIT-SOLUTIONS** [comment]
```yaml
version: 0.53.0-rc14
accounts:
  pmwadmin:
    disable_password_change: true
    admin: true
  pmwuser:
    disable_password_change: true
title: POPIT CLOUD
vfs:
  children:
    - source: E:\POPIT CLOUD\ICONS
      name: ICON
      can_see:
        - pmwadmin
      can_read: true
      can_list:
        - pmwadmin
      can_upload: false
      can_delete: false
      can_archive: true
    - source: C:\Users\IT\Downloads\Telegram Desktop
      name: Telegram
      can_see: can_read
      can_read:
        - pmwadmin
      can_list: can_read
      can_upload: can_read
      can_delete: can_read
      can_archive: can_read
    - source: E:\PG APPS - Syncthing
      name: PG APPS
      can_read: "*"
      children: []
    - source: E:\01 OS
      can_read: "*"
    - source: E:\02 SOFTWARES\BASIC SOFTWARES
      can_read: "*"
      children: []
  can_see: "*"
  can_list: "*"
  can_upload:
    - pmwadmin
cert: C:\Users\IT\Downloads\SSL POPULARGROUP.IN\STAR.populargroup.in.pem
private_key: C:\Users\IT\Downloads\SSL POPULARGROUP.IN\STAR.populargroup.in_key.pem
tile_size: 4
enable_plugins:
  - antibrute
  - show-any
  - sharp
  - file-icons
  - thumbnails
  - mark-news
plugins_config:
  file-icons:
    folders: E:\POPIT CLOUD\ICONS\folder.png
    icons:
      - ext: txt
        iconFile: E:\POPIT CLOUD\ICONS\note.png
      - ext: pdf
        iconFile: E:\POPIT CLOUD\ICONS\pdf.png
      - ext: msi
        iconFile: E:\POPIT CLOUD\ICONS\tools.png
      - ext: dll
        iconFile: E:\POPIT CLOUD\ICONS\dll.png
      - ext: mp3
        iconFile: E:\POPIT CLOUD\ICONS\mp3.png
      - ext: zip|rar|7z
        iconFile: E:\POPIT CLOUD\ICONS\zip.png
      - ext: exe
        iconFile: E:\POPIT CLOUD\ICONS\settings.png
  mark-news:
    days: 3
    html: '<b><style="color: Tomato;">✳︎ NEW</b> &nbsp;'
  thumbnails:
    videos: true
https_port: 7777
favicon: E:\POPIT CLOUD\ICONS\logo_sh_l.png
base_url: https://remotely.populargroup.in

**Comment by rejetto** [comment]
1. what do you mean by "we browse files for some plugins" ?
2. is perhaps E: a network drive?
3. can you record a video of your problem?

**Comment by POPIT-SOLUTIONS** [comment]
1. Incase if i need to browse a icon file from my pc and assign to a extension  from   plugin like "file-icons".
2. I am confirming that E: is not a network drive but shared and also same issue there even with accessing root and all other drives
3. sure i will share you a video ,

**Comment by rejetto** [comment]
2. shared ok, but is it phisically on the same computer of C: ?

**Comment by POPIT-SOLUTIONS** [comment]
yes physical drive in the same device which has been shared for others

**Comment by rejetto** [comment]
ok, i will wait for your video, so that i can have a clearer idea

**Comment by POPIT-SOLUTIONS** [comment]
please find the video 
https://remotely.populargroup.in//Video/HFS%20_ISSUE.mp4
user name : user
password  : user

**Comment by rejetto** [comment]
thanks fo your video.
please, open Command Prompt in Windows, and execute "wmic logicaldisk get Size,FreeSpace,Name /format:list"
this is the command the HFS is executing to know the size of disks.
Tell me what result do you see and (more important) how long does this take.

**Comment by POPIT-SOLUTIONS** [comment]
i tried this in 4 of my devices and 2 of them were running hfs windows server . in both those devices which runs hfs server had a huge delay just like in the admin panel and 2 devices without hfs server had an instant response

**Comment by rejetto** [comment]
ok thanks, so the problem is that wmic becomes slow when you have those disconnected network drives.
i will see what i can do about it.
i'd like to create the same myself, but Windows is preventing me from creating the drive unless it is initially reachable.

**Comment by rejetto** [comment]
`wmic logicaldisk get name`
try this command on one of the "slow" machines.
it is not slow, right?

**Comment by rejetto** [comment]
ok, i hope i got a fix for that problem.
Would you mind giving me a feedback about?
to install just go to admin/home, and RIGHT-click on check-for-updates:
https://github.com/user-attachments/files/15959727/hfs-windows.zip

**Comment by POPIT-SOLUTIONS** [comment]
Running the command "wmic logicaldisk get name" provides an immediate response. Additionally, I’ve updated the new file as per your instructions, and it’s working perfectly. Thank you for your excellent support, Rejetto! We look forward to more positive experiences in the future.

**Comment by POPIT-SOLUTIONS** [comment]
Hi , rejetto 

After upgrading to new version login page not loading up thus its unable to acces user interface if we are not logged in previously

**Comment by rejetto** [comment]
i made a mistake while fixing a problem with the login.
i will now give you another zip.

**Comment by rejetto** [comment]
i cannot be sure from your description that your login problem is the same that i fixed,
but please give this a try and let me know:
https://github.com/user-attachments/files/15965216/hfs-windows.zip

**Comment by POPIT-SOLUTIONS** [comment]
Yes, that was the exact issue I had, and it’s resolved now. I will update you if anything arises again. Thank you for your support!

**Comment by rejetto** [comment]
thank you for your feedback!
there was still a small problem with uploads in the version that i just gave you.
i fixed that too and published the update (rc15), for everyone.
