### ISSUE TITLE
Show File icon of its own

### ISSUE THREAD

**Issue by POPIT-SOLUTIONS** [rejetto/hfs#649]
Hi Rejetto,

It would be great to have each file display its own icon on the user side. Many files have distinct icons, and displaying them accordingly would enhance the user experience. While the feature to change icons by extension is useful, displaying each file's specific icon would take it to the next level.

**Comment by rejetto** [comment]
what i can think of, for now, is to expand the file-icons plugin so that you can specify a file instead of just an extension

**Comment by POPIT-SOLUTIONS** [comment]
That might help us up to a limit, but it would be a nice feature if you could display the native icons that correspond to each file.

**Comment by rejetto** [comment]
sorry, if that's what you want, at the moment i cannot make system calls, as it's needed to get the icon of file.
if you would use the thing that i said, i can work on it.

**Comment by POPIT-SOLUTIONS** [comment]
keep that as a suggestion . and please forward with changes in file-icons plugin

**Comment by POPIT-SOLUTIONS** [comment]
yes absolutely

**Comment by rejetto** [comment]
update file-icons plugin, and configure it to your liking

**Comment by jbrown123** [comment]
> the files with their own icon you were talking about, are exe files?

And probably .dll files as well

**Comment by POPIT-SOLUTIONS** [comment]
The new update for the plugin actually works, but some file icons are mismatched with icons from other files

**Comment by rejetto** [comment]
can you show the problem?

**Comment by rejetto** [comment]
i see.
I also noticed that the resolution of the icon is not high.
Anyone is welcometo improve it; the job is done by the script "exicon.ps1" that you find inside the plugin's folder.
In the plugin i use ExtractAssociatedIcon offered by Windows itself, but maybe something better exists.
I'm going to close this here, as this is a problem of the plugin now, and not hfs.
