### ISSUE TITLE
control menu in powershell window reply error

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#65]
HFS version:0.24.0,Windows
when using the help menu In powershell window, most option will reply error like the screenshot below, only "help" and "quit" work ok
![图片](https://user-images.githubusercontent.com/59822418/176379564-e93a5ba5-25f5-48ea-9109-6879f74460ac.png)

**Comment by rejetto** [comment]
i've found out the code i wrote was not compatible with the binary distribution, so i had to make it differently.

https://github.com/rejetto/hfs/releases/tag/v0.24.1
