### ISSUE TITLE
Appending #LOGIN not working in 0.53.0rc14

### ISSUE THREAD

**Issue by anton-polo** [rejetto/hfs#651]
Appending #LOGIN to address will bring up the login dialog

Appending #LOGIN to address - not working in 0.53.0rc14
(in [0.52.9] works correctly)
after clicking on the link http://localhost/#LOGIN - a white window or "Unauthorized" message is displayed

 - OS: Windows 10
 - HFS Version 0.53.0rc14
 - Browser Chrome 126.0.6478.115

![image](https://github.com/rejetto/hfs/assets/45563035/3ed99d95-17be-4a05-bdc0-ada8e10865af)

**Comment by rejetto** [comment]
thanks for reporting!
i made a quick test with 0.52, 0.51 and 0.50, and while it shows the dialog, it doesn't go away after i login, so i guess this may have never worked.
possible reason: nobody has ever used this feature, and i did my tests in "dev" mode, which is most of times ok, but not in this case.

**Comment by rejetto** [comment]
i made a fix and it seems to work well for me. Can you tell me if it does for you?
you can install it by going on admin/home and right click on check-for-updates:

https://github.com/user-attachments/files/15953105/hfs-windows.zip

**Comment by anton-polo** [comment]
Thanks a lot, it works now.
