### ISSUE TITLE
When hfs downloads files on the browser, can I choose to download the file to a specified disk location?

### ISSUE THREAD

**Issue by ilanni2460** [rejetto/hfs#653]
When hfs downloads files on the browser, can I choose to download the file to a specified disk location?

The default is to download to the current user's download file. Now I want to specify it to another folder.

**Comment by TEA-Time1** [comment]
You set that in your web browser. For example, here's Microsoft Edge's Downloads settings. To be asked, you would enable **Ask me what to do with each download**.

![image](https://github.com/rejetto/hfs/assets/86643478/b4d4d374-5177-4539-ad99-5f78efaa6cdd)

**Comment by ilanni2460** [comment]
@TEA-Time1 Thank you very much for your reply, but I don't want to change the browser's default download location.

**Comment by rejetto** [comment]
> When hfs downloads files on the browser, can I choose to download the file to a specified disk location?

sorry, that's totally up to the browser, and hfs can do nothing about it.

**Comment by TEA-Time1** [comment]
What rejetto said, plus consider this. You wouldn't want just any website to be able to download just any file to wherever it wants on your drive, would you? If your browser is configured to automatically save downloads to the Downloads folder by default, you can always right click a link and do a save as. Or I believe an Alt+click on a link will also do a save as in most browsers.

**Comment by ilanni2460** [comment]
@rejetto @TEA-Time1 ok,tks.
