### ISSUE TITLE
mark the latest files or folders with "new"

### ISSUE THREAD

**Issue by tzdm** [rejetto/hfs#656]
Hope to add the function: mark the latest files or folders with "new", thank you.

**Comment by POPIT-SOLUTIONS** [comment]
there is an plug-in named "mark-news" for the same function

**Comment by tzdm** [comment]
Thanks, I'll try.&nbsp;



发自我的iPhone


------------------ Original ------------------
From: POPIT-SOLUTIONS ***@***.***&gt;
Date: Fri,Jun 28,2024 2:31 PM
To: rejetto/hfs ***@***.***&gt;
Cc: tzdm ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rejetto/hfs] mark the latest files or folders with "new" (Issue#656)





 
there is an plug-in named "mark-news" for the same function

**Comment by rejetto** [comment]
@POPIT-SOLUTIONS i forgot to say that you don't need to define the "blink" animation, as it is already available in hfs.
So, you need only to keep your first line `<b style="color: tomato; animation: blink 2s linear infinite;">✳︎ NEW</b>`
