### ISSUE TITLE
How to modify the creation time.

### ISSUE THREAD

**Issue by tzdm** [rejetto/hfs#659]
I want to modify the creation time, but now it is gray and cannot be modified. What should I do? Thank you.
![How to modify the creation time](https://github.com/rejetto/hfs/assets/53105287/f03ca162-cd6a-4f9b-8498-157bed37d74e)

**Comment by rejetto** [comment]
hey!
that field is just informative, never meant to edit, as it is not part of HFS' goals.
i think you should use a different tool for that.

**Comment by tzdm** [comment]
Thanks.
