### ISSUE TITLE
bro make hfs over the docker container

### ISSUE THREAD

**Issue by BussyBakks** [rejetto/hfs#666]
@rejetto 
i have access to my friend's CasaOS and want to install hfs in this, but idk how
image:
![image](https://github.com/rejetto/hfs/assets/108082159/8f7d9134-f0ea-409c-9612-ecd3617fb481)

**Comment by BussyBakks** [comment]
tf:V
![image](https://github.com/rejetto/hfs/assets/108082159/111363e0-421f-4d64-a944-1195fde36fee)

**Comment by rejetto** [comment]
@damienzonly may help

**Comment by damienzonly** [comment]
I've been working on it, hfs v53 will come with docker images as well, stay tuned ;)

**Comment by BussyBakks** [comment]
@damienzonly bro 0.53.0 is out :v

**Comment by damienzonly** [comment]
hi @BussyBakks , i officially released v0.53.0 and v0.53.0-arm docker images of HFS, try it out and let me know if you have any issues
https://hub.docker.com/r/rejetto/hfs/tags

**Comment by BussyBakks** [comment]
thats works!
