### ISSUE TITLE
Cannot access through one of 2 ips

### ISSUE THREAD

**Issue by syehoonkim** [rejetto/hfs#667]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  - No

**To Reproduce**
1. Make sure the computer hfs installed have 2 NICs
 - One IP is my private network's IP, and the other IP is of the network connected to internet via a router.
2. Make sure you can access via any interfaces.

**Describe the bug**
I only can access hfs from internet, and I cannot access in the private network.
I have already checked that a http server by python works well. So I don't think this problem comes from my environment.

**Expected behavior**
I expect to be able to access hfs from internet and in the private network both.

**Environment (please complete the following information):**
 - OS: Windows 10
 - HFS Version: 0.53.0-rc16
 - Browser: All browsers

**Comment by rejetto** [comment]
please report the content of the hfs console

**Comment by syehoonkim** [comment]
Hello,
I found that when I set "When country cannot be determined" to Allow, the problem disappers.
I am using 10.10.*.* as my private network's IPs.
Local IPs should be ignored on the Geo IP settings, but it seems not.

**Comment by rejetto** [comment]
it would be, but there was a typo on the 10.* 
thanks for reporting.
fixed in next release.

**Comment by syehoonkim** [comment]
Thank you!!
