### ISSUE TITLE
Feature to adjust dialog backdrop in login page

### ISSUE THREAD

**Issue by POPIT-SOLUTIONS** [rejetto/hfs#672]
can you please add a  Feature to adjust dialog backdrop in login page

**Comment by rejetto** [comment]
you don't need a new option, use css customization for that
https://github.com/rejetto/hfs/wiki/Customization

**Comment by rejetto** [comment]
i just added a video example for your case
https://github.com/rejetto/hfs/wiki/Customization#dev-tools

maybe i should add voice comment

**Comment by POPIT-SOLUTIONS** [comment]
video is not able to play

**Comment by rejetto** [comment]
that's weird. what do you get?

**Comment by POPIT-SOLUTIONS** [comment]
https://github.com/rejetto/hfs/assets/168815722/a90851a4-a407-4f4c-8383-ef37ddf9cfa8

**Comment by rejetto** [comment]
the only thing coming to mind is that it is h265, and your browser may not support it.
i just replaced it with an h264 version.

**Comment by POPIT-SOLUTIONS** [comment]
ok, thankyou
