### ISSUE TITLE
Crash during search for a large number of files.

### ISSUE THREAD

**Issue by MsDming** [rejetto/hfs#678]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  - Check if your problem is caused by your proxy, try without it.
No proxy.

**To Reproduce**
1. Go to index page.
2. Click on search button.
3. Search a series of files using a keyword.
4. Wait for minutes.

**Describe the bug**
The console will make an error and crash after searching for minutes.

**Screenshots**
![捕获](https://github.com/rejetto/hfs/assets/61997590/faafd872-1303-42fd-b050-3436b0439a25)

**Environment (please complete the following information):**
 - OS: Windows10
 - HFS Version: 0.52.6、0.52.10
 - Browser: Edge
 - CPU: Intel Xeon E5-2630 v4
 - Memory: 32GB

**Additional context**
I find that HFS occupies about 4GB memory in the task manager when it crashed.
I manage a large number of files using HFS, this problem maybe related on my files number and computer configuration?

**Comment by rejetto** [comment]
hey,
first: the version i see in your screenshot has an important security problem. Update to 0.52.10 urgently.
Future versions will have automatic check for updates, and warnings for security problems (all optional).
The browser should not be involved in the problem.
In the past I've made tests with a lot of files, like +100k.
Making a similar test today, i see your same problem, so i guess something has changed for the worse.
I'll investigate this.

**Comment by MsDming** [comment]
Thanks for your quickly response!
This is the first issue I've submitted on GitHub, and I look forward to your fix.

**Comment by rejetto** [comment]
yeah, but this is not an easy one, i fear it may take a while :)

**Comment by rejetto** [comment]
so, there is a memory leak during the search.
it is supposed to go away as soon as the serach ends.
version 0.53.0 should mitigate this problem, by using less memory.
if you are lucky, you may even not see the problem anymore.
i'm still working on it for complete solution, tho.

**Comment by rejetto** [comment]
wow, this is tough.
i've already spent many hours on it, and i'm not done yet.

**Comment by MsDming** [comment]
oh, thanks for your updating, i'll try it : )
it's really a tough one.

**Comment by rejetto** [comment]
would you care to confirm the problem is fixed with this version?
[hfs-windows-x64-0.54.0-alpha1.3.zip](https://github.com/user-attachments/files/17085718/hfs-windows-x64-0.54.0-alpha1.3.zip)

i suggest that you enable the new option i just introduced
<img width="219" alt="image" src="https://github.com/user-attachments/assets/d6573ff0-83e9-4f0f-bc66-ee7823b98ca8">
because a search in a big folder structure will be faster

**Comment by rejetto** [comment]
available in 0.54.0-alpha2
