### ISSUE TITLE
allow a user to upload a file?

### ISSUE THREAD

**Issue by asmwarrior** [rejetto/hfs#68]
Hi, I'm a hfs user for a vary long time, mainly I used the Delphi version.

Today, I first tried the Node.js version, works correctly.

One missing feature is that can a user upload a file to the server?
I can't find the option here. 

Thanks.

**Comment by rejetto** [comment]
sorry, upload is to be done
https://github.com/rejetto/hfs/blob/main/todo.md

**Comment by rejetto** [comment]
you got it
https://github.com/rejetto/hfs/releases/tag/v0.27.0
