### ISSUE TITLE
Copy feature

### ISSUE THREAD

**Issue by YallonArs** [rejetto/hfs#680]
Please add `copy_files` API

**Comment by rejetto** [comment]
so you are not asking for the copy function on the frontend, you want to use it programmatically, right?

**Comment by YallonArs** [comment]
yes, I only interact with the server programmatically via API

**Comment by rejetto** [comment]
i'm not planning to add "copy" feature soon, but you are free to do it yourself.
HFS can be expanded by writing your server side code.
https://github.com/rejetto/hfs/wiki/Middlewares

several existing plugins expose their own api this way.
in future version 0.54 i'm going to add a specific api to add apis, to make the process a bit easier and more standardized.

**Comment by rejetto** [comment]
i changed my mind, i will offer the api in next version.

**Comment by rejetto** [comment]
available in 0.54.0-alpha2
