### ISSUE TITLE
[Windows] Integration of IIS as Proxy

### ISSUE THREAD

**Issue by Crushedice** [rejetto/hfs#681]
Greetings,
Im using the File Server since years now, and i'm happy to see
that a new ( and SECURE ) Version is now available.

I am Using Windows server with IIS as the web back end.
It would be nice to see that reflected in the file server,
since for now, it always shows me the monitored downloads as localhost.

**Comment by rejetto** [comment]
hey, that depends on how you configure your proxy.
if you look at hfs admin-panel / home, you may see a link to a guide for proxy configuration. 
Do you?
if you don't see it there, you can click on https://github.com/rejetto/hfs/wiki/Reverse-proxy

**Comment by Crushedice** [comment]
Ah!. 
Man. such a timewaste for me, i tried many things in IIS.
In the end, Just set the "Proxy count" to 1. 
Didnt see this option before. 

All good now. Thank you
