### ISSUE TITLE
port forwardig and listen on internal port not working

### ISSUE THREAD

**Issue by digitalvisuals** [rejetto/hfs#683]
After working several weeks with no problems hfs is topping after the leatest windows 11 update. 
I can start the server itself, but its not responding any more on the the ports used before.  Also the internet connection is not working .
I can't connect de local port also, so there in no possibility to get in the admin section.

I had set the following data in the modem.  internal host 192.168.2.19 and external 86.80.132.170  on port 80.
There was no change to this.  All what |I got is the error the server was time out, and 192.168......give no respons to admin connect

So I ám lost on this point for now.

digitalvisuals Harry

**Comment by digitalvisuals** [comment]
after set back the config bak to working file I can back in the admin section and local in the file sections, but its not possible to get  from the 86.80.132.170 ip  .
![screen_863](https://github.com/user-attachments/assets/6362244b-b8ea-45ea-a014-c8bba2181ef9)

**Comment by rejetto** [comment]
hey!
While HFS provides some functions to assist with port forwarding, it does not actually control this process, as it has very limited authority over it. Only you can (and sometimes neither you can 😄).
Access your admin panel, click "internet", and then "verify", and see what it tells you.

**Comment by digitalvisuals** [comment]
If I do that , I goto this see screenshot;
I have local connection again, but no from internet

Thanks Harry


website: DigitalVisuals <https://digitalvisuals.nl>- Affinity Photo |
Designer.
Discord: @digitalvisuals
Mastodon: @DigitalVisuals


Op ma 15 jul 2024 om 14:26 schreef Massimo Melina ***@***.***

**Comment by rejetto** [comment]
please, read again my instructions
> Access your admin panel, click "internet", and then "verify", and see what it tells you.

it's not possible these steps brings the screenshot you posted

**Comment by digitalvisuals** [comment]
sorry that was the connection from the link.
here the internet connection and result from admin center/internet, in the modem there wass no change after the first install some weeks ago.
![screen_864](https://github.com/user-attachments/assets/85ebe0cd-93b4-4d95-abfb-397ca97e23e0)
![screen_865](https://github.com/user-attachments/assets/a414cdaa-bde8-4ae0-9a46-027ecc2a0cce)

**Comment by rejetto** [comment]
ok, first problem is that you selected the local address as main address (or so it seems).
<img width="214" alt="image" src="https://github.com/user-attachments/assets/2dc07355-3d6d-4f72-bba1-273005364318">

click "change", and then probably your best option is "automatic", if you don't have a domain.
then try again

**Comment by digitalvisuals** [comment]
![screen_866](https://github.com/user-attachments/assets/26fc6ea4-0aca-4625-afc8-159a8c6059af)
result I got this.

**Comment by digitalvisuals** [comment]
fix is not working

**Comment by rejetto** [comment]
fix is available when "upnp" is enabled on your modem/router.
nonetheless it doesn't always work, and in such case you need to manually configure the port forwarding on your modem.
this website tries to help https://portforward.com/

**Comment by digitalvisuals** [comment]
strange at all, it was weeks long working and after windows update I got this problem

**Comment by rejetto** [comment]
anyway, after "fix" fails, you should get a warning with a list of advices, that's actually more or less all i know about it 😄

one of these advices says "There could be a firewall, try configuring or disabling it."
did you consider it?

**Comment by digitalvisuals** [comment]
the port I have forwarded is 192.68.2.19  local it see this port..  My static net ip is 86.80132.170  this was working without errors. 
yesterday I got the problems.

**Comment by digitalvisuals** [comment]
Hi, yes have read everything, i cant change the listing port in the modem,
but not in hfs. It stays to the old ip
If i change the tcp/ucp port from 80 to lets say 7777 or 7776 nothing
works. So I quit for now with this.

Op ma 15 jul. 2024 16:21 schreef Massimo Melina ***@***.***>:

**Comment by rejetto** [comment]
sorry, i don't understand your description of the configuration.
If you need more help, it's best if you post a screenshot of your configuration.
I assume you already tried to disable the firewall of your Windows as advised.

**Comment by digitalvisuals** [comment]
well I'am not the only one on this home network, so \I can't remove the firewall.  Because there is many gaming and streaming  from it.

**Comment by rejetto** [comment]
the point was a test to know if it's the firewall, even temporarily,
and i'm talking about Windows firewall, that affects only your computer, not the whole network.

**Comment by digitalvisuals** [comment]
i don't use the windows firewall ;)

**Comment by rejetto** [comment]
so you disabled Windows Firewall, which comes bundled with Windows, but you may be using another, same advice

**Comment by digitalvisuals** [comment]
oke fix it, is working now, but after set port forwarding it says the ip 192.168.2.19 what is my pc is not working

**Comment by digitalvisuals** [comment]
leatest saterday it was working with the same settings...... ????

**Comment by rejetto** [comment]
i didn't touch your computer, i swear 😄
so, is the problem solved?

**Comment by digitalvisuals** [comment]
no
:(

**Comment by rejetto** [comment]
you said "is working now", so what is working? and what's not?
please provide screenshots, it's clearer

**Comment by digitalvisuals** [comment]
This what it says after fixx It...    Your configured address http://192.168.2.19 doesn't seem to work 😰
still, we are going to test your IP address 🤞

**Comment by digitalvisuals** [comment]
after that :  We couldn't reach your server from the Internet. Try port-forwarding on your router

**Comment by digitalvisuals** [comment]
I send the modem setting forwarding ports.

![screen_870](https://github.com/user-attachments/assets/6d6b6156-38e2-4884-ae51-8740673a7c88)
![screen_871](https://github.com/user-attachments/assets/2af3c453-c327-4d80-bace-1bab6501deda)

**Comment by digitalvisuals** [comment]
The same results with windows defender who is on al the time  my pc was installed to off.

**Comment by rejetto** [comment]
since HFS is trying to use the address "192", it seems you didn't  follow my instructions.

> ok, first problem is that you selected the local address as main address (or so it seems).
<img width="214" alt="image" src="https://github.com/user-attachments/assets/2dc07355-3d6d-4f72-bba1-273005364318">

> click "change", and then probably your best option is "automatic", if you don't have a domain.
then try again

Anyway, even after this necessary fix, i don't expect your problem to be solved.
the configuration of your modem seems correct.
The rule with "UDP" is actually useless and can be deleted. HTTP is TCP only, not UDP. 
Something else is blocking HFS, i cannot know what. Normally it's Windows firewall (also called WIndows Defender Firewall).

**Comment by digitalvisuals** [comment]
I had set it to Off, but also after that it was not working again. So what is changed after windows 11 was updated yesterday I have no idea.  :(

**Comment by digitalvisuals** [comment]
also hfs.exe has public acces in the firewall settings

**Comment by rejetto** [comment]
i'm sorry, i'm out of advice here :(

**Comment by digitalvisuals** [comment]
You have done your best , I thank you for that!

**Comment by digitalvisuals** [comment]
Don't ask me what I have done, but I can acces the server from my website at the static ip. ;) I have set only a another port from 80 to 82

**Comment by rejetto** [comment]
cool! i'm closing this then
