### ISSUE TITLE
files/folders with "\" in the name cannot be interracted with

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#688]
Error when trying to interract with such file:
`Not found: /root/demo/%5Ctest/`
the folder was named `\test`

running this error through a url decoder the output is:
`Not found: /root/demo/\test/`
this is why it doesnt work

**Comment by W-i-n-7** [comment]
https://hdun.org/random/hfs-issue-688.mp4
in this video i first demonstrate that i have proper permissions then the bug

**Comment by rejetto** [comment]
thanks for reporting!
