### ISSUE TITLE
enter a URL without login cause 401 in webpage

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#69]
HFS ver: 0.24.1
error reproduce steps:
0.if logined already, logout first, or simply open a  privacy window in browser;
1.enter a URL without permission;
2.use the login dialog box to login;
3.webpage will show 401 errorcode instead of file list
![image](https://user-images.githubusercontent.com/59822418/179709902-9fb6f8ce-4cd3-4a47-b09f-8a0045a37918.png)

**Comment by rejetto** [comment]
should be solved with 
https://github.com/rejetto/hfs/releases/tag/v0.24.3
LMK
