### ISSUE TITLE
"stop" and "exit" should be aliases of "quit"

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#695]
![img](https://github.com/user-attachments/assets/593c971d-72a5-4de9-96ec-b3683df36add)

**Comment by rejetto** [comment]
ok for exit.
stop doesn't sound good.

**Comment by W-i-n-7** [comment]
minecraft uses stop thats why i listed it as an option 😀

**Comment by rejetto** [comment]
available in 0.54.0-alpha2
