### ISSUE TITLE
index.html is considered as download (max downloads per ip conflict)

### ISSUE THREAD

**Issue by rec32** [rejetto/hfs#697]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
- Cloudflare

**To Reproduce**
0. Set correct number of HTTP proxies
1. Set "Max downloads per IP" to 1
2. Enable "Serve as web-page if index.html is found" for some folder
3. Place some index.html to it
4. Start to download something
5. Visit the folder from before

**Describe the bug**
You will get an error "too many requests" (if not, press ctrl+f5)

**Expected behavior**
Page opens like default ones.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 22H2
 - HFS: 0.53.0
 - Browser: Firefox 128

**Additional context**

**Comment by rejetto** [comment]
right, thanks for reporting!
this should be fixed in next release.

**Comment by rejetto** [comment]
this is fixed in current 0.54.0-alpha
