### ISSUE TITLE
Black screen issue on the Shared Files page

### ISSUE THREAD

**Issue by shuakm** [rejetto/hfs#698]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  - no

**To Reproduce**
1. Go to ''HFS Admin Panel' -» 'Shared Files''
2. Shared files page black screen,Cannot click on any element.

**Describe the bug**
Go to ''HFS Admin Panel' -» 'Shared Files''，Shared files page black screen,Cannot click on any element.
**Expected behavior**
TypeError: Object.hasOwn is not a function
**Screenshots**
![捕获](https://github.com/user-attachments/assets/5054a85c-8fad-41f1-80d1-f54d2269b748)
![捕获1](https://github.com/user-attachments/assets/e519a564-feb3-4a4c-806e-776c873290db)
![捕获2](https://github.com/user-attachments/assets/1c5d9779-96d4-462d-b7b0-725702c14ce2)

**Environment (please complete the following information):**
 - OS: CentOS 8.5 Debian 12.2
 - HFS Version 0.5.29 0.5.30
 - Browser Chrome Edge Firefox

**Additional context**
This situation occurs when creating HFS 5.29 and 5.30 on both CentOS and Debian systems.
This phenomenon occurs when using Chrome, Edge, and Firefox browsers.
It is normal on Windows systems.

**Comment by rejetto** [comment]
thanks for reporting!
the problem should affect chrome up to version 92. Do you have such an old version?

**Comment by rejetto** [comment]
this is fixed in current 0.54.0-alpha
