### ISSUE TITLE
popup after saving a comment is "fullscreen" and not small 

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#699]
this is what i mean

"fullscreen"
![fullscreen](https://github.com/user-attachments/assets/477fdd25-8101-43db-8b96-75cc528909be)
"small"
![small](https://github.com/user-attachments/assets/68cdebd4-164f-40eb-b373-a97f2258cfec)

im not sure if it should be a bug or a feature request

**Comment by rejetto** [comment]
sounds ok

**Comment by rejetto** [comment]
in latest 0.54
