### ISSUE TITLE
"select all" box stays checked after deleting files

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#700]
![1](https://github.com/user-attachments/assets/68c8e6bc-1aa2-47a6-b135-b12fef5c4ab6)
![2](https://github.com/user-attachments/assets/cd1b6ecf-05c8-42a8-a2c9-4360f9c0887b)
![3](https://github.com/user-attachments/assets/3eb4a9f9-139a-4536-a88d-8020eb80778e)
![4](https://github.com/user-attachments/assets/5ac4955b-a5e4-439e-933b-4ee8d46f275c)
![5](https://github.com/user-attachments/assets/e5bc47b0-58eb-4d9a-a064-74f2deba3ed1)
![6](https://github.com/user-attachments/assets/a5c271bb-947b-499f-808e-4645b77d4334)
![7](https://github.com/user-attachments/assets/72dc2163-11ce-45e2-88bf-66b953468a7e)

sorry my obs broke so screenshots it is then

**Comment by W-i-n-7** [comment]
this issue _might_ be elsewhere too but i just noticed it here and thought to report even though its a very minor bug

**Comment by rejetto** [comment]
thanks for reporting!
