### ISSUE TITLE
Linux arm support for rasberrypi and ubuntu vm alternatives

### ISSUE THREAD

**Issue by coff33ninja** [rejetto/hfs#702]
I'm going to keep it as easy as possible in the request this would work awesome if I can run this on my rasberry/ubuntu arm servers much better as using cockpit in terms of the file sharing and ftp services out there. I have been using 2.4 on windows for a few years and always thaught that it was the end of the road till I doomscrolled and random searches.

**Comment by rejetto** [comment]
Find instructions for "other systems" in the readme
https://github.com/rejetto/hfs#other-systems
