### ISSUE TITLE
Prevent Windows from sleep

### ISSUE THREAD

**Issue by Jackboy001** [rejetto/hfs#703]
**Is your feature request related to a problem? Please describe.**
I was annoying about when i have to access my files outside, the computer goes into sleep automatically sometimes. Yes, sometimes. It will keeps awake for a week if my computer's mood is good, or goes into sleep right after few hours. I've set every sleep or hibernate settings to NEVER in control panel -> power options, even done some group policy settings i googled from internet, but still. Maybe the computer is really tired so want to get some sleep, huh?

Edition	Windows 11 Pro
Version	23H2
Installed on	‎2023/‎11/‎23
OS build	22631.2506
Experience	Windows Feature Experience Pack 1000.22677.1000.0

**Describe the solution you'd like**
Hope there will be an option to prevent computer from sleep in control panel. And, since i running hfs on a laptop (i seldom bring it out but sometimes sill need), hope there will be an option about "only keep awake when plugged in".

**Describe alternatives you've considered**
currently no

**Additional context**
Since ive modded some settings in group policy so its grayed out. Its set to never.
<img width="454" alt="image" src="https://github.com/user-attachments/assets/a64e2145-a2ca-430c-bbde-698b2a0f9155">

**Comment by rejetto** [comment]
I don't think HFS should solve this system problem.
You may find other software doing it
https://learn.microsoft.com/en-us/windows/powertoys/awake
