### ISSUE TITLE
Info regarding remote access possibilities without public ip exposure 

### ISSUE THREAD

**Issue by lostb053** [rejetto/hfs#707]
Basically, for added security, it would be great to see an option for let's say, uploading some file/certificate as a means of authentication alongside password.

**Describe the solution you'd like**
could be a txt file with random text/characters, to be checked after given a correct password.

**Describe alternatives you've considered**
maybe something along totp function. It follows a specific algorithm anyways, just have a shared key between both server and client

**Additional context**
I'm really grateful for this free app and it's really great to be honest. I want to use it as remote access, so just wish to see some extra layers of security for peace of mind. Additionally it would be great to see the app simply running in background rather than having to keep terminal open, but that's still something I can live with 👌.

**Comment by rejetto** [comment]
HFS already supports certificate for https.
It is able to generate the certificate internally, and renew it when it's time.
Admin-panel > internet > https

is that what you need?

running "in background" is called "service".
That is something you can achieve but it depends on your operating system.
Find instructions for running as a service in the README file (homepage of this repository).
Instructions for Windows still need improvements.

**Comment by lostb053** [comment]
https is encryption, but not exactly an extra gate you need to clear B4 access? So like, anyone can access https websites, but what I mean is more of authentication certificate rather than encryption certificate. (To be honest, I might be wrong here, as I can't get the thing to work). Like Multi-Factor Authentication. Totp could work as well. I saw the letsencrypt integration, and I can't get it to work so I left it at self signed. I lack the know-how here else I actually already saw the interface where I could add it myself using code and stuff (idk programming).

I'll check out the readme. Thanks 🙏.

**Comment by rejetto** [comment]
standard login in HFS is protected by SRP https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol
MFA is not currently available.
if certificate generation failed for you, you can report the error message.

**Comment by lostb053** [comment]
![Screenshot 2024-08-18 143511](https://github.com/user-attachments/assets/d307e68a-3871-40f0-88d0-66ccb0840cb1)

![Screenshot 2024-08-18 143522](https://github.com/user-attachments/assets/a544cfb9-34d8-4e2c-bb7e-e4f2cb6a26c0)



![Screenshot 2024-08-18 143705](https://github.com/user-attachments/assets/39b6a003-2216-47ad-9a52-fd0973f1dde5)

![Screenshot 2024-08-18 143731](https://github.com/user-attachments/assets/b0a7e942-a73f-4340-a89a-ff3869768812)

![Screenshot 2024-08-18 143651](https://github.com/user-attachments/assets/7c78b3a9-b8fe-4d9f-9abf-babadee0027a)

Do i need more info? I'm sorry I'm not sure what am i missing here
~~I don't think i have public IP from my ISP~~ or atleast can't seem to get it work (i do have public IPv4)

**Comment by rejetto** [comment]
the message says that your domain points to 192.* which is the local IP.
This is wrong, the domain must point to your public ip.

letsencrypt needs you to be reachable on port 80 of your public ip.
i suggest you to use the "verify" in the "internet" page to be sure that you are reachable, as it is a necessary condition.

**Comment by lostb053** [comment]
yeah... that's the problem i have. I am not sure how to achieve that. can't get it to work on my public ip.

**Comment by rejetto** [comment]
your domain, that ends with ddns.net, is a service offered by noip.com and you can refer to them for help on configuration.
Basically, you have to login to their website, and from there you'll be able to change the ip.
For now, do it manually, then you can see to get it automatic.

**Comment by lostb053** [comment]
i already tried setting the ip there. i looked around n found that my ISP doesn't give IPv4 exposures. only IPv6 for home connections

**Comment by rejetto** [comment]
then be sure to have an ipv6 domain on noip

<img width="349" alt="image" src="https://github.com/user-attachments/assets/af26132d-8fd0-4be9-b85d-d6cfa448d6ab">

**Comment by lostb053** [comment]
Oh
Lemme give it a try

**Comment by lostb053** [comment]
Can't get it to work after all. I think I'll try something else instead. But within network it's still a great application. I usually hate using phone link and such, this will prove to be pretty handy. Sadly can't set it up for remote access

**Comment by rejetto** [comment]
i see.
Letsencrypt won't generate the certificate without the domain working, but even if it did, it would be useless.
HFS (as any other web server that i know) doesn't manage your domain, so i cannot help you with it.

**Comment by lostb053** [comment]
Yes, thx for your time regardless :)

**Comment by lostb053** [comment]
Hey @rejetto, idk if it helps or has been updated somewhere else already, for remote access, one could use tailscale (free service) or NordVPN meshnet (I pay for the vpn).

As such, I suggest mentioning it in Readme. Might help many others.

**Comment by lostb053** [comment]
https://meshnet.nordvpn.com/how-to/remote-files-media-access/http-file-server

It helps establish remote access, and secure assuming nordvpn's servers are.
Tailscale on other hand has a similar process, and probably even allows https certificate generation (I have to try it yet with either services to be honest)

**Comment by rejetto** [comment]
so, you suggest using a VPN service with HFS for enhanced security, right?
sound ok, i will mention this at https://github.com/rejetto/hfs/wiki/Security

**Comment by rejetto** [comment]
i guess this is done

**Comment by lostb053** [comment]
It was more about secure remote access even without https. Which can be risky. So tunneling between devices like this (ofc with a proper setup and uncompromised devices) would make you less vulnerable than using ddns without https.
But yes, works ig

PS: My isp wouldn't allow ip exposure, so couldn't get https certificate.
