### ISSUE TITLE
remove system integration

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [rejetto/hfs#708]
**Is your feature request related to a problem? Please describe.**
cant remove system integration even after removing hfs

**Describe the solution you'd like**
a button to remove system integration

**Describe alternatives you've considered**

**Additional context**

**Comment by rejetto** [comment]
the button is already there. 
As soon as you click to do the system integration, it becomes "remove integration"
<img width="575" alt="image" src="https://github.com/user-attachments/assets/d997d45f-3dcd-4959-9f9f-3dd49257b89b">

**Comment by abdelaziz-mahdy** [comment]
oh thank you i didnt see it
