### ISSUE TITLE
Plugins not loading after update

### ISSUE THREAD

**Issue by redtrillix** [rejetto/hfs#72]
**Describe the bug**
The plugins aren't loading in the Admin interface after updating to [v0.26.1](https://github.com/rejetto/hfs/releases/tag/v0.26.1)

**To Reproduce**
1. Download and extract updated version to file location.
2. Run the `hfs.exe` executable.
3. Open the Admin Interface.
4. Go to Plugins menu.
5. Under "Installed" active plugins show up, and some are also showing up as not installed under "Search Online".

**Expected behavior**
A list of active/enabled plugins in the Admin interface.

**Screenshots**
![Screenshot](https://i.imgur.com/W9anUqb.png?raw=true)
![Screenshot](https://i.imgur.com/ehYwnG0.png?raw=true)
![Screenshot](https://i.imgur.com/asPpIXB.png?raw=true)
![Screenshot](https://i.imgur.com/zSLg4Tn.png?raw=true)

**Environment (please complete the following information):**
__Installed on:__
 - OS: Windows Server 2019

__Accessed on:__
 - OS: Windows 11 22H2
 - Browser Brave Browser Nightly
 - Version: Version 1.45.5  Chromium: 105.0.5195.52 (Official Build) nightly (64-bit)

**Comment by rejetto** [comment]
sorry for the trouble, give a look at this
https://github.com/rejetto/hfs/releases/tag/v0.26.2

**Comment by TheShadowAngel** [comment]
@rejetto, have a nice day!

Updated [v0.26.1](https://github.com/rejetto/hfs/releases/tag/v0.26.1) to [v0.26.2](https://github.com/rejetto/hfs/releases/tag/v0.26.2), Plugins -> Installed : list is empty 🤷‍♂
** [v0.26.0](https://github.com/rejetto/hfs/releases/tag/v0.26.0) work fine 😉

**Comment by rejetto** [comment]
for a while I didn't have a Windows computer to make tests.
Now I do. I will work on it asap.

**Comment by rejetto** [comment]
ok, this was finally tested on Windows. Sorry for the mess
https://github.com/rejetto/hfs/releases/tag/v0.26.3

**Comment by TheShadowAngel** [comment]
Thanks!
Now it's working 👍
