### ISSUE TITLE
Files with a # symbol, characters removed after the #.

### ISSUE THREAD

**Issue by NSBSD-InfoTech** [rejetto/hfs#722]
**BEFORE**

- Are you using a reverse-proxy, like nginx? No
  - Check if your problem is caused by your proxy, try without it.

**To Reproduce**
1. Uploaded a pdf file with file name PO#12345.pdf

**Describe the bug**
The file will upload successfully, but the characters after the # will be removed. ex. PO#

**Expected behavior**
Because of this bug, anything after # symbol will get cut, even the file extension, the file gets corrupted.  You can rename the file after downloading and include the file extension like .pdf and it will open properly.

The filename should be unchanged after uploading even with # symbol.  

**Screenshots**
Try to provide videos or else screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: macOS Sonoma 14.6
 - HFS Version latest
 - Browser Google chrome

**Additional context**

**Comment by rejetto** [comment]
thanks for reporting!
fixed in next release

**Comment by rejetto** [comment]
this is fixed in current 0.54.0-alpha
