### ISSUE TITLE
Please make the pagination view configurable (if possible)

### ISSUE THREAD

**Issue by killersolyom** [rejetto/hfs#725]
Hi Rejetto!

If more than 100 elements are displayed on a page, a pagination view is displayed at the bottom of the page. Could you please make it configurable? I mean i would like to hide it. I just want a scrollable collection without that view. Is there a possible solution?
Thank you very much!

![screen](https://github.com/user-attachments/assets/5e6e0ec6-2256-4843-b7d7-35ee33cf79c3)

**Comment by rejetto** [comment]
try hiding it with css.
the list will still be scrollable for the full extent, loading more elements as you scroll, until the end.

**Comment by rejetto** [comment]
do you know how to do that?

**Comment by killersolyom** [comment]
Unfortunately i don't know. I know that somehow i have to add a custom style to the custom html code, but I honestly don't know what to add. This solution would be perfect for me if it could be solved.

![image](https://github.com/user-attachments/assets/c10acb29-13e2-4b61-be4b-1700965eff8d)

**Comment by rejetto** [comment]
admin-panel > custom html > section style

add
```css
#paging { display: none }
```

**Comment by killersolyom** [comment]
It works perfectly fine, thank you very much.
