### ISSUE TITLE
Download privilege escape with plugins

### ISSUE THREAD

**Issue by cbr00t** [rejetto/hfs#728]
It is possible to download files/folders with the (can_see) permission that appear in the File List through plugins that perform Show, Preview, Play Media ... etc. operations. This situation allows the (can_download: false) permission to be exceeded.

Only the way to prevent this is (can_see = false) permission.

![img01](https://github.com/user-attachments/assets/b0ed5520-2be9-4117-9751-a63837bca609)

![img02](https://github.com/user-attachments/assets/9b033c31-0db7-4837-947a-5945af9c4901)

**Comment by rejetto** [comment]
but what happens when you click on one of those, like show?

**Comment by cbr00t** [comment]
Sorry, my mistake.
The data it shows is not the file content, it is the HFS Web Page interface again, it just shows HTML information as text.

![img03](https://github.com/user-attachments/assets/4c8fceab-0c6f-4e17-8661-c4ea7d3d8f9d)

**Comment by rejetto** [comment]
ok, but this has brought to my attention that these plugins are not currently able to determine that they fail at getting the file.
I'll take care of it.
