### ISSUE TITLE
Translation to Thai language

### ISSUE THREAD

**Issue by ssoonthorn** [rejetto/hfs#730]
[
[hfs-lang-th.json](https://github.com/user-attachments/files/16940294/hfs-lang-th.json)
](url)

**Comment by rejetto** [comment]
thank you for your contribution!
i will include it in next release.
i noticed you had problems translating some harder lines, so i took the liberty to do them using a program (i can't speak thai). Please tell me if they look good to you
```
        "n_files": "{n} ไฟล์",
        "n_folders": "{n} โฟลเดอร์",
        "filter_count": "{n} ผ่าน",
        "select_count": "{n} เลือก",
```

**Comment by ssoonthorn** [comment]
It looks good.

ในวันที่ พฤ. 12 ก.ย. 2024 เวลา 05:05 Massimo Melina <
***@***.***> เขียนว่า:
