### ISSUE TITLE
Will HFS add the reverse proxy feature?

### ISSUE THREAD

**Issue by fellow99** [rejetto/hfs#731]
HFS is a very good WebServer with a perfect confiurable WebUI.
BUT as a WebServer, it it lack of the reverse proxy feature.
I suggest you add this feature.

**Comment by rejetto** [comment]
it is a nice idea, but i think this is better be done as a plugin

**Comment by rejetto** [comment]
ok, i published a first attempt.
find it on admin-panel / plugins / search online: reverse proxy

i made a simple test and it seems to work, but i'm no expert on this topic so i'm not sure it's doing everything it should.
LMK

**Comment by rejetto** [comment]
did it work for you?

**Comment by fellow99** [comment]
It works. Thank you for adding this feature.
