### ISSUE TITLE
Chat plugin

### ISSUE THREAD

**Issue by cbr00t** [rejetto/hfs#734]
After login or logout, Chat plugin stays in old state unless doing F5 (reload page)

![chat-pluıgin](https://github.com/user-attachments/assets/301eecdd-3f85-4ccf-b91f-98ed3f05a7c5)

**Comment by rejetto** [comment]
hey!
that project is not mine, please open the issue at https://github.com/damienzonly/hfs-chat/issues

and, @damienzonly , you probably should HFS.watchState('username') or something like that
