### ISSUE TITLE
Work on Ubuntu 22.04,Out Put Some Error

### ISSUE THREAD

**Issue by cyxnzb** [rejetto/hfs#74]
I have ran the application on my server in ubuntu 22.04 version.
I use nohup to make the program run in the background.
However, I don't know why, after the program runs for a while, it will automatically crash and will not restart. After I checked the log output, I found some key lines.
**nohup: ignoring input
HFS ~ HTTP File Server - Copyright 2021-2022, Massimo Melina <a@rejetto.com>
License https://www.gnu.org/licenses/gpl-3.0.txt
started 9/6/2022, 4:57:46 PM 
version 0.26.2
build 2022-09-03T21:16:11.000Z
cwd /root/.hfs
config config.yaml
HINT: type "help" for help
using generic lib for crc32
[Error: EBADF: bad file descriptor, read] {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}**

**Comment by rejetto** [comment]
do you have the "debug.log" ?
you may find it in /root/.hfs

**Comment by cyxnzb** [comment]
> do you have the "debug.log" ? you may find it in /root/.hfs

Yeah,i see.
i don't know how to upload it in the github,so i have no choice but attach it here.

**
9/6/2022, 4:46:42 PM: http port 3306 busy: mariadbd
9/6/2022, 4:49:59 PM: insufficient parameters, expected: <key> <value>
9/6/2022, 4:50:04 PM: insufficient parameters, expected: <key>
9/6/2022, 4:50:08 PM: insufficient parameters, expected: <password> [<username>=admin]
9/6/2022, 4:57:46 PM: {"errno":-9,"code":"EBADF","syscall":"read"}
9/6/2022, 5:02:03 PM: {"errno":-9,"code":"EBADF","syscall":"read"}
**

**Comment by rejetto** [comment]
"after a while" is a problem.
I tried running hfs on ubuntu 22.04 with nohup but couldn't reproduce it.
I see 2 options here
- you find a way to make me reproduce the problem at will
- i can produce an experimental fix for you, and you tell me if it works

question: are you using "linux" hfs here, or did you install via npm?

**Comment by cyxnzb** [comment]
> “一段时间后”是一个问题。我尝试在 ubuntu 22.04 上运行 hfs，但无法重现它。我在这里看到2个选项
> 
> * 你找到一种方法让我随意重现问题
> * 我可以为您制作一个实验性修复程序，并且您告诉我它是否有效
> 
> 问题：您是在这里使用“linux”hfs，还是通过npm安装的？

I'm sorry to see your reply now, if memory serves, I should have downloaded the source code directly and used it

**Comment by rejetto** [comment]
maybe you could tell me what exact command you use to launch hfs with nohup
