### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by Gohan472** [rejetto/hfs#745]
**Is your feature request related to a problem? Please describe.**

While HFS works well across Windows, Linux, and macOS, setting up and maintaining it manually on different systems can be cumbersome. Having a consistent deployment method would be more efficient.

**Describe the solution you’d like**

An official Docker container for HFS would greatly simplify deployment, especially for users who run HFS on multiple platforms. 
Docker also allows easy passthrough of underlying storage, making HFS more flexible and attractive as a web file server.

**Comment by Gohan472** [comment]
Following up: I did find docker listed in the wiki. 

https://github.com/rejetto/hfs/wiki/Docker/

**Comment by rejetto** [comment]
well, that page is old.
@damienzonly has been working on hfs for docker

**Comment by rejetto** [comment]
in the meantime have a look at this https://hub.docker.com/repository/docker/rejetto/hfs/

**Comment by Gohan472** [comment]
> in the meantime have a look at this https://hub.docker.com/repository/docker/rejetto/hfs/

Awesome! Thank you!
