### ISSUE TITLE
Editable theme templates

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#75]
It would be cool to be able to modify html/css/js files, which would make it possible to change the appearance of the web interface.

**Comment by rejetto** [comment]
some capabilities are already there, see the theme-example plugin
<img width="285" alt="image" src="https://user-images.githubusercontent.com/1367199/189859644-5420b119-1eaa-41e3-aa32-63d9e9dc39c3.png">

Of course we can discuss it.

I'm not planning to add the old approach, as it has a number of problems.
But someone else is working on [a plugin to offer that](https://github.com/NaitLee/Takeback-HFS-Template), but it didn't release it "officially", so it doesn't appear on plugins/search.
