### ISSUE TITLE
Temporary upload-file causing filesystem and service-related issue

### ISSUE THREAD

**Issue by physicsdolphin** [rejetto/hfs#751]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
NO

**To Reproduce**

1. Upload a large file to a certain location, then manually cancel the transfer before finishing.
2. The file will disappear at set delete time in "delete unfinished uploading", but 'folder menu-get list' still show the temporary file.
3. now check your host server's filesystem, from serverside you'll see corresponding file named hfs$upload-[YOUR FILENAME] is not deleted.
4. You'll find further upload to the same location with the same file is stucked at speed near zero or even not available.
5. The temporary file in 3 cannot be deleted even with SYSTEM or LOCAL SERVICE account permission (tried launch a cmd from processhacker). The only way to remove that is terminating the HFS process, since you cannot get the file's permission without its read permission. Those files might be marked as "to be deleted" thus stucked in NTFS filesystem, blocking further uploading attempt on the same file.

**Describe the bug**

The temporary file created whilst uploading is not correctly handled by HFS.

**Expected behavior**

The temporary file created whilst uploading should be correctly deleted according to settings

**Screenshots**

SETTINGS:
![image](https://github.com/user-attachments/assets/1976fa08-d92c-4302-8ee3-7377ac5da3b1)

![image](https://github.com/user-attachments/assets/c490f998-95f8-4274-a75d-9209612c2239)

SERVER SIDE BEHAVIOR:
<img width="332" alt="image" src="https://github.com/user-attachments/assets/91985009-cc02-4e14-980b-eab53aaeda80">

<img width="515" alt="image" src="https://github.com/user-attachments/assets/f393e94f-f6cd-4219-bbd2-cf224c766e69">

<img width="322" alt="image" src="https://github.com/user-attachments/assets/2276c806-0379-41ff-91cb-69d8e86f1639">

<img width="247" alt="image" src="https://github.com/user-attachments/assets/39c691f3-2ac2-446a-963c-3d62c6012474">

<img width="253" alt="image" src="https://github.com/user-attachments/assets/f61a112a-4c99-4cf3-a5c5-7fbea7c9c2ef">

CLIENT-SIDE BEHAVIOR:
![image](https://github.com/user-attachments/assets/692af04f-5a46-4149-9043-27be6a2ab03b)

![image](https://github.com/user-attachments/assets/2103f0f3-07cb-4bbd-9a5a-c33c60671a2c)

![image](https://github.com/user-attachments/assets/58512b51-28ce-451a-aceb-76671493352d)

**Environment (please complete the following information):**
 - OS: [HFS Server runs on Windows Server 2022 21H2 20348.2655, host can be any version of windows 10/11 with a web browser]
 - HFS Version [tested on 0.53.0 and 0.54.0 alpha2]
 - Browser [tested on chrome and edge]

**Additional context**

Suggestions:

1. give an option to allow user to choose a TEMP directory or use an independent environment variable
2. give an option to store temporary uploading file in server's memory instead of disk drive if the latter choice is causing this instability.
3. change the interaction method with NTFS filesystem to a more robust one.

P.S.
The HFS executable is registered on windows as a service using NSSM 2.24-103-gdee49fc 64-bit 2017-05-16, but makes no difference on this issue compared to directly running it by double-clicking the executable.

**Comment by rejetto** [comment]
you say "manually cancel the transfer".
how?
if I click the button for upload cancellation, I get "1 skipped"
<img width="143" alt="image" src="https://github.com/user-attachments/assets/e7d0aacb-d8f5-46da-9e1c-b6ef69018f0b">

I see in your screenshot it says "1 failed", so I assume you did something different.

**Comment by physicsdolphin** [comment]
The first time when you upload a certain file, you can cancel the upload and skipped the file just as your description.


If you set 10s expiration time for unfinished upload, you'll see this up cancellation: 
![image](https://github.com/user-attachments/assets/33ee6204-5f97-4dd0-8493-30f2cdaa473d)


And after 10s you'll see the temp file is removed in web display
![image](https://github.com/user-attachments/assets/3b45473b-e5a0-4e9a-b726-34f5b6e263d3)


However, if you try to get a list by:
![image](https://github.com/user-attachments/assets/0e1c190d-5659-42a3-baa4-ec576a9f2678)


You'll see the temp file is not properly deleted, thus prohibiting further attempt to re-uploading the same file.
![image](https://github.com/user-attachments/assets/810512d0-f889-4786-b2fa-ea3a2067c6aa)



At server's end I can confirm that the temp file is not properly removed:
![image](https://github.com/user-attachments/assets/1a8c6166-631e-4627-8769-120a9b55de91)


Then you'll have no alternative but to restart the HFS service to completely get rid of those unhandled temp file before being able to upload the same file again, or you'll be stuck like this:

![image](https://github.com/user-attachments/assets/ef81bc1d-a435-4923-aa08-f3f7788a31f6)

After a long zero-speed timeout (Wireshark says TCP zero window which means server refused client's upload since it cannot overwrite that unhandled temp file), you'll see some "failed" hint.

**Comment by rejetto** [comment]
ok, i see this problem is happening only on Windows

**Comment by rejetto** [comment]
of course i made my verification, but would you care to confirm that this version is fixing the problem for you? 
https://github.com/user-attachments/files/17174250/hfs-windows-x64-0.54.0-alpha2.2.zip
to install it you can go Admin-panel > Home
and right-click on the check-for-updates

**Comment by rejetto** [comment]
alpha3 released
