### ISSUE TITLE
Issues/observations related to 0.54.0 alpha2 release

### ISSUE THREAD

**Issue by killersolyom** [rejetto/hfs#754]
I discovered two problems, one minor and one major. I'm using the latest Opera browser and Windows 11.

**1. Regarding the minor issue**
This was valid for several previous versions. In short the problem is that when i open the plugin page in the admin page, the installed plugin list start to appear and then it switches to a black screen.
If i refresh (F5) the page and quickly click on the installed plugins, i can get the page to load. The same applies to the update section. But i can't open the plugin management section in any way. 
This error can be seen in the logs:
![plugin_error](https://github.com/user-attachments/assets/3f4fc8a0-a271-47d1-94a2-ceb22076f8ef)

**2. Regarding the major issue**
On the previous alpha release (0.54.0 alpha1), everything is going well. But i can't upload files on the new alpha release (0.54.0 alpha2).
If i try, it uploads 0 byte files. In practice i can't upload anything except folders.
I see this error message in the console:
![upload_error](https://github.com/user-attachments/assets/2a476c57-cd6e-4880-b55f-e5f149c14599)

Could you please check these errors?
Thank you very much!

**Comment by rejetto** [comment]
1. can you send me the list of your installed plugins? you can see it also in the "plugins" folder that's in the "working directory".
2. yeah, sorry the fix is ready to be shipped with next release. In the meantime you can workaround the problem by using the "split uploads" option. You can set it to 1000MB for example. 

thanks for reporting!

**Comment by killersolyom** [comment]
Installed plugin list:
![image](https://github.com/user-attachments/assets/9ab33da4-4480-478f-821c-ffa5aa3530db)

**Comment by rejetto** [comment]
thanks but this is just enabled plugins, while the list causing the problem is "installed" plugins, so there may be more.

**Comment by killersolyom** [comment]
The config file contains only the enabled plugins. Should I take a print screen of the contents of the plugins folder?

**Comment by rejetto** [comment]
yes, thanks

**Comment by killersolyom** [comment]
![image](https://github.com/user-attachments/assets/6775a96f-45b1-45b2-ab7b-f3ea4f1ce2ac)

**Comment by killersolyom** [comment]
The custom plugins are mostly the same as the original ones, only they have a few modifications to deal only with folders/files or to only work within a certain path.

**Comment by rejetto** [comment]
i think the error is caused by a malformed "repo" information inside the plugin.
i can just imagine that one of those custom plugins have that. Is it possible?
anyway, i made a fix and next version will not crash in such case.

if the changes you made to those plugins can be useful to other people, please consider letting know the author of the plugin that you had such necessity, so the author can consider adding an option for it.

**Comment by killersolyom** [comment]
Thank you very much, that was a very good tip! That was the problem. The repo field was missing from several plugins.

**Comment by rejetto** [comment]
i expect the crash to happen only if the repo is present but malformed, not missing

**Comment by killersolyom** [comment]
I was not 100% sure, so i added a something where it was missing. I also found a few plugins where it was specified, but the format was incorrect. I mean instead of repo = "author/name" it was repo = "something". Now it works properly

**Comment by rejetto** [comment]
alpha3 released

**Comment by killersolyom** [comment]
I installed it. I don't have much time to test today, but unfortunately I found a bug. When i try to log in a warning popup appears.
Now i can upload files but i can't delete them. I think it's because of the error.

![image](https://github.com/user-attachments/assets/fd01bffc-6676-42f3-9c9c-45ecb4c7d2cd)

![image](https://github.com/user-attachments/assets/980b5f58-f66d-4317-ae11-3662ed27e84e)


Sorry for commenting after you closed the topic, I didn't realize it was closed.

**Comment by rejetto** [comment]
you can comment as much as you want, i close just to keep track of solved issues.
but this is a new issue, actually, so please open a new one

**Comment by rejetto** [comment]
anyway, i see the problem now, no real need to open the issue.
i don't know how i could miss it, that's a bummer.
keep you posted

**Comment by rejetto** [comment]
i retired alpha3 because if this ugly bug, will soon publish alpha4 that will include this fix

**Comment by rejetto** [comment]
alpha4 published
