### ISSUE TITLE
Need a reset button

### ISSUE THREAD

**Issue by Avatar-Lion** [rejetto/hfs#757]
Please make a button to reset all settings. In the old version of HFS it was enough to delete .ini file in the program folder, but in the new version there are no additional files. Now the admin panel does not open for me, I did something and now the browser says "forbidden" when trying to open the address http://localhost/~/admin/

I would also like to remove this console window that appears when starting HFS.

**Comment by rejetto** [comment]
what was the ini file is now another file called "config.yaml"
just delete that

**Comment by Avatar-Lion** [comment]
Where is this file located? I only see hfs.exe and a folder "plugins".

**Comment by rejetto** [comment]
when you run hfs.exe the file should be in the same folder.
anyway, when you run HFS, one of the first lines you see in the console is "cwd", and that is where it's saving files.
this is the documentation about it https://github.com/rejetto/hfs?tab=readme-ov-file#configuration

**Comment by Avatar-Lion** [comment]
Yes, thank you very much, I found directory .hfs in the user profile. I deleted it and everything became fine.

**Comment by rejetto** [comment]
what version are you using?

**Comment by Avatar-Lion** [comment]
0.54.0-alpha4

**Comment by rejetto** [comment]
are you running hfs.exe from "program files" folder ?
because you seem to be having the same problem as this other user https://github.com/rejetto/hfs/discussions/758#discussioncomment-10813797

**Comment by Avatar-Lion** [comment]
Yes, in C:\Program Files. My old PC had WinXP and there HFS was also located in C:\Program Files. However, now I have a new PC with Win10.

**Comment by rejetto** [comment]
but in my experiments, if i try to run HFS (previous version) in "program files", it fails to save to same folder
<img width="379" alt="image" src="https://github.com/user-attachments/assets/b1a26af1-1a1a-4e9c-95e6-1b1070495380">

don't you have the same problem?
that's why i'm not saving to program files.

anyway, for next release i'm considering a different strategy: test if i can write, and if i can't i'll switch to users folder.

**Comment by Avatar-Lion** [comment]
When I launch HFS, its window looks like this:
![image](https://github.com/user-attachments/assets/ef688d38-9172-4326-a404-ea48ebe287bb)

**Comment by rejetto** [comment]
in this screenshot you are running the new version, and it's NOT trying to save to "program files", so of course you don't have errors.
in my screenshot i'm showing previous version
