### ISSUE TITLE
problem when starting hfs from command line and launching update from admin panel

### ISSUE THREAD

**Issue by LiveG24** [rejetto/hfs#760]
running on mac
starting hfs from command line with --cwd .

launching update from admin panel
after the download hfs is restarted without --cwd .
so is returned to default config

**Comment by rejetto** [comment]
thanks for reporting!

**Comment by rejetto** [comment]
https://github.com/rejetto/hfs/discussions/759#discussioncomment-10853864
the version i posted there has also this fix

**Comment by LiveG24** [comment]
brilliant ! 
thanks a lot 🙇‍♂️
