### ISSUE TITLE
"Menu--Get List ", Chinese file names and special symbols have encoding confusion issues.

### ISSUE THREAD

**Issue by 8bqDev** [rejetto/hfs#762]
@rejetto Feedback issue：

"Menu--Get list" ，Chinese file names and special symbols have encoding confusion issues (it may be related to UTF-8, but I don't know where to set it).

（Used in Windows, "hfs-windows-x64-0.53.1“）

![Chinese file names have encoding confusion issues](https://github.com/user-attachments/assets/f58b0de1-e7f9-4f52-b874-0c4505cc31ea)

**Comment by rejetto** [comment]
what do you mean by "confusion" ?
what is the problem with that result? those links work correctly, right?
what did you expect?

**Comment by 8bqDev** [comment]
@rejetto 
My expectation is that in the next version, you can fix the issue of garbled file names obtained from 'Menu -- Get List'.

Because if there are many files, the "Get List" function should be very useful. If it's not troublesome, please fix it in the next version. Thank you.

After all, we all hope that New HFS is perfect.    ^_^

**Comment by rejetto** [comment]
I understand that those links are unreadable.
"Get list" feature is not designed for human usage, but for automated tools. 
I'm using a standard function for url encoding, the one of the browser itself, and it decided that unicode characters must be encoded too.
I tried to not encode unicode characters, and it seems to work, but I'm not sure if it's safe for all usages. Maybe it doesn't work with old browsers. I made a test with firefox 40, but found no problem.
I'm open to make a test. I give you this version, will you help me by using it and report problems?
https://github.com/user-attachments/files/17266301/hfs-windows-x64-0.54.0-beta5.1.zip
right-click on the "check for updates" button, and paste this link

**Comment by 8bqDev** [comment]
@rejetto 

I am happy to test, and here is my test feedback:

（I used 'hfs-windows-x64-0.54.0-beta5.1.zip'“）

1. Firstly, I upgraded "Microsoft Edge" to the latest "129.0.2792.79 (official version) (64 bit)".

2. The file name this time includes "Chinese", "Russian", "Korean", and "Japanese"; Special symbols such as "RMB ￥", "Ruble ₽", "USD $", "Euro €", and "Pound ￡" seem to be correctly obtained by "Menu -- Get List".

3. . However, if the file name contains "space", there will be a problem with URL transcoding, resulting in "% 20" encoding.



![If the file name contains 【spaces】 it will be garbled](https://github.com/user-attachments/assets/e37257e6-4183-465c-877c-335c323a845c)

**Comment by TEA-Time1** [comment]
That is completely normal. %20 (not % 20) represents a space in encoded text, because an actual space is also used as parameter separators and such, so %20 is used to represent a space in a string that needs to stay together.

**Comment by rejetto** [comment]
%20 is necessary, it's not a "problem", it's just ugly. A link cannot have a space.

**Comment by 8bqDev** [comment]
@rejetto @TEA-Time1 

I realize that “spaces” and “%20” are necessary in coding and can't really be hidden.
﻿
From a user's visual point of view, this looks strange.
I've done some searching to see if it's possible to add a style attribute such as “white-space: nowrap” (force no line breaks) to the CSS to avoid spaces in the text, and thus spacing, so that spaces in the coding are less visually obvious. (I've encountered cases where the “%20” was hidden when the page displayed spaces; I don't know what method was used to do this (it could have been visual deception using CSS's transparent color or white color), and I forget where I saw it).
﻿
Of course, none of this may be a functionality-impacting issue, just bringing it up for discussion and sharing from the perspective of a more perfect HFS.

**Comment by rejetto** [comment]
the thing you've found is html/css, and it has nothing to do with links.
the content of get-list is not a web page, it is simple text, like a txt file, and has no formatting.

can you tell me what are you using the "get list" for?

**Comment by 8bqDev** [comment]
> %20 is necessary, it's not a "problem", it's just ugly. A link cannot have a space.

In practice, if there is a space in the link, the browser (such as “Microsoft Edge”) it will be automatically converted to add “%20”, I tested the following two ways, are able to open and display the normal “txt” text.

”http://192.168.2.107/Q1/B/0_使用说明★先%20看￥￥.txt“﻿
”http://192.168.2.107/Q1/B/0_使用说明★先 看￥￥.txt“

**Comment by rejetto** [comment]
as you see, the second doesn't work

**Comment by 8bqDev** [comment]
> as you see, the second doesn't work

Forgot to tell you. I'm using a Simplified Chinese OS and a Chinese browser, I've tested multiple browsers, and it opens both ways. (Maybe it has something to do with the system language too)

"http://192.168.2.107/Q1/B/0_使用说明★先%20看￥￥.txt"
"http://192.168.2.107/Q1/B/0_使用说明★先 看￥￥.txt"

**Comment by 8bqDev** [comment]
> the thing you've found is html/css, and it has nothing to do with links. the content of get-list is not a web page, it is simple text, like a txt file, and has no formatting.
> 
> can you tell me what are you using the "get list" for?

I personally use it now, mainly to see what folders and files are in the directory, because after I share it with others, they add many new subfolders and files, with “Get List” it's easy to see at a glance, but of course I don't rule out the possibility of using “Get List “ to do further automatic list use.


Because I am a non-programmer, may not find examples appropriate enough, should these methods will be linked to get the space (%20) encoding conversion will be some help, here will not expand:
1, the replacement function (simple replacement)
2, TypeScript decorator or JavaScript proxy program
3, data preprocessing or caching (precompiled regular expressions)
4, Parallel and asynchronous processing
﻿
You may also be concerned that adding transformations will pose challenges to the efficiency, performance, and stability of your program execution.

But from the perspective of a perfect HFS, it's all worth it. ^_^

**Comment by rejetto** [comment]
> Forgot to tell you. I'm using a Simplified Chinese OS and a Chinese browser, I've tested multiple browsers, and it opens both ways. (Maybe it has something to do with the system language too)

what do you mean by "it opens"? Tell me where and how are you doing your test.
Try to use screenshots or video, as I think there's some misunderstanding going on.

When I look at your post here on github, the second link is broken, this is a screenshot just to be sure we are looking at the same thing:
<img width="423" alt="image" src="https://github.com/user-attachments/assets/8c466562-0718-4e78-b6bd-ff13f03507b1">
you see, it breaks at the space, and that's normal. A valid URL cannot have a space.

**Comment by 8bqDev** [comment]
What I mean is: when I use the link without “%20”, I replace the “%20 position” with “space” and still open the link.
It's like this : http://192.168.2.107/Q1/B/0_使用说明★先 看￥￥.txt
I've noticed that Github seems to treat characters before a space as the end of a link, and characters after a space as regular text.
(This may cause you to misunderstand).


（After “Enter” in the browser, the browser will automatically replace the “space” I used with “%20” as in the picture.）
![AAAAA](https://github.com/user-attachments/assets/3446b63a-1ecb-4c9c-8666-4a1757cf1f0c)

**Comment by rejetto** [comment]
ok, thanks to your screenshot now it's clear what you meant.
what you are doing is to paste the link in the browser.
the browser automatically replaces it with %20 because the space is not valid.
When you try to do the same here on github, it doesn't work.
This same problem will apply to many other places.
"get list" is designed to produce valid links, that always work, not just when you copy & paste in the browser.
 The %20 in the get-list is not a problem, is a necessity. I understand that you don't like it for your usage, but this is not enough to change it, sorry.

**Comment by 8bqDev** [comment]
@rejetto 

I tested “0.56.0” and found that you may have forgotten that “#762” encodes the “unicode characters” in “Links” again, causing the folder names in “Links” to show up as a bunch of encodings.
Because of this, the folder names in the “logs” file also show a bunch of codes.

我测试了“0.56.0”，发现你可能忘记了“#762”再次编码了“Links”中的“unicode字符”，导致“Links”中的"文件夹名称"显示为一堆编码。
因为这个原因，导致“日志”文件中，文件夹名称也是显示一堆编码。
![Image](https://github.com/user-attachments/assets/97caa92b-5c79-4887-9c6e-bf5cfcfbd0fe)

**Comment by rejetto** [comment]
ok you will find that fixed in 0.57

**Comment by 8bqDev** [comment]
@rejetto 

I tested '0.57.0-beta2' and found 2 issues related to 'List'.
我测试了”0.57.0-beta2“，发现与”List“相关的2个问题。


1，In the root directory, after clicking "Get list" on the homepage, it will prompt a blank page with "about: blank # blocked" and no List. Is it because there is no available list for files and folders in the root directory.
在根目录，主页里点击“Get list”后会提示“about:blank#blocked”空白页面，没有List列表。是不是根目录中的文件和文件夹，就是没有可用的列表的。

![Image](https://github.com/user-attachments/assets/e58b0f99-3aaa-4cb5-8d15-5f46cd2c7ac3)


2，Root directory → Folder with a Chinese name → Upload → Copy links，After pasting, the displayed folder path is a bunch of encodings.
根目录---含有中文名称的文件夹---”Upload“---“Copy links”，粘贴后，显示的文件夹路径是一堆编码。

![Image](https://github.com/user-attachments/assets/03f514fc-2341-4b96-98e7-8c28eed020c4)

![Image](https://github.com/user-attachments/assets/9c180025-4666-450d-8781-be5ee5022c85)

**Comment by rejetto** [comment]
thanks for reporting!
both will be fixed in next release.
please when you find new problems, open new issue instead of replying here.
