### ISSUE TITLE
Perhaps make "wait for loading" screen dark

### ISSUE THREAD

**Issue by rec32** [rejetto/hfs#764]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when "Wait for loading or use basic interface now" flashbangs me, even for a short while. 

**Describe the solution you'd like**
#000000 for background, #999999 for text, as in usual interface.

**Describe alternatives you've considered**
You can make it only for "wait for loading" screen, not for whole basic interface.

**Additional context**
bottom text

**Comment by rejetto** [comment]
i hear you brother.
you'll get it on next 0.54

**Comment by 1dNDN** [comment]
Better use something like #373737 or #111111 for background and maybe #f4f4f4 for text. It looks really better than #000

**Comment by rejetto** [comment]
> Better use something like #373737 or #111111 for background and maybe #f4f4f4 for text. It looks really better than #000

the loading page color must match the default theme, 
and currently the default dark theme in hfs uses #000

**Comment by rejetto** [comment]
available in latest 0.54
