### ISSUE TITLE
“get list folder “ does not display subdirectories and etc

### ISSUE THREAD

**Issue by yo8z6gv** [rejetto/hfs#765]
in version 2.3 when requesting a list of files the full structure was loaded
i.e.
...
directory/directory/directory/file
directory/directory/file
directory/file
file

but here only
directory/
file

and the rest of the levels do not load, even if the display option is “See this item in the list” “any one”.

**Comment by rejetto** [comment]
This is possible but not the default behavior.
Just append `&depth=*` to the URL.
More details at https://github.com/rejetto/hfs/wiki/Get%E2%80%90list

**Comment by yo8z6gv** [comment]
How do I change this parameter to default? if custom.html doesn't exist

--
ps
and there are three types of 404 errors for some reason
template
/~/plugins

catalog match
/~/plugins/1
Not Found will already write

/~/frontend/
inside the style will be written in red 
Not found

**Comment by rejetto** [comment]
i wrote instructions for you at https://github.com/rejetto/hfs/wiki/Customization#make-get-list-recursive

i didn't understand the errors you are talking about, but please open another issue. Keep issues separated

**Comment by yo8z6gv** [comment]
why the “get list” button does not inherit the protocol of the main site?
i.e. I open as https, but when I click “get list”, the list has http links? (inside)

**Comment by SanokKule** [comment]
It uses `Main address` you set on the `Internet` page in admin panel

**Comment by yo8z6gv** [comment]
> It uses `Main address` you set on the `Internet` page in admin panel

and if
cloudflared tunnel --url http://localhost:80
?

**Comment by yo8z6gv** [comment]
> It uses `Main address` you set on the `Internet` page in admin panel

it only worked with the domain. from 
cloudflared tunnel --url http://localhost:80
as an example
/\ but in that case the admin panel is available to everyone -_-

the list is still made by http
i.e. there is no dependence on the link from which the request is coming from

---
I have two network connections.
two ip addresses and two of each
500 and 700 speeds mBIT/s

I do not have a master address. If one network lacks speed and the download supports fragments from different addresses (open), then the summation of speeds up to 1200 mbps, which means 120 mb / s, is activated.

**Comment by SanokKule** [comment]
> but in that case the admin panel is available to everyone -_-

I don't quite understand what you mean here, you can just disable unprotected access on localhost?
![image](https://github.com/user-attachments/assets/f6e2f901-1d1e-420d-a622-ec5f5b16e8cc)


`Main address` only affects the links that are created by hfs to be copied by system integration, in the `Get list` button and `Verify` button in internet page.
It doesn't allow or disallow admin panel and is not related to that.

https://github.com/rejetto/hfs/blob/7554dac44ffc9d792c0a0e1927bb96d4b6666ab6/config.md?plain=1#L93

**Comment by rejetto** [comment]
i think he is saying that if he configures the proxy to go to localhost, then "other people" is considered localhost and they can access admin-panel.

When you start using an http proxy, if you visit HFS admin/home you'll get a warning that you are using a proxy and you need to configure it. It's easy as it's just a number: if you use 1 proxy, you configure "1" in hfs.

I don't know this "cloudflared tunnel", if it's an http proxy. If it's something else, then HFS will not be able to see the real address of the users, and will think they are in localhost. This should be avoided, but if necessary, you can disable the "unprotected admin on localhost" as Sanok has suggested.

This is OT, as the issue in the subject has been resolved, and it would have deserved a different issue/discussion.

**Comment by rejetto** [comment]
for your other problem, please tell us what you have configured here, inside Admin-panel > Internet
<img width="403" alt="image" src="https://github.com/user-attachments/assets/dc552542-b1a7-44c4-b07f-972daa3000a5">

**Comment by rejetto** [comment]
by the way, i had forgot to document that you can pass `prepend=*` to use the same address you use for the request (instead of "main address"). For example here i'm getting localhost
<img width="440" alt="image" src="https://github.com/user-attachments/assets/cb7e8290-3091-4e83-9ae8-e7cb8ca2c45d">
