### ISSUE TITLE
Ordering issues for afterEntryName

### ISSUE THREAD

**Issue by SanokKule** [rejetto/hfs#766]
`afterEntryName` event currently works based on load order and if i add buttons, order depends one when the script was executed/loaded which is not ideal

**Comment by rejetto** [comment]
i can introduce a setOrder function for you to decide if be put at the end, passing a positive number, or at the beginning passing a negative number
```js
HFS.onEvent('afterEntryName', () => {
  return 'A' 
})
HFS.onEvent('afterEntryName', ({ entry }, { setOrder }) => {
  setOrder(-1)
  return 'B'
})
```

with this, B will come before A, even if it's executed after.
[hfs-windows-x64-0.54.0-beta5.4.zip](https://github.com/user-attachments/files/17296510/hfs-windows-x64-0.54.0-beta5.4.zip)
