### ISSUE TITLE
Error messages in the console on Alpha 0.54.0-beta5 and 5.3

### ISSUE THREAD

**Issue by killersolyom** [rejetto/hfs#768]
I noticed that error messages (2 types) appear in the console on the latest beta release.
I think this is related to the new checkbox on the login page.
![image](https://github.com/user-attachments/assets/a8168233-d9f3-4675-8d8c-288635db729d)

Errors:
![error_1](https://github.com/user-attachments/assets/fa410a1c-ca32-4a4e-9789-020e0ad19d0a)

![error_2](https://github.com/user-attachments/assets/a36b5d9e-f21a-4512-9a54-e68f24f8da66)

Sorry for the bad image quality.  Could you check how critical the problem? Or is it possible that there is something wrong only on my side due to a wrong setting?

**Comment by rejetto** [comment]
it's not happening here.
what are the exact steps?

**Comment by killersolyom** [comment]
Unfortunately i don't have steps. The hfs server runs constantly and in the meantime it throws such errors.

**Comment by rejetto** [comment]
looking closer at your screenshots, I understood that it happens when login is attempted not using the web interface, but using "bare" http/https (like curl, for example).
if you know nothing about it, it is possible that those are scanning attempts over the internet, no big deal.
those errors should be harmless,  meaning that the request is not served and the client receives "500 internal server error".
i already fixed the first error, and now trying to reproduce the second.

**Comment by killersolyom** [comment]
Now get this error message on the login screen
![image](https://github.com/user-attachments/assets/7ecda9a2-4479-4ddb-bb4f-0ea1d58de152)

**Comment by rejetto** [comment]
this should be the same as the second one, that i'm working on

**Comment by killersolyom** [comment]
Regarding this "_looking closer at your screenshots, I understood that it happens when login is attempted not using the web interface_"

Yes, i have a pyton script, which runs periodically and retrieves the contents of certain folders from the hfs server. It then generates an index html. I checked it and as python script does not get any error.

(content reco bot)

**Comment by rejetto** [comment]
the second error was caused by antibrute plugin, that i failed to update accordingly to some recent changes of 0.54.
can you confirm this version fix your problems?
right-click on check-for-updates
https://github.com/user-attachments/files/17305569/hfs-windows-x64-0.54.0-beta5.5.zip

**Comment by killersolyom** [comment]
Sure, i will install it and come back later with the answer.

Edit:
The login issue seems to be fixed.

**Comment by killersolyom** [comment]
No new errors since installing beta5.5

![no_error](https://github.com/user-attachments/assets/d1f91b67-bff7-4144-ab37-866a7e612858)

**Comment by rejetto** [comment]
cool!
