### ISSUE TITLE
how i can upload file in hfs ?

### ISSUE THREAD

**Issue by asd0109** [rejetto/hfs#77]
i can`t find some where to upload file in hfs ,please help ~     thank you !

**Comment by rejetto** [comment]
this version doesn't have upload yet. To do...

**Comment by asd0109** [comment]
can you add it ?   upload is a very important function.

**Comment by rejetto** [comment]
that's what I meant with "to do", that I will do it.
When I can, this is not a quick task.

**Comment by asd0109** [comment]
thank you very much !

**Comment by rejetto** [comment]
you got it
https://github.com/rejetto/hfs/releases/tag/v0.27.0

**Comment by asd0109** [comment]
> you got it https://github.com/rejetto/hfs/releases/tag/v0.27.0

perfect !   thank you .
