### ISSUE TITLE
The download-counter plug-in cannot display the number of downloads

### ISSUE THREAD

**Issue by tzdm** [rejetto/hfs#771]
In the new version, the download-counter plug-in seems to be no longer valid. Currently, the number of downloads cannot be displayed. Has anyone encountered such a problem?

**Comment by rejetto** [comment]
i'm looking at it

**Comment by rejetto** [comment]
it's missing the first download, but after that it counts and displays correctly, right?

**Comment by rejetto** [comment]
you can fix it without waiting for next update, by replacing the file `plugins/download-counter/plugin.js` with the one from this zip [plugin.js.zip](https://github.com/user-attachments/files/17326879/plugin.js.zip)

**Comment by tzdm** [comment]
Thanks.



发自我的iPhone


------------------ Original ------------------
From: Massimo Melina ***@***.***&gt;
Date: Thu,Oct 10,2024 6:55 PM
To: rejetto/hfs ***@***.***&gt;
Cc: tzdm ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rejetto/hfs] The download-counter plug-in cannot display thenumber of downloads (Issue #771)





 
you can fix it without waiting for next update, by replacing the file plugins/download-counter/plugin.js with the one from this zip plugin.js.zip

**Comment by rejetto** [comment]
i noticed there was a second bug, that caused to not display the counter inside the file menu, like this
<img width="165" alt="image" src="https://github.com/user-attachments/assets/ecbbf3d5-c81a-4d7c-8bc9-a5df6feed956">

so now the files to be replaced are 2. Let me give you a zip of the whole download-counter folder, it's easier.
[download-counter.zip](https://github.com/user-attachments/files/17326987/download-counter.zip)

**Comment by tzdm** [comment]
Thanks, I'll try it.



发自我的iPhone


------------------ Original ------------------
From: Massimo Melina ***@***.***&gt;
Date: Thu,Oct 10,2024 7:05 PM
To: rejetto/hfs ***@***.***&gt;
Cc: tzdm ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rejetto/hfs] The download-counter plug-in cannot display thenumber of downloads (Issue #771)





 
i noticed there was a second bug, that caused to not display the counter inside the file menu, like this
 image.png (view on web)
 
so now the files to be replaced are 2. Let me give you a zip of the whole download-counter folder, it's easier.
 download-counter.zip
