### ISSUE TITLE
router error

### ISSUE THREAD

**Issue by maandoz** [rejetto/hfs#774]
- Are you using a reverse-proxy, like nginx?
  -- no

**To Reproduce**
  --  reproducible at every hfs start

**Describe the bug**
  --  i have a problem with router recognition.
       hfs writes this error message
       thanks

**Expected behavior**
What you expected to happen.

**Screenshots**
 
![router](https://github.com/user-attachments/assets/4f08aa5e-c85a-49f2-9e4b-6a748981f3ac)

**Environment (please complete the following information):**
 - OS: win 11 pro 64
 - HFS Version 0.54.0
 - Browser -- Chrome - Opera - Edge

**Additional context**

**Comment by rejetto** [comment]
thanks for reporting!
i've fixed the bug causing the error you see in the first screenshot.
anyway, that's just a bad handling of the refusal/error hfs is receiving from your modem/router.
So, even with the fix, you won't get your port mapped.
It's hard to say why, as i've seen modems behave wildly with upnp (the system used to request ports). My previous modem was buggy, and sometimes i needed to switch off/on upnp. My current modem works well with all ports but port 80, that works only if I map it manually from its configuration interface. So, if HFS fails, try manually.

**Comment by maandoz** [comment]
I'll do it that way.
Thanks for the correction and the suggestion.

**Comment by rejetto** [comment]
fixed in 0.54.0-rc9
