### ISSUE TITLE
Avoid using wmic

### ISSUE THREAD

**Issue by NN---** [rejetto/hfs#776]
wmic utility is deprecated: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/wmic
Modern Windows does not have this executable anymore.

It triggers for me AV detections due to the deprecation of wmic.

**Comment by rejetto** [comment]
i see

**Comment by rejetto** [comment]
my plan is to work on this in 0.55

**Comment by rejetto** [comment]
i'm closing this as 0.55 has been published (alpha1)
