### ISSUE TITLE
Direct links to the file and authorization

### ISSUE THREAD

**Issue by 6elkir** [rejetto/hfs#78]
**Describe the bug**
Greetings! If you send a direct link to a file to a person and he did not log in before, then instead of authorization -> file download, Not Found tells him and that's it. This is very inconvenient, especially if you don't need to show the file storage interface once again.

**Comment by rejetto** [comment]
I just tested and a direct link to a file is asking me to login, no "not found".
Double check and provide as many details as possible to reproduce it.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/1367199/201471735-63af8dac-959c-430e-a83a-bc5e1a5e9054.png">

**Comment by 6elkir** [comment]
I'm send to you email link for video demonstration)

**Comment by rejetto** [comment]
the video is showing the problem, but not how to make it happen from zero, so I don't how to reproduce it, and without this I won't be able to solve it.
If I make a protected file, or a protected folder, I get the login correctly.
You may
1. try to create a new hfs server and see what exactly takes to make the problem happen, and write here detailed instructions for me
or
2. send me your config.yaml, and maybe i can see something in it. In this case you may want to remove the "srp" lines, like this
<img width="95" alt="image" src="https://user-images.githubusercontent.com/1367199/201534533-2c4862fa-8d87-4512-bced-2d0c1a9b7f47.png">

TBH I suppose that even with a visible srp, [people cannot find your password ](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol)(that's the whole point), but if you want to take extra caution...

**Comment by 6elkir** [comment]
Hello, Im send config in email for you.
