### ISSUE TITLE
Piping not working in admin whitelist

### ISSUE THREAD

**Issue by reknor320** [rejetto/hfs#783]
-

**Comment by reknor320** [comment]
I dont know where that rubbish came from, just entered title, after going through stupidity with password to report this.
Anyway I was trying to edit the whitelist for admin access, if i use 192.168.1.* it is fine, but blocks localhost, but if I put 192.168.1.* | localhost, then both addresses get blocked from access, same with 192.168.1.* | 127.0.0.1. I had this issue trying to help security limiting admin access to local network only, and noticed the usual , and ; didn't work, then searched for config info, which luckily makes this very quick and easy to undo. This issue was seen in version 0.52.00 and is still present in the current 0.54.0.
Thank you for such a great fileserver programme.

**Comment by rejetto** [comment]
I see a space in your configuration. Network masks don't work with spaces in current version. Try to remove it.

Since space has no reason to exist in this context, i will make next version to ignore it.

**Comment by reknor320** [comment]
sorry, used to dos commands requiring a space to define the values from each other, works without any spaces, now just cant seem to get default localhost to work correctly. 127.0.0.1 works, but only as this address, not localhost and localhost doesn't seem to add the default either. list in settings put as "192.168.1.*|localhost" (excluding quotation marks)
![local](https://github.com/user-attachments/assets/287d0846-2cbd-4d42-9e28-c49ee636a426)
.
![localhost](https://github.com/user-attachments/assets/1c0fed41-c5a6-40bd-b9e0-7ac6f587e1d9), is there another special way to list localhost?

**Comment by rejetto** [comment]
this happens because localhost in many computers, like mine, is not translating "localhost" to 127.0.0.1 (which is ipv4) but to ::1 (which is ipv6)

you can see that in the "monitoring" or "logs" page

**Comment by reknor320** [comment]
oh, tried this and external address can now access admin.
![Clipboard02](https://github.com/user-attachments/assets/c6806e7d-fa29-4312-bf01-343444683afd)

**Comment by rejetto** [comment]
i cannot reproduce your problem.
i tried your same setting, and while i was able to access with an external address before (82.*) now i can't anymore (tried both from same computer and from another computer), while is still functioning on localhost. So, the block is working here.
maybe you can try to access "Monitoring" to see what address is HFS seeing actually.

also, i thought i can show this warning for people entering 127.0.0.1 without ::1
<img width="486" alt="image" src="https://github.com/user-attachments/assets/39fb5d86-e850-4f14-aa41-54f094b8a652">

**Comment by rejetto** [comment]
any idea?

**Comment by reknor320** [comment]
Sorry, I had lost this page. Using ::1 does indeed work, as I checked with a tablet at work, just checked log and found out that HFS is seeing a local address, as the main router is looping the external address back on its local address. I think this message would be quite helpful.Thank you very much for your help.

**Comment by rejetto** [comment]
ok, so it was a false alarm, good
