### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by arkprocession** [rejetto/hfs#79]
Thanks for this extremely powerful tool. is amazing.
Uploads are the only thing missing and that is it!

**Comment by rejetto** [comment]
thanks, duplicated for https://github.com/rejetto/hfs/issues/77

**Comment by rejetto** [comment]
you got it
https://github.com/rejetto/hfs/releases/tag/v0.27.0

**Comment by arkprocession** [comment]
> you got it https://github.com/rejetto/hfs/releases/tag/v0.27.0

Thanks for remembering!

But i don't see the upload button anywhere

**Comment by rejetto** [comment]
for the button to appear you have to give upload permission first.
at the moment upload permission is displayed (on admin-panel) only for folders on disk (that is, with source).

In next release I will display the upload permissions even without the source, and will have a small text specifying that you need the source.

**Comment by arkprocession** [comment]
> for the button to appear you have to give upload permission first. at the moment upload permission is displayed (on admin-panel) only for folders on disk (that is, with source).
> 
> In next release I will display the upload permissions even without the source, and will have a small text specifying that you need the source.

Ok going to have to extensively figure out how to give that permission.

Hopefully in future versions it will be more intuitive.

being secure or configurable doesn't mean we should miss it so easily, being something quite accesible for regular user in other plataforms.

just feedback :)

thanks for everything

**Comment by rejetto** [comment]
if you tell me how you expected it, it may be useful for improvements

**Comment by arkprocession** [comment]
> if you tell me how you expected it, it may be useful for improvements

all i can say is i use your tool almost every day.

And everything else is intuitive.

i dont know how i expect it to be  ut i tried to activate uploads and could not do it, for 10 minutes.

Will try again soon, and let you know once i figure out how to give permissions to specific users for uploads.

**Comment by rejetto** [comment]
First you must have a folder on disk, otherwise HFS won't know where to put the files you upload
Admin-panel → Menu → Shared files → Add → from disk → ...select a folder

Now you will see a field "Who can upload" on that folder.
You can set it as "anyone" or whatever fits your needs.

Now you gave permission for upload, and people accessing that folder will see a new "upload" button on the top bar.

**Comment by arkprocession** [comment]
> First you must have a folder on disk, otherwise HFS won't know where to put the files you upload Admin-panel → Menu → Shared files → Add → from disk → ...select a folder
> 
> Now you will see a field "Who can upload" on that folder. You can set it as "anyone" or whatever fits your needs.
> 
> Now you gave permission for upload, and people accessing that folder will see a new "upload" button on the top bar.

I understand now. Thanks
