### ISSUE TITLE
zipping folder with non english character causes zip name to contain ?

### ISSUE THREAD

**Issue by W-i-n-7** [rejetto/hfs#790]
i downloaded a folder containing the letter "Ö" in the name and the zip file it downloaded had a ? in a box inplace of the letter

i presume this bug is something to do with unicode and or ascii and also affects letters such as ä or å and others

**Comment by rejetto** [comment]
<img width="424" alt="image" src="https://github.com/user-attachments/assets/534ce384-07c7-431e-af8c-e72fc3ee14bb">

i can't reproduce you problem.
Any idea?

**Comment by W-i-n-7** [comment]
> <img alt="image" width="424" src="https://private-user-images.githubusercontent.com/1367199/380787768-534ce384-07c7-431e-af8c-e72fc3ee14bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzYzODIsIm5iZiI6MTczMDEzNjA4MiwicGF0aCI6Ii8xMzY3MTk5LzM4MDc4Nzc2OC01MzRjZTM4NC0wN2M3LTQzMWUtYWY4Yy1lNzJmYzNlZTE0YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTcyMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQyNWNjNzcyZTllNTY5ODUwY2YxOTI0NjEwODcyMWQ1MmYzY2MyNjBkYWJhYzQzNGVjOTY2OTQxNDIwMDBmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AF3b8nhrCxXxW9cCHAYwNRp267iqdxLDkE9n0tM-en4">
> 
> i can't reproduce you problem. Any idea?

os language?

**Comment by W-i-n-7** [comment]
on my phone on firefox its ? symbols but on pc its fine
that is really weird
my phone does support these characters btw

**Comment by rejetto** [comment]
confirmed, but only android firefox, chrome works well

**Comment by W-i-n-7** [comment]
odd

**Comment by rejetto** [comment]
should be fixed in 54-rc10, right?

**Comment by W-i-n-7** [comment]
lemme test

**Comment by W-i-n-7** [comment]
appears to be fixed
