### ISSUE TITLE
play .mov format video

### ISSUE THREAD

**Issue by DaddaDu** [rejetto/hfs#791]
Can play .mp4 format video, can not play.mov format video, want to add the function of playing .mov

**Comment by rejetto** [comment]
I just tested, and both Chrome and Firefox are playing some mov files i got, both on Windows and on Mac.
So I guess your problem is in the codec used by your files, and HFS cannot fix that. 
https://github.com/rejetto/hfs/wiki/FAQ#q-some-videoaudio-files-are-not-played-how-to-fix-it

**Comment by rejetto** [comment]
Starting with version 0.55, there's a plugin called "unsupported-videos" that can partially solve this problem, transcoding those videos in streaming (on the server).
