### ISSUE TITLE
How do I turn off upnp in this program?

### ISSUE THREAD

**Issue by mhidro** [rejetto/hfs#794]
How do I turn off upnp in this program?

**Comment by rejetto** [comment]
hfs does no automatic upnp action, what's your problem?

**Comment by mhidro** [comment]
If it doesn't then there is no problem, the configuration ui was just confusing to me and I thought it did. Thanks.

**Comment by rejetto** [comment]
I see. If you have a suggestion, what may make the UI less confusing on this matter?

**Comment by mhidro** [comment]
This line in the cli at startup made me start looking at the options in the admin for an upnp section. 
`13:20:32 upnp http://192.168.1.1:2828/gateway.xml`
Maybe don't query the upnp capability of the router without explicit user action? Or explicitly say "UPNP is off" near that line in the cli log. 

Another option is to have an explicit toggle or a box that say "UPNP: OFF" 
in `~/admin/#/internet`

**Comment by rejetto** [comment]
but can you explain what's good for the user in not searching for the gateway?
i can't write "upnp is off" because it's not true: hfs is reading from upnp, but not writing/changing until the user is asking.

**Comment by mhidro** [comment]
>but can you explain what's good for the user in not searching for the gateway?

Well, nothing in particular, it was a "personal" prefference for slightly paranoid people. I guess it can just be off completely if that is posible with a checkbox. I don't know if anyone would actually care about this.

**Comment by rejetto** [comment]
i would expect a paranoid user who's worried about upnp to disable it on the modem/router. Am I wrong?

**Comment by mhidro** [comment]
You're def right. Don't think about it too much. If you have the time maybe add some verbiage to the /internet config panel indicating if the upnp client is asking for a port forward or not.

**Comment by mattcheau** [comment]
Paranoid user here. I caught this at the host firewall level. 

I don't want any applications I use to even attempt to use UPnP/SSDP without an explicit toggle. @rejetto, can you explain why a UPnP client is even necessary for the app?

**Comment by rejetto** [comment]
@mattcheau  is not "necessary" but convenient, and it was roughly explained above.
In details, HFS uses upnp to talk to the router
- to map a port if the user asks for it
- to know if the port was already mapped (limited to mappings done via upnp on many routers)
- to detect double-NAT (and warn the user)

so, automatic usage is only for reading, while writing is user-triggered.
do you have upnp enabled on your router?
in the light of this, i wonder if it's still useful to have an option to turn it off.

**Comment by mattcheau** [comment]
> do you have upnp enabled on your router?

I do not make use of UPnP anywhere on the LAN I'm running HFS on, no.

> i wonder if it's still useful to have an option to turn it off.

My 2¢ would be either 1.) option to turn it off, or 2.) documentation—(or both) would be useful. I was surprised enough by these packets, given my impression of HFS as a lighter weight, purpose-built HTTP file server, to find my way here.

Thanks very much for your work.

**Comment by rejetto** [comment]
it's done, you will be able to switch it off in 3.2
