### ISSUE TITLE
Update for Japanese translation

### ISSUE THREAD

**Issue by Kuruton8** [rejetto/hfs#795]
[hfs-lang-ja.txt](https://github.com/user-attachments/files/17600005/hfs-lang-ja.txt)

Thanks for the hard work for this project. I really appreciate.

**Comment by rejetto** [comment]
thank you very much, it will be included in next release.

would you please translate also these 2 lines missing for version 0.54 ?
```
        "Cancel": "Cancel",
        "allow_session_ip_change": "Allow IP change during this session"
```

chatgpt suggests this:

    "Cancel": "キャンセル",
    "allow_session_ip_change": "このセッション中にIPアドレスの変更を許可する"

**Comment by Kuruton8** [comment]
The translation by ChatGPT is perfect. You can use them.
Thanks a lot.

**Comment by rejetto** [comment]
thanks!
