### ISSUE TITLE
When clicking on a file, the uploader's IP address will be displayed

### ISSUE THREAD

**Issue by QinYueQwQ** [rejetto/hfs#796]
Does this feature seem unable to be turned off? Or did I not find the corresponding method?

**Comment by rejetto** [comment]
hi, i decided to write this in the FAQ page
https://github.com/rejetto/hfs/wiki/FAQ#q-i-dont-want-my-ip-address-to-be-visible-how-can-i-hide-it

**Comment by QinYueQwQ** [comment]
Thank you, but I think you may not understand what I mean.
When using the front end, after an uploader uploads a file, the uploader's IP address will appear in the secondary menu of the file.
like this:
![image](https://github.com/user-attachments/assets/8b3ca9e1-e8c6-4ec0-b646-496d0714fb49)
And Click it:
![4a4f88c734fdfa79eaf9f7604dcc8ef9](https://github.com/user-attachments/assets/087a20ba-4823-4721-acf3-ec3a9d7872ea)
I would like to be able to turn this off, but I can't seem to find an option in the settings

**Comment by rejetto** [comment]
i'm sorry, i didn't read the title right :)
starting with version 0.54, the IP is displayed only if you are an admin.
There's no option at the moment, just this new behavior.

**Comment by QinYueQwQ** [comment]
I see, thanks for your reply!

**Comment by rejetto** [comment]
what version were you using?

**Comment by QinYueQwQ** [comment]
0.53.0
Maybe it's time to update :p
When version 0.54 was released

**Comment by rejetto** [comment]
0.54 will be official very soon, last days in the "beta" channel.
latest official version is 0.53.2, you can see it by clicking "check for updates" button.

**Comment by QinYueQwQ** [comment]
OK, thanks for your reminder.

**Comment by CMJNB** [comment]
I would also like the name to be hidden, or only visible to administrators.

---

<details>
<summary>🌐 点击展开中文翻译</summary>

> 我希望名字也能隐藏，或者只给管理员开放。

</details>

**Comment by rejetto** [comment]
@CMJNB i will add this to 3.2
