### ISSUE TITLE
Need button in Monitoring - Disconnect all connections except local ones

### ISSUE THREAD

**Issue by deamon2k** [rejetto/hfs#797]
Need button in Monitoring - Disable all connections except local ones

**Comment by rejetto** [comment]
what do you mean by local, same pc or same local network?

**Comment by deamon2k** [comment]
These challenges
```
[::1] :7423 1:57:36 PM /~/api/get_connections? 200 B/s 3.4 MB
[::1] :7424 1:57:36 PM /~/api/get_connection_stats? 100 B/s 1.7 MB
```
Probably not necessary Disable?

**Comment by rejetto** [comment]
ok, ::1 is the same pc

you say "disable all...", but what do you mean by "disable" ?

**Comment by deamon2k** [comment]
Disconnect

**Comment by rejetto** [comment]
ok, now it's clear.
i guess it can be an interesting feature.

**Comment by rejetto** [comment]
ok, you'll get it with version 0.55

**Comment by deamon2k** [comment]
Move the Disconnect all button to the top of the interface. Scrolling is pointless. Why was selective disconnect removed?

**Comment by rejetto** [comment]
in all of my tests the button is visible without scrolling. Do you need to scroll?

By "selective" you mean for a single connection? it was not removed. It is still visible on the row if your screen is large enough, or otherwise you have to click on a connection.
