### ISSUE TITLE
"Proxy" directory feature

### ISSUE THREAD

**Issue by istvanmate** [rejetto/hfs#800]
**Is your feature request related to a problem? Please describe.**
No. Yes, if you consider not being able to watch IPTV outside of the country a problem...

**Describe the solution you'd like**
I am not sure, if this is already implemented, or can be done with available features, if so, please help me set it up.
I would like to add a virtual directory, under which every requested resource will be downloaded from a specified URL. For example:
1. virtual directory **/m4psort** to proxy to **https://c201-node62-cdn.connectmedia.hu/150104/8f8ef36a046f22d867efbb4dcae8af25/672b53b4**
2. request comes in for /m4sport/index.m3u8
3. hfs to dowload **https://c201-node62-cdn.connectmedia.hu/150104/8f8ef36a046f22d867efbb4dcae8af25/672b53b4/index.m3u8**
4. hfs to serve the downloaded content as **/m4sport/index.m3u8**

**Describe alternatives you've considered**
I have currently a PowerShell script doing this, it mostly works with VLC, but stalls with ffmpeg. Also it has to run on a different port.

**Additional context**
The redirect URL is quite dynamic, I update it hourly, so the possibility to update it with a script would also be required.

**Comment by istvanmate** [comment]
Just found out (and tested), that the reverse proxy plugin does exactly this. Now the question, how can I update the target URL with a script...

**Comment by rejetto** [comment]
you say "a script", i guess you mean one external to hfs.
one option is to modify config.yaml, as that's where the information is saved, but i don't advice that.
Your best option is calling set_plugin on localhost, so you don't need to authenticate
`curl 'http://localhost/~/api/set_plugin'  -H 'x-hfs-anti-csrf: 1' --data-raw '{"id":"reverse-proxy","config":{"routes":[{"path":"/rev","url":"http://rejetto.com"}]}}'`

**Comment by istvanmate** [comment]
Awesome! Managed to update with PowerShell as well with
```
Invoke-RestMethod -Uri 'http://localhost/~/api/set_plugin' -Headers @{"x-hfs-anti-csrf" = 1} -Method POST -Body ('{"id":"reverse-proxy","config":{"routes":[{"path":"/m4sport","url":"'+$m4sport+'"}]}}')
```
One issue though, when I execute the update for multiple redirects, then all redirects will be deleted, only the last updated remains.

**Comment by istvanmate** [comment]
By the way, internal (scheduled?) script would also be ok, I just did not find any schedulers in hfs.

**Comment by istvanmate** [comment]
Just realized, that 
```PowerShell
{"routes":[{"path":"/m1","url":"'+$m1+'"}, {"path":"/m4sport","url":"'+$m4sport+'"}]}}
```
will work perfectly.

**Comment by rejetto** [comment]
yes, since you are setting the whole configuration for the plugin, you must find your way, like keeping all in memory between writings, or using get_plugin just before set_plugin.

hfs doesn't have a scheduler at the moment, but you have the whole javascript available, so you may do `setInterval(whatever, 60*60*1000)`, but in such case remember to cancel the interval when the plugin is unloaded.

**Comment by rejetto** [comment]
ok, i guess this is done

**Comment by istvanmate** [comment]
Yes, thank you very, very much!
