### ISSUE TITLE
Chunk uploads to HFS

### ISSUE THREAD

**Issue by kran27** [rejetto/hfs#804]
Cloudflare's proxy limits post request bodies to 100MB, (unless you're on a business or enterprise plan, which i'm gonna assume most people are not) meaning any upload larger will fail.

The only workaround is not not proxy through Cloudflare for uploads, which exposes your IP, and makes something like running it behind a tunnel impossible (which also restricts other software which wants to use standard HTTP ports)

**Comment by rejetto** [comment]
you are lucky, version 0.54 has split-uploads feature.
it's almost official release, but if you want it today you can enable update to beta versions.

**Comment by kran27** [comment]
what timing lmao, thank you for such a quick response aswell
