### ISSUE TITLE
Can't search plugin, but plugin update seems functional

### ISSUE THREAD

**Issue by Xingeqwd** [rejetto/hfs#812]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  nono, proxy not impact the issue, 
  host machine can directly visit GITHUB, but glitch also happend when visit in the host machine

**To Reproduce**
1. Go to plugin
2. type theme or hfs , etc... (Keywords present in the plugin library)  in the search text box
3. Click on search
4. see nothing searched

**Describe the bug**
Searching doesn't find anything, but the textwords is exist in the plugin repo,
the update check seems to be working fine 
(no errors in frontend and backend, also no errors when searching)

This is not caused by HFS access github too manytime.

**Expected behavior**
 Plugin search can get result normally

**Screenshots**
![image](https://github.com/user-attachments/assets/ccc9f8a8-becf-4936-863b-a5d2deddf3d5)
![image](https://github.com/user-attachments/assets/69e4d62c-e9bd-4fbd-a2ec-f30f9070f9e4)
![image](https://github.com/user-attachments/assets/90ad2c47-4a89-4e90-b49d-465fe192de01)

**Environment (please complete the following information):**
 - OS: Windows
 - HFS Version: 0.54.0
 - Browser: chrome, firefox, edge, IE

**Additional context**
This is indeed a weird problem. 
There are no errors in the background and front end of the program, and the local machine can also access it.

If it is really inconvenient, it doesn’t matter! 
I can still install it manually. I just raised an issue so that future visiter can know these.

That HFS3 is really a masterpiece! especially when we know WEBDAV function in coming, hurray!

**Comment by rejetto** [comment]
hey!
please do this
- press F12, you'll see a panel in the browser, it's called dev-tools, and it looks like this
<img width="405" alt="image" src="https://github.com/user-attachments/assets/239269f4-a099-4435-9bdf-00846628fea9">

- access the plugis page, so you can see the problem
- now take 2 screenshots of dev-tools, for "console" and for "network"
- take another screenshot in admin-panel > logs > console

**Comment by Xingeqwd** [comment]
@rejetto 
hello sir


Ah, yes, i forgot i can see the console, its errored the 401
I guess this might be my proxy problem when your program requesting the github API?

thank you a lot lot! 
You are a kind people, sir!
If you need anything else, pls say, i will provid you!
___________
 photo are as followed:
![image](https://github.com/user-attachments/assets/5b3a70d8-d5a0-46a6-bb2b-2879fe162819)
![image](https://github.com/user-attachments/assets/8ee34038-5d4a-4954-b4cc-918d43bb62af)

**Comment by rejetto** [comment]
401 is not on the plugins requests, which are only in the second screenshot.
you forgot this: 
> take another screenshot in admin-panel > logs > console

**Comment by Xingeqwd** [comment]
@rejetto  
SIR, Sorry to bothering, Long time no reply！
I didn't pay enough attention to the email
below is my screenshot pls see:
![image](https://github.com/user-attachments/assets/266d350e-6173-4d7f-86cb-736bd00f29fc)

This is indeed a wried problem, because we can see no error in the log.
i guess This problem may be attributed to GitHub, that's doesn't big matter

If its doesn't conveniencet to solve, we can feel free to forget it. 
I can still update it manually, thank you!

**Comment by rejetto** [comment]
don't worry, i don't expect you to reply in minutes :)
and I AM interested in understanding your problem, because i still don't know why you have it, so i cannot exclude 100% that is something that HFS can solve.
If I had the same problem on my computer (or a computer i can handle), it would be easier.

let's see,
you published a screenshot to show that you can access github, but that's the computer where the browser runs. Are you sure it's the same computer where HFS runs? i can't say from you screenshot because the address bar of the browser is not visible.

**Comment by Xingeqwd** [comment]
certainly, sir

i using chrome to visit page, and HFS process is just Running beside him
(
Simply put, I visit the page on the localhost
)

If there is anything else I don't explain clearly, please tell me.

**Comment by rejetto** [comment]
admin-panel > internet: is "verify" working?

even better: launch hfs with --dev parameter.
now, the console should report much more information.
If now i go to "search online", that's what i see
<img width="515" alt="image" src="https://github.com/user-attachments/assets/f0c34809-efa8-43e2-b6b1-ae8d55e74b59">

what do you see?

**Comment by rejetto** [comment]
verify your firewall settings about hfs. Maybe you accidentally blocked its access to internet.

**Comment by Xingeqwd** [comment]
@rejetto 
AH, i reply late again sir, SRY for inconvenience!

when i visit the panel > internet > verify, i see:
![image](https://github.com/user-attachments/assets/f1b7a39f-301c-427a-a284-b70f78f8de25)

and after i searched the plugin, console says( this 200 seems normal ?):
![image](https://github.com/user-attachments/assets/f03b805f-4fb7-46dd-b719-402d9b565a67)

and, i have added a rule in the windows firewall advanced.. "Allow all outbound links from HFS"
after that, problem exist

——————————————

AND May I ask, will HFS access GITHUB through the system proxy?
My network here needs a proxy to access GITHUB, otherwise it will not be accessible。。。

Thank you sir! you are a kind good people!

**Comment by rejetto** [comment]
> AND May I ask, will HFS access GITHUB through the system proxy?

nope, and i guess that's the reason for your problem!
generally, don't assume a software works with (outbound) proxies, and even more, don't assume it does it automatically. 😄

**Comment by rejetto** [comment]
i hope in the future i will add support for outgoing proxies.
If/when i will, i will let you know here, so you can subscribe this issue.
For the moment i'm closing this, as it's not a bug, but thanks for letting me find out.

**Comment by Xingeqwd** [comment]
OKAY sir, thanks and Sorry to trouble you!

Looking forward to the WEBDAV function, 

And thank you again for your great work! 

I will try to find some opportunity to sponsor! (When I have a little spare money)

**Comment by rejetto** [comment]
0.56 will support and let you configure an outbound proxy.

**Comment by Xingeqwd** [comment]
> 0.56 will support and let you configure an outbound proxy.

Thank you for the notice, kindhearted sir!

**Comment by rejetto** [comment]
available in 0.56.0-alpha1

**Comment by Xingeqwd** [comment]
> available in 0.56.0-alpha1

thank you sir! 

——————

But pardon me please, we are actually more looking forward to the WEBDAV function.

（
Actually, I noticed that you talked about this in mid-October 24, 
and it seemed that there are some difficulties. 
Can I ask about the progress regard this?
）

There are really very few open source and good on use webdav server tools in the world, 
Either the price is high or there are many restrictions (such as the "same time login amount limit" of RAIDRIVE).

So I don't have a webdav server yet. If the function is launched, I will definitely try my best to make a donation!

**Comment by rejetto** [comment]
sorry, no progress on webdav.
as i wrote in the dedicated discussion that you referring to, my plan is to work on webdav after version 3.0

**Comment by Xingeqwd** [comment]
> sorry, no progress on webdav. as i wrote in the dedicated discussion that you referring to, my plan is to work on webdav after version 3.0

Ah, okay, i see, I understand, 

(Actually, I didn’t see the saying about “webdav release after version 3.0”, But I know now)

Also thank you in the same!  The existing functions are already very good enough.

**Comment by Xingeqwd** [comment]
@rejetto Hello sir
Parden me to ask an other question please,
I just found that after replacing and updating the exe file, 
the configuration file will be cleared. 
Just ask in case, Will the program do this?

**Comment by rejetto** [comment]
please write in a new discussion
https://github.com/rejetto/hfs/discussions/new?category=general
