### ISSUE TITLE
ZIP button does not have a label, can't be hidden

### ISSUE THREAD

**Issue by ThePanzafahra** [rejetto/hfs#815]
On the top bar of the server, all buttons have a label, such as #login-button, #options-button etc. - the ZIP button, however, does not.

![options button with label](https://github.com/user-attachments/assets/01546d60-53b3-4261-b25c-eb0c1ff7671f)
![zip button with no label](https://github.com/user-attachments/assets/f774a9cc-423d-47a4-bd1a-f91b5e2451d9)

While, obviously, the ZIP option can be disabled server-wide by selecting "No one can zip" on the home directory, it'd also be a good alternative to simply be able to hide the button in the style section.

**Comment by rejetto** [comment]
look closer
<img width="432" alt="image" src="https://github.com/user-attachments/assets/55f848f7-c6fb-46aa-8a6e-10cb7a6210d1">

the zip button needs an A to wrap it, and that's where the id is. 
You can hide it with *style* as you expect 😉
