### ISSUE TITLE
Deleted himself

### ISSUE THREAD

**Issue by Antro24** [rejetto/hfs#816]
hfs kept closing.
But we moved to a new level, he left.
Is this how it should be?

We're talking about 55 alpha.

**Comment by Antro24** [comment]
Just noticed that windows defender detects this as a threat.

**Comment by Antro24** [comment]
Program:Win32/Contebrew.A!ml

**Comment by Antro24** [comment]
<img width="574" alt="Screenshot_2" src="https://github.com/user-attachments/assets/7f108657-656e-49f5-8bdd-bdd4934ea175">

In general, I miss this program, it was better, although not safe.

**Comment by rejetto** [comment]
> Just noticed that windows defender detects this as a threat.

this is a known problem,
please refer to https://github.com/rejetto/hfs/wiki/Antivirus

**Comment by Antro24** [comment]
> > Только что заметил, что Защитник Windows определил это как медицинское.
> 
> Это известная проблема, пожалуйста, обратитесь к [https://github.com/rejetto/hfs/wiki/Antivirus.](https://github.com/rejetto/hfs/wiki/Antivirus)

This did not happen before version 55; the standard Windows antivirus did not react like that.

**Comment by rejetto** [comment]
it did not happen on your computer, but happened on many other computers, otherwise i wouldn't have made that wiki page 😬

the behavior of the antivirus changes in time, because in the meantime people reports the program as safe.

i had the same kind of problem with HFS 2.*

**Comment by Antro24** [comment]
I hope someday v2.x.x will continue to exist separately. 
This program has so many functions, and it should not disappear without a trace.

**Comment by rejetto** [comment]
i hope it too, that someone has the will to continue it
