### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by EinsteinIamNot** [rejetto/hfs#819]
i was running hfs latest alpha verions on a win 2019 server
Yesterday 22nd of november the hfs.exe file was deleted by windows defender
Alert level: severe
Status:  quarantained
category: trojan
Win32/Wacatac.B!ml

Details: This program is dangerous and executes commands from an attacker.

**Comment by rejetto** [comment]
hi, read here https://github.com/rejetto/hfs/wiki/Antivirus
