### ISSUE TITLE
Code Errors and Bug

### ISSUE THREAD

**Issue by lighting9999** [rejetto/hfs#823]
# BUG Report
## Security Issues
Data Tampering: If `this.sent` can be maliciously modified from outside, the calculated speed will be inaccurate. Ensure that the value of sent can only be updated through controlled methods.
Accuracy of Timestamps: If the system time can be changed by users or attackers, this will affect the accuracy of the speed calculation. In most cases, this won't be a serious issue, but if the application is time-sensitive, it should be considered.
## Code Errors/Improvement Suggestions
Variable Initialization: Make sure `this.lastSpeedTime` and this.sent are properly initialized in the class constructor. For example, `this.lastSpeedTime` should be set to the timestamp at the first call, and this.sent should initially be set to 0.
Precision Issue: When past is close to 1000 milliseconds, it may lead to frequent resets of lastSpeedTime and sent, which could affect the smoothness of the speed calculation. Consider using a longer time window to reduce fluctuations.
Unit Consistency: Confirm that the unit of `this.sent` is consistent with the returned speed unit. If sent is in bytes and you want the result in kilobytes per second (kB/s), you should divide by 1024 instead of just past.
Floating Point Handling: `this.sent / past might` produce a floating-point result. If you want to keep the result as an integer (e.g., always return integer kB/s), you need to decide how to handle the decimal part (e.g., rounding).
Exception Handling: Although the current logic ensures that past will not be 0 due to the `>= 1000` check, it's still a good practice to avoid division by zero errors. Adding some defensive programming practices would be beneficial.
Performance Optimization: If getSpeed is called frequently, executing `Date.now()` each time might have a slight performance overhead. If this becomes a bottleneck, consider updating the time only when necessary.

## Example of Improved Code
```JavaScript
class DataTransferMonitor {
    constructor() {
        this.sent = 0;
        this.lastSpeed = 0;
        this.lastSpeedTime = Date.now();
    }

    updateSent(amount) {
        this.sent += amount; // Assuming amount is in bytes
    }

    getSpeed() { // The returned speed unit is kB/s
        const now = Date.now();
        const past = now - this.lastSpeedTime;
        if (past >= 1000) {
            this.lastSpeedTime = now;
            this.lastSpeed = Math.round((this.sent / 1024) / (past / 1000)); // Convert bytes to kilobytes and adjust time to seconds
            this.sent = 0;
        }
        return this.lastSpeed;
    }
}
```
## Affected code
```JavaScript
  ​    ​// @return kBs 
 ​    ​getSpeed​(​)​: ​number​ ​{ 
 ​        ​const​ ​now​ ​=​ ​Date​.​now​(​) 
 ​        ​const​ ​past​ ​=​ ​now​ ​-​ ​this​.​lastSpeedTime 
 ​        ​if​ ​(​past​ ​>=​ ​1000​)​ ​{​ ​// recalculate? 
 ​            ​this​.​lastSpeedTime​ ​=​ ​now 
 ​            ​this​.​lastSpeed​ ​=​ ​this​.​sent​ ​/​ ​past 
 ​            ​this​.​sent​ ​=​ ​0 
 ​        ​} 
 ​        ​return​ ​this​.​lastSpeed 
 ​    ​}
```

**Comment by rejetto** [comment]
so you hope that chatgpt can make you discover this kind of problems, right? 😄
i'm sorry but we are not there yet
