### ISSUE TITLE
Alpha - update issue

### ISSUE THREAD

**Issue by Gladiejathor** [rejetto/hfs#825]
hey there,

**To Reproduce**
Steps to reproduce the behavior: WINDOWS
1. Go to 'v53 - admin panel - do update '

**Describe the bug**
seems du run teh update, also download done. while  processing, the .exe will be renewed?/deleted.
in the restart process something faild badly.   sometimes the .exe just vanish, sometimes startet old version.

**Environment (please complete the following information):**
 - OS: Windows
 - HFS Version 53 to 55
 - while starup / update

**Additional context**
start the renamed old .exe will perfecly fine start old server. update to 54 is fine.
54 to 55 not testet yet.

PS THANKS for all the hard work =D

**Comment by rejetto** [comment]
hey!
this sounds like your antivirus deleting the new version.
Find more about it at https://github.com/rejetto/hfs/wiki/Antivirus

**Comment by rejetto** [comment]
did you solve?

**Comment by Gladiejathor** [comment]
yes
