### ISSUE TITLE
Termux install error port 80

### ISSUE THREAD

**Issue by accnetdev** [rejetto/hfs#827]
Hi Massimo,

Trying to install hfs3 (0.54.0) on my mobile phone in termux.

After thé installation of nodejs-lts
This is thé result of thé npx hfs@latest :

15:08:40 HFS ~ HTTP File Server
15:08:40 © Massimo Melina <a@rejetto.com> - License https://www.gnu.org/licenses/gpl-3.0.txt
15:08:40 started 12/4/2024, 3:08:40 PM
15:08:40 version 0.54.0
15:08:40 build 2024-11-09T13:54:41.802Z
15:08:40 working directory (cwd) /data/data/com.termux/files/home/.hfs
15:08:40 app /data/data/com.termux/files/home/.npm/_npx/95660a09cc333978/node_modules/hfs
15:08:40 node v20.17.0
15:08:40 platform android node
15:08:40 pid 12512
15:08:40 config config.yaml
15:08:40 No config file, using defaults
15:08:40 HINT: type "help" for help
15:08:40 fs-x-attributes not available
15:08:40 upnp http://192.168.1.254:5678/desc/root
15:08:40 http lacking permission on port 80, try with permission (sudo) or port > 1024
15:08:40  >> try specifying a different port, enter this command: config port 1080
15:08:42 loading plugin antibrute
1080
15:09:13 cannot understand entered command, try 'help'
1080
15:11:20 cannot understand entered command, try 'help'

I'm stucked in thé installation process and don't know how to fix thé error of port.

Thanks

**Comment by rejetto** [comment]
hey!
apparently you are entering just "1080" while it is suggesting "config port 1080" ?

**Comment by accnetdev** [comment]
I tried 1080 or 1001 (to be under 1024) but I'm stucked in the installation script nothing happens with any values.

**Comment by rejetto** [comment]
the problem was not the number, but the way you were typing the command.
it is not clear from your last message if you understood that.

btw, that's not an installation script, it's the program.

**Comment by accnetdev** [comment]
Sorry now I have Understood!
I just typed : config port 1080 and I get localhost:1080/~/admin/ in my default browser. GREAT!

I will go ahead later: my goal is to use HFS running on my mobile from anywhere (with mobile data as well as wifi) as I have done it with some other Android LAMP apk.

have you made any progress on the webdav to HFS?

**Comment by rejetto** [comment]
nope, i'm working on other things

**Comment by accnetdev** [comment]
OK, no problem we can do without ;-)
But it could be cool!
Have a good day.
