### ISSUE TITLE
Romanian language pack - update

### ISSUE THREAD

**Issue by 0xy99** [rejetto/hfs#832]
Hello, community!
I have modified the file for translation and adaptation to Romanian language pack and I want to upload it here, so that you can put it into production for future versions. I would like to propose in the future, some method by which we can personalize user accounts by choosing a profile picture, etc...
As mentioned in a previous post, it would be very useful to implement FTP of such a server.
Have a nice day!

[hfs-lang-ro.json](https://github.com/user-attachments/files/18112033/hfs-lang-ro.json)

**Comment by rejetto** [comment]
thank you!
it will be included in next release.
for the account picture, please open a separate issue
