### ISSUE TITLE
Creating private folders for each user.

### ISSUE THREAD

**Issue by xDololow** [rejetto/hfs#834]
Is it possible to create private folders for users automatically?  I want to create some amount of users and make them have private folders.

**Comment by rejetto** [comment]
there's no such feature, and it's not planned.
and yet, HFS configuration is a text file (config.yaml). Once that you've created one user with its folder, you may find a way to replicate faster using a text editor.

would you care to describe how do you imagine this feature would be exactly?

**Comment by xDololow** [comment]
> Once that you've created one user with its folder, you may find a way to replicate faster using a text editor.

Yeah, I did exactly that.

> would you care to describe how do you imagine this feature would be exactly?

maybe additional setting for private user folder that accessible only by user (maybe admin as well). But its fine for now
