### ISSUE TITLE
got an error when select "add file" to upload

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#87]
**Describe the bug**
when upload a single file, console window will report the error everytime, but the frontend webpage wasn't show any warning.

**To Reproduce**
1.using "add file" method to upload a file;
2. the error message popup in the console window

**Screenshots**
![image](https://user-images.githubusercontent.com/59822418/212582198-ad2f67f6-585d-46f0-855b-3dbe075fe804.png)

**Environment (please complete the following information):**
 - OS: windows 10 22H2 ProfessionalWorkstation Version
 - Browser: Firefox 108.0.2 & Google Chrome 108.0.5359.125 (X64)
 - Version: 0.27.0

**Comment by dzw13579** [comment]
If I use "add folder" button, It's OK after tranmit the entire folder

**Comment by rejetto** [comment]
ok i got to reproduce the problem and will let you know

**Comment by rejetto** [comment]
should be fixed
https://github.com/rejetto/hfs/releases/tag/v0.27.1
