### ISSUE TITLE
prevent users to ban LocalHost IP

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#88]
**Is your feature request related to a problem? Please describe.**
when I using the account with admin privilege in "Monitoring" page, I try to ban a IP  to stop it access my service, but I click my LocalHost IP by mistake, So I can't continue my operation, and I have to stop HFS and undo the ban operation in config file😂.

**Describe the solution you'd like**
enlarge the pre rule coverage to every accounts that stop people to block LocalHost IP when using Localhost IP in Backend, this rule work in "admin" account only. Or, set a rule to stop people banning the IP he(or she) login to the Backend?

**Comment by rejetto** [comment]
done in latest version
https://github.com/rejetto/hfs/releases/tag/v0.27.1
