### ISSUE TITLE
Ability to Delete Files, Folders.

### ISSUE THREAD

**Issue by arkprocession** [rejetto/hfs#90]
Is it being worked on?

Thank you

**Comment by rejetto** [comment]
it's in to-do.
do you have suggestion on you'd like the interaction to be?

**Comment by arkprocession** [comment]
> it's in to-do. do you have suggestion on you'd like the interaction to be?

Not really but thanks :)

It's a damn fine job this tool.

What about Drag & Drop, Ability to reproduce media like video, music or edit txt right from web.?
Also something cool would be a share link that can be encrypted.

**Comment by rejetto** [comment]
thanks
drag&drop: where/what/why?
reproduce: maybe
edit: maybe as plugin
encrypted link: what does it mean?

main problem is that's only me working on this, in my spare time.
I'm trying to keep things neat enough to interest someone in helping.

**Comment by arkprocession** [comment]
> thanks drag&drop: where/what/why? reproduce: maybe edit: maybe as plugin encrypted link: what does it mean?
> 
> main problem is that's only me working on this, in my spare time. I'm trying to keep things neat enough to interest someone in helping.

For example upload files from desktop dragging them to the windows, like in Filebrowser.
Encrypted link for example : firefox send, or filebrowser.

Where you can zip a content from your file server and share it through a link without authentication , or at least with a password.

**Comment by rejetto** [comment]
sorry for the late reply.
adding drag&drop for upload in to-do.
the link thing is interesting and something like it was already in my mind, but its properties must be defined very well.
I guess it would have nothing to do withe VFS.

**Comment by rejetto** [comment]
btw, drag&drop done

**Comment by rejetto** [comment]
ok, we've go also the 'delete', and now you can play music files by installing a plugin, "simple-player"
https://github.com/rejetto/hfs/releases/tag/v0.34.0
