### ISSUE TITLE
download zip file without file format suffix under "Fliter List"

### ISSUE THREAD

**Issue by dzw13579** [rejetto/hfs#92]
**Describe the bug**
as the title said,  select one of the share folders' root path, using "download zip" in "Filter list" to select any folders or files to download, the "save as"window will only show "zip"as file name, without file format suffix.
this bug show in root path files or folders download only. 

**To Reproduce**
Please take a look the screenshots below

**Screenshots**
1.
![3](https://user-images.githubusercontent.com/59822418/213340835-dcd8180b-ff38-4706-80e6-99757bc185cd.png)
2.
![4](https://user-images.githubusercontent.com/59822418/213340852-6fbf600c-e718-47a8-9bb3-498d0eef621c.png)

**Comment by rejetto** [comment]
fixed in next release
thanks
