### ISSUE TITLE
Not able to share a file on a network drive on Windows

### ISSUE THREAD

**Issue by TheReptile** [rejetto/hfs#93]
**Describe the bug**
I want to share a file which is located on a mapped network drive under Windows.
This is currently not possible.

**To Reproduce**
1. Go to The Admin interface -> Shared Files -> ADD -> from disk
2. Click on the root button
3. Notice mapped network drives are not available

**Expected behavior**
Being able to add a file from a network drive which is mapped to a drive letter.

**Environment (please complete the following information):**
 - Windows 10 22H2
 - Firefox 109
 - Version 0.28

**Comment by rejetto** [comment]
I noticed that HFS sees my network drive unless I run it as "service", then it doesn't.
Setting the service with my user account didn't work.
So i made a quick search and found that it is a [known behaviour of Windows](https://stackoverflow.com/questions/182750/map-a-network-drive-to-be-used-by-a-service).

Can you confirm you are using HFS as service?

**Comment by TheReptile** [comment]
I don't run HFS as a service, but I do run it as administrator. (I was using a privileged port.) I've updated the config to use a non-privileged port. Now all is well when I run it normally. Thanks for this hint!

**Comment by rejetto** [comment]
thanks for sharing.
Try to have a look at this:
https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/mapped-drives-not-available-from-elevated-command#cause

**Comment by TheReptile** [comment]
I had a look at the page you mentioned and applied the registry edit. 
When starting HFS with elevated rights, the mapped drives are available.
So this seems to be a nice solution.

Thanks!
