### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by heeroyuyj** [rejetto/hfs#99]
Is there a way to add the ability to configure multiple languages? For example, a standard language template that can be translated into other languages? (if it is possible)

I am a Chinese user, so I would like to Chineseize it

**Comment by rejetto** [comment]
there's no way for you 🙃, at the moment.
It will take a few hours (of my work) to make it possible, and I will do it, just don't know when.
#32

**Comment by rejetto** [comment]
multilanguage is added in latest version
